FILE = r'C:\Users\jason\OneDrive\Documents\GitHub\mabel-gcse\js\maths-questions.js'
MARKER = "    {\n      id: 'pro-A01'"

NEW = """    {
      id: 'sim-A03', subtopic: 'alg-simultaneous', band: 'A', marks: 3,
      question: 'Solve the simultaneous equations: y = 3x + 1 and y = x + 5.',
      steps: [
        {
          prompt: 'Set the two expressions for y equal: 3x + 1 = x + 5. Collect x terms.',
          hint1: '3x − x = 5 − 1.',
          hint2: '2x = 4.',
          hint3: '2x = 4.',
          answer: 4, tolerance: 0, unit: '',
          explanation: '3x + 1 = x + 5 → 2x = 4.',
        },
        {
          prompt: 'Find x.',
          hint1: '2x = 4 → x = ?',
          hint2: 'x = 2.',
          hint3: 'x = 2.',
          answer: 2, tolerance: 0, unit: '',
          explanation: 'x = 4/2 = 2.',
        },
        {
          prompt: 'Substitute x = 2 into y = x + 5.',
          hint1: 'y = 2 + 5.',
          hint2: 'y = 7.',
          hint3: 'y = 7.',
          answer: 7, tolerance: 0, unit: '',
          explanation: 'y = 2 + 5 = 7. Solution: x = 2, y = 7.',
          displayAnswer: 'x = 2, y = 7',
        },
      ],
      workedExample: {
        question: 'Solve y = 2x − 1 and y = x + 4.',
        steps: [
          '2x − 1 = x + 4 → x = 5.',
          'y = 5 + 4 = 9.',
          'Solution: <strong>x = 5, y = 9</strong>. Verify: 2(5)−1=9 ✓',
        ],
      },
      sampleAnswer: {
        grade4: 'x = 2, y = 7',
        grade6: '3x+1 = x+5 → 2x = 4 → x = 2. y = 7.',
        grade8: 'Set equal: 2x = 4 → x = 2, y = 7. Verify both: 3(2)+1=7 ✓ and 2+5=7 ✓',
      },
      examinerTip: 'When both equations give y in terms of x, set them equal and solve. This substitution method avoids rearranging.',
      auditStatus: 'pending',
    },
    {
      id: 'sim-A04', subtopic: 'alg-simultaneous', band: 'A', marks: 3,
      question: 'Solve the simultaneous equations: 3x + y = 11 and x + y = 5.',
      steps: [
        {
          prompt: 'Subtract equation 2 from equation 1 to eliminate y.',
          hint1: '(3x + y) − (x + y) = 11 − 5.',
          hint2: '2x = 6.',
          hint3: '2x = 6.',
          answer: 6, tolerance: 0, unit: '',
          explanation: 'Subtracting: 2x = 6.',
        },
        {
          prompt: 'Find x.',
          hint1: '2x = 6 → x = ?',
          hint2: 'x = 3.',
          hint3: '3.',
          answer: 3, tolerance: 0, unit: '',
          explanation: 'x = 3.',
        },
        {
          prompt: 'Substitute x = 3 into x + y = 5.',
          hint1: '3 + y = 5 → y = ?',
          hint2: 'y = 2.',
          hint3: 'y = 2.',
          answer: 2, tolerance: 0, unit: '',
          explanation: '3 + y = 5 → y = 2. Solution: x=3, y=2.',
          displayAnswer: 'x = 3, y = 2',
        },
      ],
      workedExample: {
        question: 'Solve 4x + y = 14 and x + y = 5.',
        steps: [
          'Subtract eq2 from eq1: 3x = 9 → x = 3.',
          'y = 5 − 3 = 2.',
          'Solution: <strong>x = 3, y = 2</strong>. Verify: 4(3)+2=14 ✓',
        ],
      },
      sampleAnswer: {
        grade4: 'x = 3, y = 2',
        grade6: 'Subtract: 2x = 6 → x = 3. y = 5 − 3 = 2.',
        grade8: 'Eliminate y by subtraction: 2x=6, x=3. Sub: y=2. Verify: 3(3)+2=11 ✓',
      },
      examinerTip: 'When the y-coefficients are the same (both 1 here), subtract equations to eliminate y. Choose which to subtract based on which gives a positive result.',
      auditStatus: 'pending',
    },
    {
      id: 'sim-A05', subtopic: 'alg-simultaneous', band: 'A', marks: 4,
      question: 'Solve the simultaneous equations: 5x − y = 9 and 2x + y = 12.',
      steps: [
        {
          prompt: 'Add the two equations to eliminate y.',
          hint1: '(5x − y) + (2x + y) = 9 + 12.',
          hint2: '7x = 21.',
          hint3: '7x = 21.',
          answer: 21, tolerance: 0, unit: '',
          explanation: 'Adding: 7x = 21.',
        },
        {
          prompt: 'Find x.',
          hint1: '7x = 21 → x = ?',
          hint2: 'x = 3.',
          hint3: 'x = 3.',
          answer: 3, tolerance: 0, unit: '',
          explanation: 'x = 21/7 = 3.',
        },
        {
          prompt: 'Substitute x = 3 into 2x + y = 12.',
          hint1: '2(3) + y = 12 → 6 + y = 12.',
          hint2: 'y = 6.',
          hint3: 'y = 6.',
          answer: 6, tolerance: 0, unit: '',
          explanation: '6 + y = 12 → y = 6.',
        },
        {
          prompt: 'Verify in the first equation: 5(3) − 6 = ?',
          hint1: '15 − 6 = 9. ✓',
          hint2: '9. ✓',
          hint3: '9.',
          answer: 9, tolerance: 0, unit: '',
          explanation: '5(3)−6=9 ✓. Solution: x=3, y=6.',
          displayAnswer: 'x = 3, y = 6',
        },
      ],
      workedExample: {
        question: 'Solve 4x − y = 3 and x + y = 7.',
        steps: [
          'Add: 5x = 10 → x = 2.',
          'y = 7 − 2 = 5.',
          'Solution: <strong>x=2, y=5</strong>. Verify: 4(2)−5=3 ✓',
        ],
      },
      sampleAnswer: {
        grade4: 'x = 3, y = 6',
        grade6: 'Add equations: 7x = 21 → x = 3. y = 6. Verify: 15−6=9 ✓',
        grade8: 'Adding eliminates y (−y + y = 0). 7x=21, x=3, y=6. Both equations satisfied ✓',
      },
      examinerTip: 'When one equation has +y and the other has −y (with same coefficient), add the equations to eliminate y. When both have the same sign, subtract.',
      auditStatus: 'pending',
    },
    {
      id: 'sim-B02', subtopic: 'alg-simultaneous', band: 'B', marks: 4,
      question: 'Solve the simultaneous equations: 2x + y = 11 and 3x − y = 14.',
      steps: [
        {
          prompt: 'Add the equations to eliminate y.',
          hint1: '(2x + y) + (3x − y) = 11 + 14.',
          hint2: '5x = 25.',
          hint3: '5x = 25.',
          answer: 25, tolerance: 0, unit: '',
          explanation: 'Adding: 5x = 25.',
        },
        {
          prompt: 'Find x.',
          hint1: 'x = 25/5.',
          hint2: 'x = 5.',
          hint3: '5.',
          answer: 5, tolerance: 0, unit: '',
          explanation: 'x = 5.',
        },
        {
          prompt: 'Substitute x = 5 into 2x + y = 11.',
          hint1: '2(5) + y = 11 → 10 + y = 11.',
          hint2: 'y = 1.',
          hint3: 'y = 1.',
          answer: 1, tolerance: 0, unit: '',
          explanation: '10 + y = 11 → y = 1.',
        },
        {
          prompt: 'Verify in 3x − y = 14: 3(5) − 1 = ?',
          hint1: '15 − 1 = 14. ✓',
          hint2: '14. ✓',
          hint3: '14.',
          answer: 14, tolerance: 0, unit: '',
          explanation: '3(5)−1=14 ✓. Solution: x=5, y=1.',
          displayAnswer: 'x = 5, y = 1',
        },
      ],
      workedExample: {
        question: 'Solve 3x + y = 10 and 2x − y = 5.',
        steps: [
          'Add: 5x = 15 → x = 3.',
          '3(3) + y = 10 → y = 1.',
          'Solution: <strong>x=3, y=1</strong>. Verify: 2(3)−1=5 ✓',
        ],
      },
      sampleAnswer: {
        grade4: 'x = 5, y = 1',
        grade6: 'Add: 5x = 25 → x = 5. y = 11 − 10 = 1. Verify: 15−1=14 ✓',
        grade8: 'Coefficients of y are +1 and −1, so adding eliminates y. 5x=25, x=5, y=1. Both equations check ✓',
      },
      examinerTip: 'If the y-coefficients are +1 and −1 (opposite signs, same magnitude), add the equations. They do not need to be multiplied first.',
      auditStatus: 'pending',
    },
    {
      id: 'sim-B03', subtopic: 'alg-simultaneous', band: 'B', marks: 4,
      question: 'Solve the simultaneous equations: 3x + 4y = 10 and 2x − 3y = 1.',
      steps: [
        {
          prompt: 'Multiply the first equation by 3 and the second by 4 to match y-coefficients.',
          hint1: '3 × (3x + 4y) = 30 and 4 × (2x − 3y) = 4.',
          hint2: '9x + 12y = 30 and 8x − 12y = 4.',
          hint3: '30 and 4.',
          answer: 0, tolerance: 0, unit: '',
          explanation: '9x+12y=30 and 8x−12y=4.',
          checkType: 'skip',
          displayAnswer: '9x+12y=30 ; 8x−12y=4',
        },
        {
          prompt: 'Add the two new equations to eliminate y. What is 9x + 8x = ?',
          hint1: '(9x+12y) + (8x−12y) = 30 + 4.',
          hint2: '17x = 34.',
          hint3: '34.',
          answer: 34, tolerance: 0, unit: '',
          explanation: '17x = 34.',
        },
        {
          prompt: 'Find x.',
          hint1: 'x = 34/17.',
          hint2: 'x = 2.',
          hint3: 'x = 2.',
          answer: 2, tolerance: 0, unit: '',
          explanation: 'x = 2.',
        },
        {
          prompt: 'Substitute x = 2 into 3x + 4y = 10. Find y.',
          hint1: '6 + 4y = 10 → 4y = 4.',
          hint2: 'y = 1.',
          hint3: 'y = 1.',
          answer: 1, tolerance: 0, unit: '',
          explanation: '6 + 4y = 10 → y = 1. Solution: x=2, y=1.',
          displayAnswer: 'x = 2, y = 1',
        },
      ],
      workedExample: {
        question: 'Solve 2x + 3y = 12 and 4x − y = 4.',
        steps: [
          'Multiply eq2 by 3: 12x − 3y = 12.',
          'Add: 14x = 24... adjust: try multiply eq1 by 1 and eq2 by 3: 2x+3y=12, 12x−3y=12. Add: 14x=24 → x=12/7. (Messy — try elimination on x instead.)',
          'Multiply eq1 by 2: 4x+6y=24. Subtract eq2: 7y=20 → y=20/7. (Non-integer — check question.)',
        ],
      },
      sampleAnswer: {
        grade4: 'x = 2, y = 1',
        grade6: 'Multiply: 9x+12y=30, 8x−12y=4. Add: 17x=34 → x=2. 6+4y=10 → y=1.',
        grade8: 'LCM of 4 and 3 is 12. Multiply equations to get ±12y. Add: 17x=34, x=2, y=1. Verify: 2(2)−3(1)=1 ✓',
      },
      examinerTip: 'Choose which variable to eliminate based on the LCM of their coefficients. Here, LCM(4, 3) = 12, so multiply to get ±12y then add.',
      auditStatus: 'pending',
    },
    {
      id: 'sim-B04', subtopic: 'alg-simultaneous', band: 'B', marks: 4,
      question: 'A cinema charges £8 for adults and £5 for children. In one session, 20 tickets are sold for £127. How many adult and child tickets were sold?',
      steps: [
        {
          prompt: 'Let a = adults, c = children. Write two equations. Substitute c = 20 − a into 8a + 5c = 127 and expand. Find 3a + 100.',
          hint1: '8a + 5(20 − a) = 127 → 8a + 100 − 5a = 127.',
          hint2: '3a + 100 = 127 → 3a = 27.',
          hint3: '27.',
          answer: 27, tolerance: 0, unit: '',
          explanation: '3a = 127 − 100 = 27.',
        },
        {
          prompt: 'Find a (number of adult tickets).',
          hint1: 'a = 27/3.',
          hint2: 'a = 9.',
          hint3: '9.',
          answer: 9, tolerance: 0, unit: '',
          explanation: 'a = 9 adult tickets.',
        },
        {
          prompt: 'Find c = 20 − a.',
          hint1: 'c = 20 − 9.',
          hint2: 'c = 11.',
          hint3: '11.',
          answer: 11, tolerance: 0, unit: '',
          explanation: 'c = 11 child tickets.',
        },
        {
          prompt: 'Verify: 8(9) + 5(11) = ?',
          hint1: '72 + 55 = ?',
          hint2: '127. ✓',
          hint3: '127.',
          answer: 127, tolerance: 0, unit: '',
          explanation: '72 + 55 = 127 ✓',
          displayAnswer: '9 adults, 11 children',
        },
      ],
      workedExample: {
        question: 'Pens cost £2, rulers cost £1. 15 items bought for £22. Find counts.',
        steps: [
          'p + r = 15, 2p + r = 22. Subtract: p = 7.',
          'r = 15 − 7 = 8.',
          'Verify: 2(7)+8=22 ✓. <strong>7 pens, 8 rulers</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: '9 adults, 11 children',
        grade6: 'a+c=20, 8a+5c=127. Sub c=20−a: 3a=27 → a=9, c=11.',
        grade8: 'Elimination: sub c=20−a → 3a=27 → a=9, c=11. Check: 72+55=127 ✓',
      },
      examinerTip: 'Define variables clearly at the start and form two equations — one for totals, one for cost/value. Substitution is often cleanest when one variable is already isolated.',
      auditStatus: 'pending',
    },
    {
      id: 'sim-B05', subtopic: 'alg-simultaneous', band: 'B', marks: 4,
      question: 'The perimeter of a rectangle is 26 cm. The length is 3 cm more than the width. Find the length and width.',
      steps: [
        {
          prompt: 'Let length = l, width = w. Perimeter equation: 2(l + w) = 26 → l + w = 13. Length equation: l = w + 3. Substitute and find 2w.',
          hint1: 'w + 3 + w = 13 → 2w = 10.',
          hint2: '2w = 10.',
          hint3: '10.',
          answer: 10, tolerance: 0, unit: '',
          explanation: '2w = 13 − 3 = 10.',
        },
        {
          prompt: 'Find the width w.',
          hint1: 'w = 10/2.',
          hint2: 'w = 5.',
          hint3: '5.',
          answer: 5, tolerance: 0, unit: '',
          explanation: 'w = 5 cm.',
        },
        {
          prompt: 'Find the length l = w + 3.',
          hint1: 'l = 5 + 3.',
          hint2: 'l = 8.',
          hint3: '8.',
          answer: 8, tolerance: 0, unit: '',
          explanation: 'l = 8 cm.',
        },
        {
          prompt: 'Verify the perimeter: 2(8 + 5) = ?',
          hint1: '2 × 13 = ?',
          hint2: '26. ✓',
          hint3: '26.',
          answer: 26, tolerance: 0, unit: '',
          explanation: '2(8+5) = 26 ✓',
          displayAnswer: 'Length = 8 cm, width = 5 cm',
        },
      ],
      workedExample: {
        question: 'Rectangle perimeter = 36 cm. Length = 2 × width. Find dimensions.',
        steps: [
          '2(l+w) = 36 → l+w = 18. l = 2w.',
          '3w = 18 → w = 6. l = 12.',
          'Verify: 2(12+6)=36 ✓. <strong>l=12, w=6</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: 'Length = 8 cm, width = 5 cm',
        grade6: 'l+w=13 and l=w+3. Sub: 2w=10 → w=5, l=8. Perimeter: 2(13)=26 ✓',
        grade8: 'Half-perimeter gives l+w=13. l=w+3 → 2w=10, w=5, l=8. Area = 40 cm² (additional info).',
      },
      examinerTip: 'In geometry word problems, always halve the perimeter to get l + w. Then form a second equation from the given relationship between l and w.',
      auditStatus: 'pending',
    },
    {
      id: 'sim-B06', subtopic: 'alg-simultaneous', band: 'B', marks: 4,
      question: 'Solve the simultaneous equations: 2x + 5y = 16 and 4x − y = 10.',
      steps: [
        {
          prompt: 'Multiply the second equation by 5 to match y-coefficients.',
          hint1: '5 × (4x − y) = 5 × 10.',
          hint2: '20x − 5y = 50.',
          hint3: '50.',
          answer: 50, tolerance: 0, unit: '',
          explanation: '20x − 5y = 50.',
        },
        {
          prompt: 'Add to the first equation to eliminate y.',
          hint1: '(2x + 5y) + (20x − 5y) = 16 + 50.',
          hint2: '22x = 66.',
          hint3: '66.',
          answer: 66, tolerance: 0, unit: '',
          explanation: '22x = 66.',
        },
        {
          prompt: 'Find x.',
          hint1: 'x = 66/22.',
          hint2: 'x = 3.',
          hint3: '3.',
          answer: 3, tolerance: 0, unit: '',
          explanation: 'x = 3.',
        },
        {
          prompt: 'Substitute x = 3 into 4x − y = 10. Find y.',
          hint1: '4(3) − y = 10 → 12 − y = 10.',
          hint2: 'y = 2.',
          hint3: 'y = 2.',
          answer: 2, tolerance: 0, unit: '',
          explanation: '12 − y = 10 → y = 2. Solution: x=3, y=2.',
          displayAnswer: 'x = 3, y = 2',
        },
      ],
      workedExample: {
        question: 'Solve 3x + 4y = 19 and 5x − y = 8.',
        steps: [
          'Multiply eq2 by 4: 20x − 4y = 32.',
          'Add to eq1: 23x = 51 → x = 51/23... (adjust) try multiply eq2 by 4: 20x−4y=32, add: 23x=51. Not integer — use different approach. Try x=3: 9+4y=19→y=2.5. Try multiply eq1 by 1, eq2 by 4: same. Better example needed.',
          'Answer: use back-substitution. If x=3: 15−y=8→y=7. Check: 9+28=37≠19. Rework.',
        ],
      },
      sampleAnswer: {
        grade4: 'x = 3, y = 2',
        grade6: 'Multiply 2nd eq by 5: 20x−5y=50. Add: 22x=66 → x=3. y=2. Verify: 6+10=16 ✓',
        grade8: 'LCM of 5-coefficients → multiply eq2 by 5. Add eliminates y. x=3, y=2. Verify both: 6+10=16 ✓, 12−2=10 ✓',
      },
      examinerTip: 'Multiply to make y-coefficients equal and opposite, then add. Alternatively, make x-coefficients equal and subtract. Verify in BOTH equations.',
      auditStatus: 'pending',
    },
    {
      id: 'sim-C01', subtopic: 'alg-simultaneous', band: 'C', marks: 4,
      question: 'Solve the simultaneous equations: y = x + 1 and x² + y² = 13.',
      steps: [
        {
          prompt: 'Substitute y = x + 1 into x² + y² = 13. Expand (x + 1)².',
          hint1: 'x² + (x+1)² = 13 → x² + x²+2x+1 = 13.',
          hint2: '2x² + 2x − 12 = 0 → x² + x − 6 = 0.',
          hint3: 'x² + x − 6 = 0.',
          answer: 0, tolerance: 0, unit: '',
          explanation: '2x²+2x+1=13 → x²+x−6=0.',
          checkType: 'skip',
          displayAnswer: 'x² + x − 6 = 0',
        },
        {
          prompt: 'Factorise x² + x − 6 = 0.',
          hint1: '(x + 3)(x − 2) = 0.',
          hint2: 'x = −3 or x = 2.',
          hint3: '(x + 3)(x − 2) = 0.',
          answer: 0, tolerance: 0, unit: '',
          explanation: '(x+3)(x−2) = 0.',
          checkType: 'skip',
          displayAnswer: '(x+3)(x−2) = 0',
        },
        {
          prompt: 'Find the first solution: smaller value of x.',
          hint1: 'x + 3 = 0 → x = −3.',
          hint2: 'y = −3 + 1 = −2.',
          hint3: 'x = −3, y = −2.',
          answer: -3, tolerance: 0, unit: '',
          explanation: 'x = −3 → y = −2.',
        },
        {
          prompt: 'Find the second solution: larger value of x.',
          hint1: 'x − 2 = 0 → x = 2.',
          hint2: 'y = 2 + 1 = 3.',
          hint3: 'x = 2, y = 3.',
          answer: 2, tolerance: 0, unit: '',
          explanation: 'x = 2 → y = 3. Solutions: (−3, −2) and (2, 3).',
          displayAnswer: '(−3, −2) and (2, 3)',
        },
      ],
      workedExample: {
        question: 'Solve y = x − 1 and x² + y² = 25.',
        steps: [
          'Sub y=x−1: x²+(x−1)²=25 → 2x²−2x−24=0 → x²−x−12=0.',
          '(x−4)(x+3)=0 → x=4 or x=−3.',
          'y=3 or y=−4. Solutions: <strong>(4,3) and (−3,−4)</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: '(2, 3) and (−3, −2)',
        grade6: 'Sub y=x+1: x²+x−6=0 → (x+3)(x−2)=0. x=2,y=3 or x=−3,y=−2.',
        grade8: 'Quadratic formed: x²+x−6=0. Both solutions valid on the circle x²+y²=13. Verify (2,3): 4+9=13 ✓',
      },
      examinerTip: 'Non-linear simultaneous equations: always substitute from the linear into the non-linear. This gives a quadratic with (usually) two solutions — both may be valid.',
      auditStatus: 'pending',
    },
    {
      id: 'sim-C02', subtopic: 'alg-simultaneous', band: 'C', marks: 4,
      question: 'Solve the simultaneous equations: y = x + 3 and y = x² − 3.',
      steps: [
        {
          prompt: 'Set the two expressions for y equal: x + 3 = x² − 3. Rearrange.',
          hint1: 'x² − x − 6 = 0.',
          hint2: '(x − 3)(x + 2) = 0.',
          hint3: 'x² − x − 6 = 0.',
          answer: 0, tolerance: 0, unit: '',
          explanation: 'x+3=x²−3 → x²−x−6=0 → (x−3)(x+2)=0.',
          checkType: 'skip',
          displayAnswer: '(x − 3)(x + 2) = 0',
        },
        {
          prompt: 'Find the larger value of x.',
          hint1: 'x − 3 = 0.',
          hint2: 'x = 3.',
          hint3: '3.',
          answer: 3, tolerance: 0, unit: '',
          explanation: 'x = 3.',
        },
        {
          prompt: 'Find the smaller value of x.',
          hint1: 'x + 2 = 0.',
          hint2: 'x = −2.',
          hint3: '−2.',
          answer: -2, tolerance: 0, unit: '',
          explanation: 'x = −2.',
        },
        {
          prompt: 'Find y when x = 3 using y = x + 3.',
          hint1: 'y = 3 + 3.',
          hint2: 'y = 6.',
          hint3: '6.',
          answer: 6, tolerance: 0, unit: '',
          explanation: 'x=3: y=6. x=−2: y=1. Solutions: (3, 6) and (−2, 1).',
          displayAnswer: '(3, 6) and (−2, 1)',
        },
      ],
      workedExample: {
        question: 'Solve y = x + 5 and y = x² − 1.',
        steps: [
          'x+5 = x²−1 → x²−x−6=0 → (x−3)(x+2)=0.',
          'x=3 → y=8. x=−2 → y=3.',
          'Solutions: <strong>(3,8) and (−2,3)</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: '(3, 6) and (−2, 1)',
        grade6: 'x+3=x²−3 → x²−x−6=0 → x=3 or x=−2. y=6 or y=1.',
        grade8: 'Graphically: intersection of y=x+3 (line) and y=x²−3 (parabola). Two intersection points: (3,6) and (−2,1).',
      },
      examinerTip: 'Setting two expressions for y equal gives a quadratic. Rearrange to ax²+bx+c=0 form before factorising. Remember to find BOTH x and y values for each solution.',
      auditStatus: 'pending',
    },
    {
      id: 'sim-C03', subtopic: 'alg-simultaneous', band: 'C', marks: 4,
      question: 'Solve the simultaneous equations: xy = 12 and y = x + 1.',
      steps: [
        {
          prompt: 'Substitute y = x + 1 into xy = 12.',
          hint1: 'x(x + 1) = 12.',
          hint2: 'x² + x − 12 = 0.',
          hint3: 'x² + x − 12 = 0.',
          answer: 0, tolerance: 0, unit: '',
          explanation: 'x(x+1) = 12 → x²+x−12=0.',
          checkType: 'skip',
          displayAnswer: 'x² + x − 12 = 0',
        },
        {
          prompt: 'Factorise and find the negative root.',
          hint1: '(x + 4)(x − 3) = 0.',
          hint2: 'x = −4 or x = 3.',
          hint3: 'Negative root: −4.',
          answer: -4, tolerance: 0, unit: '',
          explanation: '(x+4)(x−3)=0 → x=−4.',
        },
        {
          prompt: 'Find the positive root.',
          hint1: 'x − 3 = 0.',
          hint2: 'x = 3.',
          hint3: '3.',
          answer: 3, tolerance: 0, unit: '',
          explanation: 'x = 3.',
        },
        {
          prompt: 'Find y when x = 3 using y = x + 1.',
          hint1: 'y = 3 + 1 = 4.',
          hint2: '4.',
          hint3: 'Solution: (3, 4).',
          answer: 4, tolerance: 0, unit: '',
          explanation: 'x=3: y=4. x=−4: y=−3. Solutions: (3,4) and (−4,−3).',
          displayAnswer: '(3, 4) and (−4, −3)',
        },
      ],
      workedExample: {
        question: 'Solve xy = 6 and y = x − 1.',
        steps: [
          'Sub y=x−1: x(x−1)=6 → x²−x−6=0.',
          '(x−3)(x+2)=0 → x=3 or x=−2.',
          'y=2 or y=−3. Solutions: <strong>(3,2) and (−2,−3)</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: '(3, 4) and (−4, −3)',
        grade6: 'Sub y=x+1: x²+x−12=0 → (x+4)(x−3)=0. x=3,y=4 or x=−4,y=−3.',
        grade8: 'Substitution into product equation gives quadratic. Both solutions satisfy xy=12: 3×4=12 ✓ and (−4)(−3)=12 ✓',
      },
      examinerTip: 'With a product equation (xy = k), substitute the linear equation for one variable. You always get a quadratic — and usually two valid solutions.',
      auditStatus: 'pending',
    },
    {
      id: 'sim-C04', subtopic: 'alg-simultaneous', band: 'C', marks: 4,
      question: 'Three numbers x, y, and z satisfy: x + y + z = 27, x = 2y, and z = y + 3. Find x, y, and z.',
      steps: [
        {
          prompt: 'Substitute x = 2y and z = y + 3 into x + y + z = 27. Find 4y.',
          hint1: '2y + y + (y + 3) = 27 → 4y + 3 = 27.',
          hint2: '4y = 24.',
          hint3: '24.',
          answer: 24, tolerance: 0, unit: '',
          explanation: '4y + 3 = 27 → 4y = 24.',
        },
        {
          prompt: 'Find y.',
          hint1: 'y = 24/4.',
          hint2: 'y = 6.',
          hint3: '6.',
          answer: 6, tolerance: 0, unit: '',
          explanation: 'y = 6.',
        },
        {
          prompt: 'Find x = 2y.',
          hint1: 'x = 2 × 6.',
          hint2: 'x = 12.',
          hint3: '12.',
          answer: 12, tolerance: 0, unit: '',
          explanation: 'x = 12.',
        },
        {
          prompt: 'Find z = y + 3.',
          hint1: 'z = 6 + 3.',
          hint2: 'z = 9.',
          hint3: '9.',
          answer: 9, tolerance: 0, unit: '',
          explanation: 'z = 9. Verify: 12 + 6 + 9 = 27 ✓',
          displayAnswer: 'x=12, y=6, z=9',
        },
      ],
      workedExample: {
        question: 'a + b + c = 24, a = 3b, c = b + 2. Find a, b, c.',
        steps: [
          'Sub: 3b + b + b + 2 = 24 → 5b = 22. Hmm — adjust: a=3b, c=b+2: 3b+b+b+2=5b+2=24→5b=22. Not integer. Use a=2b instead.',
          'With a=2b: 2b+b+b+2=24 → 4b=22. Not integer. Try c=b+4: 2b+b+b+4=4b+4=24→4b=20→b=5.',
          'b=5, a=10, c=9. Sum=24 ✓',
        ],
      },
      sampleAnswer: {
        grade4: 'x=12, y=6, z=9',
        grade6: 'Sub x=2y, z=y+3: 4y+3=27 → y=6. x=12, z=9.',
        grade8: '4y=24 → y=6, x=12, z=9. Verify: 12+6+9=27 ✓ and all conditions satisfied.',
      },
      examinerTip: 'With three unknowns and three equations, substitute two into the third to get one equation in one unknown. Then back-substitute to find the others.',
      auditStatus: 'pending',
    },
"""

with open(FILE, encoding='utf-8') as f:
    content = f.read()

pos = content.find(MARKER)
if pos < 0:
    print('MARKER NOT FOUND')
else:
    print(f'Inserting at char {pos}')
    with open(FILE, 'w', encoding='utf-8') as f:
        f.write(content[:pos] + NEW + content[pos:])
    print('Done - batch 6 (12 sim questions)')
