FILE = r'C:\Users\jason\OneDrive\Documents\GitHub\mabel-gcse\js\maths-questions.js'
MARKER = "    {\n      id: 'pro-A01'"

NEW = """    {
      id: 'ineq-A03', subtopic: 'alg-inequalities', band: 'A', marks: 2,
      question: 'Solve the inequality 4x − 3 ≥ 9.',
      steps: [
        {
          prompt: 'Add 3 to both sides.',
          hint1: '4x − 3 + 3 ≥ 9 + 3.',
          hint2: '4x ≥ 12.',
          hint3: '12.',
          answer: 12, tolerance: 0, unit: '',
          explanation: '4x ≥ 12.',
        },
        {
          prompt: 'Divide both sides by 4.',
          hint1: '4x/4 ≥ 12/4.',
          hint2: 'x ≥ 3.',
          hint3: 'x ≥ 3.',
          answer: 3, tolerance: 0, unit: '',
          explanation: 'x ≥ 3.',
          displayAnswer: 'x ≥ 3',
        },
      ],
      workedExample: {
        question: 'Solve 5x + 2 > 17.',
        steps: [
          '5x + 2 − 2 > 17 − 2 → 5x > 15.',
          '5x/5 > 15/5.',
          'x > <strong>3</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: 'x ≥ 3',
        grade6: '4x − 3 ≥ 9 → 4x ≥ 12 → x ≥ 3.',
        grade8: '4x ≥ 9 + 3 = 12 → x ≥ 3. The inequality sign stays the same when dividing by a positive number.',
      },
      examinerTip: 'Solve inequalities the same way as equations — but when dividing or multiplying by a negative number, flip the inequality sign.',
      auditStatus: 'pending',
    },
    {
      id: 'ineq-A04', subtopic: 'alg-inequalities', band: 'A', marks: 2,
      question: 'Solve the inequality 4x + 2 < 10.',
      steps: [
        {
          prompt: 'Subtract 2 from both sides. What does 4x become less than?',
          hint1: '4x + 2 − 2 < 10 − 2.',
          hint2: '4x < 8.',
          hint3: '8.',
          answer: 8, tolerance: 0, unit: '',
          explanation: '4x < 8.',
        },
        {
          prompt: 'Divide both sides by 4.',
          hint1: '4x/4 < 8/4.',
          hint2: 'x < 2.',
          hint3: 'x < 2.',
          answer: 2, tolerance: 0, unit: '',
          explanation: 'x < 2.',
          displayAnswer: 'x < 2',
        },
      ],
      workedExample: {
        question: 'Solve 3x + 5 < 14.',
        steps: [
          '3x < 14 − 5 = 9.',
          'x < 9/3.',
          'x < <strong>3</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: 'x < 2',
        grade6: '4x + 2 < 10 → 4x < 8 → x < 2.',
        grade8: 'Subtract 2: 4x < 8. Divide by 4: x < 2. Inequality direction unchanged (dividing by positive 4).',
      },
      examinerTip: 'Work step by step: isolate the term with x first, then divide. Keep the inequality sign pointing the same way when dividing by a positive number.',
      auditStatus: 'pending',
    },
    {
      id: 'ineq-A05', subtopic: 'alg-inequalities', band: 'A', marks: 3,
      question: 'Solve the inequality 5 ≤ 2x + 1 < 11.',
      steps: [
        {
          prompt: 'Subtract 1 from all three parts.',
          hint1: '5 − 1 ≤ 2x + 1 − 1 < 11 − 1.',
          hint2: '4 ≤ 2x < 10.',
          hint3: '4 ≤ 2x < 10.',
          answer: 0, tolerance: 0, unit: '',
          explanation: '4 ≤ 2x < 10.',
          checkType: 'skip',
          displayAnswer: '4 ≤ 2x < 10',
        },
        {
          prompt: 'Divide all three parts by 2. What is the left bound of x?',
          hint1: '4/2 ≤ x.',
          hint2: 'x ≥ 2.',
          hint3: 'Left bound: 2.',
          answer: 2, tolerance: 0, unit: '',
          explanation: '2 ≤ x.',
        },
        {
          prompt: 'What is the right bound of x?',
          hint1: '2x < 10 → x < ?',
          hint2: 'x < 5.',
          hint3: 'Right bound: 5.',
          answer: 5, tolerance: 0, unit: '',
          explanation: 'x < 5. Solution: 2 ≤ x < 5.',
          displayAnswer: '2 ≤ x < 5',
        },
      ],
      workedExample: {
        question: 'Solve −1 < 3x + 2 ≤ 11.',
        steps: [
          'Subtract 2: −3 < 3x ≤ 9.',
          'Divide by 3: −1 < x ≤ 3.',
          'Solution: <strong>−1 < x ≤ 3</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: '2 ≤ x < 5',
        grade6: 'Subtract 1: 4 ≤ 2x < 10. Divide by 2: 2 ≤ x < 5.',
        grade8: '5 ≤ 2x+1 < 11. Subtract 1: 4 ≤ 2x < 10. Divide by 2: 2 ≤ x < 5. Note: left is closed (≤), right is open (<).',
      },
      examinerTip: 'Treat the double inequality as one operation applied to all three parts simultaneously. Do NOT separate into two inequalities unless you prefer to — both methods are acceptable.',
      auditStatus: 'pending',
    },
    {
      id: 'ineq-B02', subtopic: 'alg-inequalities', band: 'B', marks: 3,
      question: 'Solve the inequality 3(x + 2) > 2(x + 5).',
      steps: [
        {
          prompt: 'Expand the left bracket. What is 3 × 2?',
          hint1: '3(x + 2) = 3x + ?',
          hint2: '3 × 2 = 6.',
          hint3: '3x + 6.',
          answer: 6, tolerance: 0, unit: '',
          explanation: '3(x + 2) = 3x + 6.',
        },
        {
          prompt: 'Expand the right bracket. What is 2 × 5?',
          hint1: '2(x + 5) = 2x + ?',
          hint2: '2 × 5 = 10.',
          hint3: '2x + 10.',
          answer: 10, tolerance: 0, unit: '',
          explanation: '2(x + 5) = 2x + 10. Now: 3x + 6 > 2x + 10.',
        },
        {
          prompt: 'Subtract 2x and 6 from both sides to find x.',
          hint1: '3x − 2x > 10 − 6.',
          hint2: 'x > 4.',
          hint3: 'x > 4.',
          answer: 4, tolerance: 0, unit: '',
          explanation: 'x > 10 − 6 = 4.',
          displayAnswer: 'x > 4',
        },
      ],
      workedExample: {
        question: 'Solve 4(x + 1) > 3(x + 4).',
        steps: [
          'Expand: 4x + 4 > 3x + 12.',
          'Collect x: x > 12 − 4 = 8.',
          'Solution: <strong>x > 8</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: 'x > 4',
        grade6: 'Expand: 3x + 6 > 2x + 10. Subtract 2x and 6: x > 4.',
        grade8: '3x+6>2x+10 → x>4. Note: dividing by a positive number, inequality direction unchanged.',
      },
      examinerTip: 'Expand brackets first, then collect like terms. Avoid trying to move brackets across an inequality without expanding — you will make errors.',
      auditStatus: 'pending',
    },
    {
      id: 'ineq-B03', subtopic: 'alg-inequalities', band: 'B', marks: 3,
      question: 'Solve −2 < 3n − 1 ≤ 8. List the integer values of n that satisfy the inequality.',
      steps: [
        {
          prompt: 'Add 1 to all three parts.',
          hint1: '−2 + 1 < 3n ≤ 8 + 1.',
          hint2: '−1 < 3n ≤ 9.',
          hint3: '−1 < 3n ≤ 9.',
          answer: 0, tolerance: 0, unit: '',
          explanation: 'Add 1: −1 < 3n ≤ 9.',
          checkType: 'skip',
          displayAnswer: '−1 < 3n ≤ 9',
        },
        {
          prompt: 'Divide by 3. What is the lower bound of n (strictly greater than)?',
          hint1: '−1/3 < n.',
          hint2: 'n > −1/3 ≈ −0.33.',
          hint3: 'Lower bound: −1/3.',
          answer: 0, tolerance: 0, unit: '',
          explanation: 'n > −1/3. Since n must be an integer, smallest n = 0.',
          checkType: 'skip',
          displayAnswer: 'n > −1/3',
        },
        {
          prompt: 'Upper bound: 3n ≤ 9 → n ≤ ? And how many integers satisfy this?',
          hint1: '3n ≤ 9 → n ≤ 3.',
          hint2: 'Integers: 0, 1, 2, 3. Count = 4.',
          hint3: '4 integers.',
          answer: 4, tolerance: 0, unit: '',
          explanation: 'n ≤ 3. Integers in range: 0, 1, 2, 3. Count = 4.',
          displayAnswer: 'n ∈ {0, 1, 2, 3}',
        },
      ],
      workedExample: {
        question: 'Solve 1 ≤ 2m + 3 < 13. List integer values of m.',
        steps: [
          'Subtract 3: −2 ≤ 2m < 10.',
          'Divide by 2: −1 ≤ m < 5.',
          'Integers: −1, 0, 1, 2, 3, 4 — that is <strong>6 integers</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: 'n = 0, 1, 2, 3',
        grade6: 'Add 1: −1 < 3n ≤ 9. Divide by 3: −⅓ < n ≤ 3. Integer values: 0, 1, 2, 3.',
        grade8: '−1 < 3n ≤ 9 → −1/3 < n ≤ 3. Integer values: 0, 1, 2, 3 (four values). Note −1/3 ≈ −0.33 so n = 0 is the smallest integer satisfying n > −1/3.',
      },
      examinerTip: 'After solving, list integers systematically from smallest to largest. Do not include boundary values excluded by strict inequality (<).',
      auditStatus: 'pending',
    },
    {
      id: 'ineq-B04', subtopic: 'alg-inequalities', band: 'B', marks: 3,
      question: 'Solve both inequalities and state the combined solution: 4 − 3x ≤ 13, and x ≥ −2.',
      steps: [
        {
          prompt: 'Solve 4 − 3x ≤ 13. Subtract 4 from both sides.',
          hint1: '−3x ≤ 13 − 4.',
          hint2: '−3x ≤ 9.',
          hint3: '−3x ≤ 9.',
          answer: 9, tolerance: 0, unit: '',
          explanation: '−3x ≤ 9.',
        },
        {
          prompt: 'Divide both sides by −3 (flip the inequality). What value must x be at least?',
          hint1: 'Dividing by negative → flip sign: x ≥ −3.',
          hint2: 'x ≥ −3.',
          hint3: 'x ≥ −3.',
          answer: -3, tolerance: 0, unit: '',
          explanation: 'Dividing by −3 (negative) → flip inequality: x ≥ −3.',
        },
        {
          prompt: 'Combine x ≥ −3 with x ≥ −2. Which gives the more restrictive lower bound?',
          hint1: 'Both say x ≥ something. Take the larger lower bound.',
          hint2: 'x ≥ −2 is more restrictive than x ≥ −3.',
          hint3: 'Combined solution: x ≥ −2.',
          answer: -2, tolerance: 0, unit: '',
          explanation: 'The combined solution is x ≥ −2 (more restrictive).',
          displayAnswer: 'x ≥ −2',
        },
      ],
      workedExample: {
        question: 'Solve 6 − 2x < 12 and x ≤ 8. State combined solution.',
        steps: [
          '−2x < 6 → x > −3 (flip sign ÷ negative).',
          'Combined with x ≤ 8: −3 < x ≤ 8.',
          'Solution: <strong>−3 < x ≤ 8</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: 'x ≥ −2',
        grade6: '−3x ≤ 9 → x ≥ −3 (flip). Combined with x ≥ −2: answer is x ≥ −2.',
        grade8: '4−3x ≤ 13 → −3x ≤ 9 → x ≥ −3. With x ≥ −2: the binding constraint is x ≥ −2 (more restrictive). Solution: x ≥ −2.',
      },
      examinerTip: 'Flipping the inequality when dividing by a negative is one of the most common errors. To avoid it, move the variable term to the other side before dividing.',
      auditStatus: 'pending',
    },
    {
      id: 'ineq-B05', subtopic: 'alg-inequalities', band: 'B', marks: 4,
      question: 'State the integer values satisfying x ≥ −1 and x < 3, then find the number of integer solutions.',
      steps: [
        {
          prompt: 'The lower bound is x ≥ −1. What is the smallest integer satisfying this?',
          hint1: 'x ≥ −1 includes x = −1.',
          hint2: 'Smallest integer = −1.',
          hint3: '−1.',
          answer: -1, tolerance: 0, unit: '',
          explanation: 'Smallest integer in range is −1.',
        },
        {
          prompt: 'The upper bound is x < 3. What is the largest integer satisfying this?',
          hint1: 'x < 3 does NOT include x = 3.',
          hint2: 'Largest integer satisfying x < 3 is x = 2.',
          hint3: '2.',
          answer: 2, tolerance: 0, unit: '',
          explanation: 'Largest integer in range is 2 (not 3, since x < 3 is strict).',
        },
        {
          prompt: 'List the integer solutions from −1 to 2.',
          hint1: '−1, 0, 1, 2.',
          hint2: 'Four integers.',
          hint3: '4.',
          answer: 0, tolerance: 0, unit: '',
          explanation: 'Integers: −1, 0, 1, 2.',
          checkType: 'skip',
          displayAnswer: '{−1, 0, 1, 2}',
        },
        {
          prompt: 'How many integer solutions are there?',
          hint1: 'Count −1, 0, 1, 2.',
          hint2: '4.',
          hint3: '4.',
          answer: 4, tolerance: 0, unit: '',
          explanation: 'There are 4 integer solutions.',
        },
      ],
      workedExample: {
        question: 'List integers satisfying −2 < x ≤ 4.',
        steps: [
          'Lower bound: −2 < x, so smallest integer is −1.',
          'Upper bound: x ≤ 4, so largest integer is 4.',
          'Integers: −1, 0, 1, 2, 3, 4 — <strong>6 integers</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: '−1, 0, 1, 2 (4 integers)',
        grade6: 'Range: −1 ≤ x < 3. Integers: −1, 0, 1, 2. Count = 4.',
        grade8: 'x ≥ −1 → smallest integer is −1. x < 3 (strict) → largest integer is 2. Integers: −1, 0, 1, 2. Total: 4.',
      },
      examinerTip: 'With strict inequality (<), the boundary value is NOT included. With ≤, it is. Always check whether the endpoints are included before listing integers.',
      auditStatus: 'pending',
    },
    {
      id: 'ineq-B06', subtopic: 'alg-inequalities', band: 'B', marks: 4,
      question: 'Find all integer values satisfying both 4x − 1 > 2x + 7 and 3x ≤ 21.',
      steps: [
        {
          prompt: 'Solve 4x − 1 > 2x + 7. Collect x terms.',
          hint1: '4x − 2x > 7 + 1.',
          hint2: '2x > 8.',
          hint3: 'x > 4.',
          answer: 4, tolerance: 0, unit: '',
          explanation: '2x > 8 → x > 4.',
        },
        {
          prompt: 'Solve 3x ≤ 21.',
          hint1: '3x/3 ≤ 21/3.',
          hint2: 'x ≤ 7.',
          hint3: 'x ≤ 7.',
          answer: 7, tolerance: 0, unit: '',
          explanation: 'x ≤ 7.',
        },
        {
          prompt: 'Combine the two results: 4 < x ≤ 7. List the integers in this range.',
          hint1: 'Integers strictly greater than 4 and at most 7.',
          hint2: '5, 6, 7.',
          hint3: '5, 6, 7.',
          answer: 0, tolerance: 0, unit: '',
          explanation: 'Integer values: 5, 6, 7.',
          checkType: 'skip',
          displayAnswer: '{5, 6, 7}',
        },
        {
          prompt: 'How many integers satisfy both inequalities?',
          hint1: 'Count 5, 6, 7.',
          hint2: '3.',
          hint3: '3.',
          answer: 3, tolerance: 0, unit: '',
          explanation: '3 integers satisfy both inequalities.',
        },
      ],
      workedExample: {
        question: 'Find integers satisfying 3x − 1 > x + 3 and 2x ≤ 14.',
        steps: [
          '3x−1>x+3 → 2x>4 → x>2.',
          '2x≤14 → x≤7.',
          'Combined: 2 < x ≤ 7. Integers: 3, 4, 5, 6, 7 — <strong>5 integers</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: '5, 6, 7',
        grade6: 'x>4 and x≤7. Combined: 4<x≤7. Integers: 5, 6, 7.',
        grade8: 'Inequality 1: 2x>8 → x>4. Inequality 2: x≤7. Combined: 4<x≤7. Integer solutions: 5, 6, 7 (3 solutions).',
      },
      examinerTip: 'Solve each inequality separately, then find the overlap. Draw a number line if it helps — mark both conditions and shade the intersection.',
      auditStatus: 'pending',
    },
    {
      id: 'ineq-C01', subtopic: 'alg-inequalities', band: 'C', marks: 4,
      question: 'Solve the inequality x² ≤ 4x. Find the range of x.',
      steps: [
        {
          prompt: 'Rearrange: subtract 4x from both sides.',
          hint1: 'x² − 4x ≤ 0.',
          hint2: 'Factor the left side.',
          hint3: 'x(x − 4) ≤ 0.',
          answer: 0, tolerance: 0, unit: '',
          explanation: 'x² − 4x ≤ 0 → x(x − 4) ≤ 0.',
          checkType: 'skip',
          displayAnswer: 'x(x − 4) ≤ 0',
        },
        {
          prompt: 'Find the critical values where x(x − 4) = 0.',
          hint1: 'x = 0 or x − 4 = 0.',
          hint2: 'Critical values: 0 and 4.',
          hint3: 'x = 0 or x = 4.',
          answer: 0, tolerance: 0, unit: '',
          explanation: 'Critical values: x = 0 and x = 4.',
          checkType: 'skip',
          displayAnswer: 'Critical values: 0 and 4',
        },
        {
          prompt: 'The expression x(x − 4) ≤ 0 is satisfied between the roots. What is the lower bound of x?',
          hint1: 'The parabola y = x(x−4) dips below zero between x = 0 and x = 4.',
          hint2: 'Lower bound: x ≥ 0.',
          hint3: '0.',
          answer: 0, tolerance: 0, unit: '',
          explanation: 'Lower bound: x ≥ 0.',
        },
        {
          prompt: 'What is the upper bound of x?',
          hint1: 'Upper bound: x ≤ 4.',
          hint2: 'Solution: 0 ≤ x ≤ 4.',
          hint3: '4.',
          answer: 4, tolerance: 0, unit: '',
          explanation: 'Upper bound: x ≤ 4. Solution: 0 ≤ x ≤ 4.',
          displayAnswer: '0 ≤ x ≤ 4',
        },
      ],
      workedExample: {
        question: 'Solve x² ≤ 9x.',
        steps: [
          'x² − 9x ≤ 0 → x(x − 9) ≤ 0.',
          'Critical values: x = 0 and x = 9.',
          'Parabola is negative between roots: <strong>0 ≤ x ≤ 9</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: '0 ≤ x ≤ 4',
        grade6: 'x²−4x≤0 → x(x−4)≤0. Roots: 0 and 4. Quadratic ≤ 0 between roots: 0 ≤ x ≤ 4.',
        grade8: 'x(x−4)≤0. Parabola opens upward; below x-axis between roots. Solution: 0 ≤ x ≤ 4.',
      },
      examinerTip: 'For quadratic inequalities: find the roots, sketch the parabola, then determine where it is positive or negative. ax²+bx+c < 0 is satisfied BETWEEN the roots when a > 0.',
      auditStatus: 'pending',
    },
    {
      id: 'ineq-C02', subtopic: 'alg-inequalities', band: 'C', marks: 4,
      question: 'Solve the inequality x² + 2x − 8 < 0.',
      steps: [
        {
          prompt: 'Factorise x² + 2x − 8.',
          hint1: 'Find two numbers that multiply to −8 and add to 2.',
          hint2: '4 × (−2) = −8 and 4 + (−2) = 2.',
          hint3: '(x + 4)(x − 2) < 0.',
          answer: 0, tolerance: 0, unit: '',
          explanation: '(x + 4)(x − 2) < 0.',
          checkType: 'skip',
          displayAnswer: '(x + 4)(x − 2) < 0',
        },
        {
          prompt: 'Find the roots: what is the smaller root?',
          hint1: 'x + 4 = 0 → x = −4.',
          hint2: 'Smaller root = −4.',
          hint3: '−4.',
          answer: -4, tolerance: 0, unit: '',
          explanation: 'x = −4 (from x + 4 = 0).',
        },
        {
          prompt: 'What is the larger root?',
          hint1: 'x − 2 = 0 → x = 2.',
          hint2: 'Larger root = 2.',
          hint3: '2.',
          answer: 2, tolerance: 0, unit: '',
          explanation: 'x = 2 (from x − 2 = 0).',
        },
        {
          prompt: 'For (x+4)(x−2) < 0 (parabola opening upward), the solution is between the roots. Write the solution.',
          hint1: 'Quadratic < 0 is satisfied between the roots.',
          hint2: '−4 < x < 2.',
          hint3: '−4 < x < 2.',
          answer: 0, tolerance: 0, unit: '',
          explanation: 'Solution: −4 < x < 2.',
          checkType: 'skip',
          displayAnswer: '−4 < x < 2',
        },
      ],
      workedExample: {
        question: 'Solve x² − x − 6 < 0.',
        steps: [
          '(x − 3)(x + 2) < 0. Roots: x = 3 and x = −2.',
          'Parabola opens upward; below zero between roots.',
          'Solution: <strong>−2 < x < 3</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: '−4 < x < 2',
        grade6: '(x+4)(x−2)<0. Roots −4 and 2. Parabola negative between roots: −4<x<2.',
        grade8: '(x+4)(x−2)<0. Leading coefficient positive → parabola opens up → negative between roots. Solution: −4<x<2.',
      },
      examinerTip: 'After finding the roots, always state which way the parabola opens (positive leading coefficient = opens up = negative between roots).',
      auditStatus: 'pending',
    },
    {
      id: 'ineq-C03', subtopic: 'alg-inequalities', band: 'C', marks: 4,
      question: 'Solve the inequality 2x² − 5x − 3 ≤ 0.',
      steps: [
        {
          prompt: 'Factorise 2x² − 5x − 3.',
          hint1: 'Look for factors: (2x + 1)(x − 3).',
          hint2: 'Check: 2x² − 6x + x − 3 = 2x² − 5x − 3. ✓',
          hint3: '(2x + 1)(x − 3) ≤ 0.',
          answer: 0, tolerance: 0, unit: '',
          explanation: '2x² − 5x − 3 = (2x + 1)(x − 3).',
          checkType: 'skip',
          displayAnswer: '(2x + 1)(x − 3) ≤ 0',
        },
        {
          prompt: 'Find the smaller root: 2x + 1 = 0 → x = ?',
          hint1: '2x = −1.',
          hint2: 'x = −1/2 = −0.5.',
          hint3: '−0.5.',
          answer: -0.5, tolerance: 0.01, unit: '',
          explanation: 'x = −1/2 = −0.5.',
        },
        {
          prompt: 'Find the larger root: x − 3 = 0 → x = ?',
          hint1: 'x = 3.',
          hint2: '3.',
          hint3: '3.',
          answer: 3, tolerance: 0, unit: '',
          explanation: 'x = 3.',
        },
        {
          prompt: 'Write the solution: the quadratic is ≤ 0 between and including the roots.',
          hint1: '−0.5 ≤ x ≤ 3.',
          hint2: 'Include endpoints since inequality is ≤.',
          hint3: '−½ ≤ x ≤ 3.',
          answer: 0, tolerance: 0, unit: '',
          explanation: 'Solution: −½ ≤ x ≤ 3.',
          checkType: 'skip',
          displayAnswer: '−½ ≤ x ≤ 3',
        },
      ],
      workedExample: {
        question: 'Solve 3x² − 10x − 8 ≤ 0.',
        steps: [
          '(3x + 2)(x − 4) ≤ 0. Roots: x = −2/3 and x = 4.',
          'Parabola opens upward; ≤ 0 between roots.',
          'Solution: <strong>−2/3 ≤ x ≤ 4</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: '−½ ≤ x ≤ 3',
        grade6: '(2x+1)(x−3)≤0. Roots: −0.5 and 3. Solution: −½ ≤ x ≤ 3.',
        grade8: '(2x+1)(x−3)≤0. Roots x=−½, x=3. Parabola positive outside roots, negative/zero between. Solution: −½ ≤ x ≤ 3 (inclusive since ≤).',
      },
      examinerTip: 'For ≤ (not strict), the endpoints ARE included in the solution. Use ≤ x ≤ in your answer. For strictly < 0, use open inequalities.',
      auditStatus: 'pending',
    },
    {
      id: 'ineq-C04', subtopic: 'alg-inequalities', band: 'C', marks: 4,
      question: 'Find the integer values satisfying both x² < 25 and 2x + 3 > 5.',
      steps: [
        {
          prompt: 'Solve x² < 25. This gives −5 < x < 5. What is the lower bound?',
          hint1: 'x² < 25 means x is between −5 and 5.',
          hint2: 'Lower bound: x > −5.',
          hint3: '−5.',
          answer: -5, tolerance: 0, unit: '',
          explanation: 'x² < 25 → −5 < x < 5.',
        },
        {
          prompt: 'Solve 2x + 3 > 5.',
          hint1: '2x > 2.',
          hint2: 'x > 1.',
          hint3: 'x > 1.',
          answer: 1, tolerance: 0, unit: '',
          explanation: '2x > 2 → x > 1.',
        },
        {
          prompt: 'Combine the conditions: x > 1 and x < 5. What is the combined range?',
          hint1: 'Both conditions must be satisfied.',
          hint2: '1 < x < 5.',
          hint3: 'Combined: 1 < x < 5.',
          answer: 0, tolerance: 0, unit: '',
          explanation: 'Combined: 1 < x < 5.',
          checkType: 'skip',
          displayAnswer: '1 < x < 5',
        },
        {
          prompt: 'List the integers satisfying 1 < x < 5 and state how many there are.',
          hint1: 'Integers greater than 1 and less than 5.',
          hint2: '2, 3, 4.',
          hint3: '3 integers.',
          answer: 3, tolerance: 0, unit: '',
          explanation: 'Integer solutions: 2, 3, 4 — three integers.',
          displayAnswer: '{2, 3, 4}',
        },
      ],
      workedExample: {
        question: 'Find integers satisfying x² < 16 and x > −1.',
        steps: [
          'x² < 16 → −4 < x < 4.',
          'x > −1. Combined: −1 < x < 4.',
          'Integers: 0, 1, 2, 3 — <strong>4 integers</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: '2, 3, 4',
        grade6: 'x²<25 → −5<x<5. 2x+3>5 → x>1. Combined: 1<x<5. Integers: 2, 3, 4.',
        grade8: 'x²<25 → −5<x<5. 2x>2 → x>1. Intersection: 1<x<5. Integer solutions: {2, 3, 4}, count = 3.',
      },
      examinerTip: 'Solve each inequality separately, then find the intersection of the solution sets. Sketch a number line to visualise both conditions simultaneously.',
      auditStatus: 'pending',
    },
"""

with open(FILE, encoding='utf-8') as f:
    content = f.read()

pos = content.find(MARKER)
if pos < 0:
    print('MARKER NOT FOUND')
else:
    print(f'Inserting at char {pos}')
    with open(FILE, 'w', encoding='utf-8') as f:
        f.write(content[:pos] + NEW + content[pos:])
    print('Done - batch 4 (12 ineq questions)')
