FILE = r'C:\Users\jason\OneDrive\Documents\GitHub\mabel-gcse\js\maths-questions.js'
MARKER = "    {\n      id: 'pro-A01'"

NEW = """    {
      id: 'seq-A03', subtopic: 'alg-sequences', band: 'A', marks: 2,
      question: 'The nth term of a sequence is 2n + 5. Find the 10th term.',
      steps: [
        {
          prompt: 'Substitute n = 10: calculate 2 × 10.',
          hint1: '2 × 10 = ?',
          hint2: '2 × 10 = 20.',
          hint3: '20.',
          answer: 20, tolerance: 0, unit: '',
          explanation: '2 × 10 = 20.',
        },
        {
          prompt: 'Add 5: what is 20 + 5?',
          hint1: '20 + 5 = ?',
          hint2: '25.',
          hint3: 'The 10th term is 25.',
          answer: 25, tolerance: 0, unit: '',
          explanation: '2(10) + 5 = 25. The 10th term is 25.',
        },
      ],
      workedExample: {
        question: 'nth term = 3n − 4. Find the 8th term.',
        steps: [
          'Substitute n = 8: 3 × 8 = 24.',
          '24 − 4 = <strong>20</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: '25',
        grade6: 'n = 10: 2(10) + 5 = 20 + 5 = 25.',
        grade8: 'Substituting n = 10 into 2n + 5: 2(10) + 5 = 25. The 10th term is 25.',
      },
      examinerTip: 'Substitution into nth term is straightforward — write out each step to avoid arithmetic errors. Show 2 × 10 = 20, then 20 + 5 = 25.',
      auditStatus: 'pending',
    },
    {
      id: 'seq-A04', subtopic: 'alg-sequences', band: 'A', marks: 2,
      question: 'Find the nth term of the arithmetic sequence 2, 6, 10, 14, ...',
      steps: [
        {
          prompt: 'Find the common difference d.',
          hint1: '6 − 2 = ?',
          hint2: 'd = 4.',
          hint3: 'd = 4.',
          answer: 4, tolerance: 0, unit: '',
          explanation: 'd = 6 − 2 = 4.',
        },
        {
          prompt: 'nth term = 4n + c. Use the first term (n = 1) to find c.',
          hint1: 'When n = 1, term = 2: 4(1) + c = 2.',
          hint2: 'c = 2 − 4 = −2.',
          hint3: 'c = −2.',
          answer: -2, tolerance: 0, unit: '',
          explanation: '4(1) + c = 2 → c = −2. nth term = 4n − 2.',
          displayAnswer: 'nth term = 4n − 2',
        },
      ],
      workedExample: {
        question: 'Find the nth term of 5, 9, 13, 17, ...',
        steps: [
          'd = 9 − 5 = 4.',
          '4(1) + c = 5 → c = 1.',
          'nth term = <strong>4n + 1</strong>. Check: n=2: 9 ✓',
        ],
      },
      sampleAnswer: {
        grade4: '4n − 2',
        grade6: 'd = 4. nth term = 4n + c. 4(1) + c = 2 → c = −2. nth term = 4n − 2.',
        grade8: 'd = 4 so nth term = 4n + c. Substituting n=1: 4+c=2 → c=−2. nth term = 4n − 2. Verify n=3: 12−2=10 ✓',
      },
      examinerTip: 'The coefficient of n equals the common difference. The constant c = (first term) − (common difference). Always verify with a second term.',
      auditStatus: 'pending',
    },
    {
      id: 'seq-A05', subtopic: 'alg-sequences', band: 'A', marks: 3,
      question: 'The nth term of a sequence is 3n − 2. Is 197 a term in this sequence? Justify your answer.',
      steps: [
        {
          prompt: 'Set 3n − 2 = 197 and solve. Add 2 to both sides: 3n = ?',
          hint1: '3n − 2 = 197 → 3n = 197 + 2.',
          hint2: '3n = 199.',
          hint3: '199.',
          answer: 199, tolerance: 0, unit: '',
          explanation: '3n = 199.',
        },
        {
          prompt: 'Divide by 3: what is 199 ÷ 3?',
          hint1: '199 ÷ 3 = ?',
          hint2: '66.33... (not a whole number).',
          hint3: 'n ≈ 66.33.',
          answer: 0, tolerance: 0, unit: '',
          explanation: '199 ÷ 3 = 66.33... — not a positive integer.',
          checkType: 'skip',
          displayAnswer: 'n = 66.33...',
        },
        {
          prompt: 'Since n must be a positive integer, is 197 in this sequence? Enter 1 for Yes, 0 for No.',
          hint1: '66.33 is not a whole number.',
          hint2: '197 is NOT a term in this sequence.',
          hint3: '0 (No).',
          answer: 0, tolerance: 0, unit: '',
          explanation: '197 is NOT a term — n = 66.33 is not a positive integer.',
          checkType: 'skip',
          displayAnswer: '197 is NOT in this sequence',
        },
      ],
      workedExample: {
        question: 'Is 100 a term in the sequence with nth term 5n − 4?',
        steps: [
          '5n − 4 = 100 → 5n = 104.',
          'n = 104/5 = 20.8 — not a whole number.',
          '100 is <strong>NOT</strong> a term in this sequence.',
        ],
      },
      sampleAnswer: {
        grade4: 'No, 197 is not a term.',
        grade6: '3n − 2 = 197 → 3n = 199 → n = 66.33 (not an integer). So 197 is not a term.',
        grade8: 'Set 3n − 2 = 197 → n = 199/3 = 66.3̄. Since n must be a positive integer and 66.3̄ is not, 197 is not in this sequence.',
      },
      examinerTip: 'To test membership: set nth term = target value, solve for n, then check if n is a positive integer. If not, the value is not in the sequence.',
      auditStatus: 'pending',
    },
    {
      id: 'seq-B02', subtopic: 'alg-sequences', band: 'B', marks: 3,
      question: 'Find the sum of the first 8 terms of the arithmetic sequence 4, 7, 10, 13, ...',
      steps: [
        {
          prompt: 'Find the 8th term using nth term = 3n + 1.',
          hint1: 'Common difference = 3. nth term = 3n + 1.',
          hint2: '8th term = 3(8) + 1 = 25.',
          hint3: '25.',
          answer: 25, tolerance: 0, unit: '',
          explanation: 'nth term = 3n + 1. 8th term = 3(8) + 1 = 25.',
        },
        {
          prompt: 'Use Sₙ = (n/2)(first + last): calculate (first + last).',
          hint1: 'First = 4, last = 25. 4 + 25 = ?',
          hint2: '29.',
          hint3: '29.',
          answer: 29, tolerance: 0, unit: '',
          explanation: 'First + last = 4 + 25 = 29.',
        },
        {
          prompt: 'Calculate S₈ = (8/2) × 29.',
          hint1: '8/2 = 4. 4 × 29 = ?',
          hint2: '4 × 29 = 116.',
          hint3: 'S₈ = 116.',
          answer: 116, tolerance: 0, unit: '',
          explanation: 'S₈ = 4 × 29 = 116.',
          displayAnswer: 'Sum = 116',
        },
      ],
      workedExample: {
        question: 'Find the sum of the first 6 terms of 3, 7, 11, 15, ...',
        steps: [
          'nth term = 4n − 1. 6th term = 23.',
          'S₆ = (6/2)(3 + 23) = 3 × 26.',
          'S₆ = <strong>78</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: '116',
        grade6: '8th term = 25. S₈ = (8/2)(4+25) = 4 × 29 = 116.',
        grade8: 'nth term = 3n+1. 8th term = 25. S₈ = (8/2)(4+25) = 4×29 = 116. Can verify by listing: 4+7+10+13+16+19+22+25=116 ✓',
      },
      examinerTip: 'Arithmetic sum formula: Sₙ = (n/2)(first + last). Find the last term first using nth term formula, then apply the sum formula.',
      auditStatus: 'pending',
    },
    {
      id: 'seq-B03', subtopic: 'alg-sequences', band: 'B', marks: 3,
      question: 'A geometric sequence starts 5, 15, 45, ... Find the 5th term.',
      steps: [
        {
          prompt: 'Find the common ratio r.',
          hint1: 'r = 15 ÷ 5.',
          hint2: 'r = 3.',
          hint3: '3.',
          answer: 3, tolerance: 0, unit: '',
          explanation: 'r = 15/5 = 3.',
        },
        {
          prompt: 'Find the 4th term by multiplying the 3rd term by r.',
          hint1: '45 × 3 = ?',
          hint2: '135.',
          hint3: '4th term = 135.',
          answer: 135, tolerance: 0, unit: '',
          explanation: '4th term = 45 × 3 = 135.',
        },
        {
          prompt: 'Find the 5th term.',
          hint1: '135 × 3 = ?',
          hint2: '405.',
          hint3: '5th term = 405.',
          answer: 405, tolerance: 0, unit: '',
          explanation: '5th term = 135 × 3 = 405.',
        },
      ],
      workedExample: {
        question: 'Geometric sequence: 2, 6, 18, ... Find the 6th term.',
        steps: [
          'r = 6/2 = 3.',
          '4th = 18×3=54. 5th = 54×3=162.',
          '6th = 162 × 3 = <strong>486</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: '405',
        grade6: 'r = 3. Terms: 5, 15, 45, 135, 405. 5th term = 405.',
        grade8: 'r = 15/5 = 3. nth term = 5 × 3^(n−1). 5th term = 5 × 3⁴ = 5 × 81 = 405.',
      },
      examinerTip: 'Geometric sequences multiply by r each time. Either multiply step by step, or use nth term = a × r^(n−1).',
      auditStatus: 'pending',
    },
    {
      id: 'seq-B04', subtopic: 'alg-sequences', band: 'B', marks: 3,
      question: 'Find the nth term of the quadratic sequence 3, 8, 15, 24, 35, ...',
      steps: [
        {
          prompt: 'Find the second differences. First differences: 5, 7, 9, 11. What is the second difference?',
          hint1: '7 − 5 = 2. 9 − 7 = 2.',
          hint2: 'Second difference = 2.',
          hint3: '2.',
          answer: 2, tolerance: 0, unit: '',
          explanation: 'Second differences are constant at 2.',
        },
        {
          prompt: 'Leading coefficient of n² = second difference ÷ 2. What is it?',
          hint1: '2 ÷ 2 = 1.',
          hint2: 'The nth term starts with n².',
          hint3: 'Coefficient = 1.',
          answer: 1, tolerance: 0, unit: '',
          explanation: 'Coefficient of n² = 2/2 = 1. Starts with n².',
        },
        {
          prompt: 'Subtract n² from each term: 3−1=2, 8−4=4, 15−9=6 ... This is 2n. Write the nth term and verify for n = 3.',
          hint1: 'nth term = n² + 2n. When n = 3: 9 + 6 = 15 ✓',
          hint2: '15.',
          hint3: 'nth term = n² + 2n.',
          answer: 15, tolerance: 0, unit: '',
          explanation: 'nth term = n² + 2n. Verify n=3: 9+6=15 ✓',
          displayAnswer: 'nth term = n² + 2n',
        },
      ],
      workedExample: {
        question: 'Find nth term of 2, 6, 12, 20, 30, ...',
        steps: [
          'First diff: 4, 6, 8, 10. Second diff: 2. Coefficient of n² = 1.',
          'Subtract n²: 1, 2, 3, 4, 5 → linear part = n.',
          'nth term = n² + n. Check n=3: 9+3=12 ✓ Answer: <strong>n² + n</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: 'nth term = n² + 2n',
        grade6: 'Second difference = 2 → n² term. Subtract n²: 2, 4, 6 → 2n. nth term = n² + 2n.',
        grade8: 'Second diff = 2 → leading coeff = 1. n²: 1,4,9,16. Remainder: 2,4,6,8 → 2n. nth term = n²+2n. Verify n=5: 25+10=35 ✓',
      },
      examinerTip: 'For quadratic sequences: constant second difference → n² term. Leading coefficient = second difference ÷ 2. Then subtract n² to find the linear part.',
      auditStatus: 'pending',
    },
    {
      id: 'seq-B05', subtopic: 'alg-sequences', band: 'B', marks: 3,
      question: 'The nth term of a sequence is n² − n + 4. Find the 1st, 2nd, and 10th terms.',
      steps: [
        {
          prompt: 'Substitute n = 1: calculate 1² − 1 + 4.',
          hint1: '1 − 1 + 4.',
          hint2: '4.',
          hint3: '4.',
          answer: 4, tolerance: 0, unit: '',
          explanation: '1 − 1 + 4 = 4.',
        },
        {
          prompt: 'Substitute n = 2: calculate 2² − 2 + 4.',
          hint1: '4 − 2 + 4.',
          hint2: '6.',
          hint3: '6.',
          answer: 6, tolerance: 0, unit: '',
          explanation: '4 − 2 + 4 = 6.',
        },
        {
          prompt: 'Substitute n = 10: calculate 10² − 10 + 4.',
          hint1: '100 − 10 + 4.',
          hint2: '94.',
          hint3: '94.',
          answer: 94, tolerance: 0, unit: '',
          explanation: '100 − 10 + 4 = 94.',
        },
      ],
      workedExample: {
        question: 'nth term = 2n² − n. Find the 1st, 3rd, and 5th terms.',
        steps: [
          'n=1: 2(1)−1 = 1.',
          'n=3: 2(9)−3 = 15.',
          'n=5: 2(25)−5 = <strong>45</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: '4, 6, 94',
        grade6: 'n=1: 1−1+4=4. n=2: 4−2+4=6. n=10: 100−10+4=94.',
        grade8: 'n²−n+4: n=1 → 4, n=2 → 6, n=10 → 94. The sequence is not arithmetic (differences increase), indicating it is quadratic.',
      },
      examinerTip: 'Substitute n values one at a time and show each calculation. For n=10, evaluate each term (100, 10, 4) separately to avoid errors.',
      auditStatus: 'pending',
    },
    {
      id: 'seq-B06', subtopic: 'alg-sequences', band: 'B', marks: 4,
      question: 'An arithmetic sequence has 3rd term = 11 and 7th term = 27. Find the nth term formula.',
      steps: [
        {
          prompt: 'The difference between the 7th and 3rd terms spans 4 steps. Find the common difference d.',
          hint1: '27 − 11 = 16 over 4 steps.',
          hint2: 'd = 16 ÷ 4.',
          hint3: 'd = 4.',
          answer: 4, tolerance: 0, unit: '',
          explanation: 'd = (27 − 11)/(7 − 3) = 16/4 = 4.',
        },
        {
          prompt: 'Work back from the 3rd term to find the 1st term: a = T₃ − 2d.',
          hint1: 'a = 11 − 2 × 4.',
          hint2: 'a = 11 − 8.',
          hint3: 'a = 3.',
          answer: 3, tolerance: 0, unit: '',
          explanation: 'a = 11 − 2(4) = 3.',
        },
        {
          prompt: 'nth term = a + (n − 1)d. Simplify.',
          hint1: 'nth term = 3 + (n − 1)(4) = 3 + 4n − 4.',
          hint2: '= 4n − 1.',
          hint3: 'nth term = 4n − 1.',
          answer: 0, tolerance: 0, unit: '',
          explanation: 'nth term = 3 + 4(n−1) = 4n − 1.',
          checkType: 'skip',
          displayAnswer: 'nth term = 4n − 1',
        },
        {
          prompt: 'Verify: when n = 3, nth term = 4(3) − 1 = ?',
          hint1: '12 − 1.',
          hint2: '11. ✓',
          hint3: '11.',
          answer: 11, tolerance: 0, unit: '',
          explanation: '4(3) − 1 = 11 ✓ (matches given 3rd term).',
        },
      ],
      workedExample: {
        question: '4th term = 13, 8th term = 29. Find nth term.',
        steps: [
          'd = (29−13)/(8−4) = 16/4 = 4.',
          'a = 13 − 3(4) = 1.',
          'nth term = 1 + (n−1)(4) = 4n − 3. Check n=4: 16−3=13 ✓',
        ],
      },
      sampleAnswer: {
        grade4: '4n − 1',
        grade6: 'd = (27−11)/4 = 4. a = 11 − 8 = 3. nth term = 3 + 4(n−1) = 4n − 1.',
        grade8: 'd=4, a=3. nth term = a+(n−1)d = 3+4(n−1) = 4n−1. Verify: n=7: 28−1=27 ✓',
      },
      examinerTip: 'Find d from (T_higher − T_lower)/(higher n − lower n). Then find the first term by working backwards. Simplify a + (n−1)d into the form pn + q.',
      auditStatus: 'pending',
    },
    {
      id: 'seq-C01', subtopic: 'alg-sequences', band: 'C', marks: 4,
      question: 'Find the value(s) of n where the sequence 4n + 3 and the sequence 3n + 7 have the same value.',
      steps: [
        {
          prompt: 'Set the two nth terms equal.',
          hint1: '4n + 3 = 3n + 7.',
          hint2: 'Collect n terms on the left.',
          hint3: 'n = 4.',
          answer: 0, tolerance: 0, unit: '',
          explanation: '4n + 3 = 3n + 7 → n = 4.',
          checkType: 'skip',
          displayAnswer: '4n + 3 = 3n + 7',
        },
        {
          prompt: 'Subtract 3n from both sides: n + 3 = 7. Solve for n.',
          hint1: 'n = 7 − 3.',
          hint2: 'n = 4.',
          hint3: '4.',
          answer: 4, tolerance: 0, unit: '',
          explanation: 'n = 4.',
        },
        {
          prompt: 'Find the common value at n = 4 using 4n + 3.',
          hint1: '4(4) + 3 = ?',
          hint2: '16 + 3 = 19.',
          hint3: '19.',
          answer: 19, tolerance: 0, unit: '',
          explanation: '4(4)+3 = 19.',
        },
        {
          prompt: 'Verify using the second sequence: 3(4) + 7 = ?',
          hint1: '12 + 7 = ?',
          hint2: '19. ✓',
          hint3: '19.',
          answer: 19, tolerance: 0, unit: '',
          explanation: '3(4)+7 = 19. Both sequences equal 19 when n = 4. ✓',
        },
      ],
      workedExample: {
        question: 'When do 5n − 2 and 3n + 8 give the same value?',
        steps: [
          '5n − 2 = 3n + 8 → 2n = 10 → n = 5.',
          'Common value = 5(5) − 2 = 23.',
          'Verify: 3(5)+8 = 23 ✓',
        ],
      },
      sampleAnswer: {
        grade4: 'n = 4, common value = 19',
        grade6: '4n+3 = 3n+7 → n = 4. Common value = 4(4)+3 = 19. Verify: 3(4)+7=19 ✓',
        grade8: 'Setting equal: n = 4. Common value = 19. The sequences share this value only at n = 4 — before that, 3n+7 is larger; after, 4n+3 is larger.',
      },
      examinerTip: 'Set the two formulas equal and solve for n. Check that n is a positive integer — if not, the sequences never share a value.',
      auditStatus: 'pending',
    },
    {
      id: 'seq-C02', subtopic: 'alg-sequences', band: 'C', marks: 4,
      question: 'Find the nth term of the quadratic sequence 0, 3, 8, 15, 24, ...',
      steps: [
        {
          prompt: 'Find the second differences. First differences: 3, 5, 7, 9. Second difference = ?',
          hint1: '5 − 3 = 2. 7 − 5 = 2.',
          hint2: 'Second difference = 2.',
          hint3: '2.',
          answer: 2, tolerance: 0, unit: '',
          explanation: 'Constant second difference = 2.',
        },
        {
          prompt: 'Leading coefficient of n² = second diff ÷ 2. What is it?',
          hint1: '2 ÷ 2 = 1.',
          hint2: 'Coefficient = 1.',
          hint3: '1.',
          answer: 1, tolerance: 0, unit: '',
          explanation: 'Coefficient of n² = 1.',
        },
        {
          prompt: 'Subtract n² from each term: 0−1=−1, 3−4=−1, 8−9=−1. What is the constant correction?',
          hint1: 'All remainders are −1.',
          hint2: 'Constant term = −1.',
          hint3: '−1.',
          answer: -1, tolerance: 0, unit: '',
          explanation: 'Remainder is constant at −1. nth term = n² − 1.',
        },
        {
          prompt: 'Verify: when n = 4, nth term = 4² − 1 = ?',
          hint1: '16 − 1 = ?',
          hint2: '15. ✓',
          hint3: '15.',
          answer: 15, tolerance: 0, unit: '',
          explanation: 'n=4: 16−1=15 ✓ nth term = n² − 1.',
          displayAnswer: 'nth term = n² − 1',
        },
      ],
      workedExample: {
        question: 'nth term of 0, 2, 6, 12, 20, ...',
        steps: [
          'First diff: 2, 4, 6, 8 → second diff = 2 → coefficient n² = 1.',
          'Subtract n²: −1, −2, −3, −4 — wait, that is not constant. Re-examine.',
          'Actually: 0−1=−1, 2−4=−2 — not constant. Try: differences 2,4,6,8 → linear part. nth term = n²−n = n(n−1). Check n=3: 6 ✓',
        ],
      },
      sampleAnswer: {
        grade4: 'nth term = n² − 1',
        grade6: 'Second diff = 2 → n². Subtract n²: −1, −1, −1, −1, −1. Constant = −1. nth term = n² − 1.',
        grade8: 'n²: 1,4,9,16,25. Subtract from sequence: −1,−1,−1,−1,−1. Constant remainder → nth term = n²−1. Verify n=5: 25−1=24 ✓',
      },
      examinerTip: 'After subtracting n², the remainder should be either constant (add a constant) or linear (find the linear nth term). If it is constant, you are done.',
      auditStatus: 'pending',
    },
    {
      id: 'seq-C03', subtopic: 'alg-sequences', band: 'C', marks: 4,
      question: 'A geometric sequence has first term 2 and common ratio r. The sum of the first 3 terms is 26. Find r.',
      steps: [
        {
          prompt: 'Write the first 3 terms: 2, 2r, 2r². Their sum = 26. Set up the equation.',
          hint1: '2 + 2r + 2r² = 26.',
          hint2: 'Divide by 2: 1 + r + r² = 13.',
          hint3: 'r² + r − 12 = 0.',
          answer: 0, tolerance: 0, unit: '',
          explanation: '2(1 + r + r²) = 26 → r² + r − 12 = 0.',
          checkType: 'skip',
          displayAnswer: 'r² + r − 12 = 0',
        },
        {
          prompt: 'Factorise r² + r − 12.',
          hint1: '(r + 4)(r − 3) = 0.',
          hint2: 'r = −4 or r = 3.',
          hint3: '(r + 4)(r − 3) = 0.',
          answer: 0, tolerance: 0, unit: '',
          explanation: '(r + 4)(r − 3) = 0.',
          checkType: 'skip',
          displayAnswer: '(r + 4)(r − 3) = 0',
        },
        {
          prompt: 'The common ratio r is positive. What is r?',
          hint1: 'r = 3 (positive solution).',
          hint2: 'r = 3.',
          hint3: '3.',
          answer: 3, tolerance: 0, unit: '',
          explanation: 'r = 3 (taking positive value).',
        },
        {
          prompt: 'Verify: 2 + 2(3) + 2(9) = ?',
          hint1: '2 + 6 + 18 = ?',
          hint2: '26. ✓',
          hint3: '26.',
          answer: 26, tolerance: 0, unit: '',
          explanation: '2 + 6 + 18 = 26 ✓',
        },
      ],
      workedExample: {
        question: 'First term 3, common ratio r. Sum of first 3 terms = 39. Find r.',
        steps: [
          '3 + 3r + 3r² = 39 → r² + r − 12 = 0.',
          '(r + 4)(r − 3) = 0 → r = 3.',
          'Verify: 3 + 9 + 27 = 39 ✓. <strong>r = 3</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: 'r = 3',
        grade6: '2+2r+2r²=26 → r²+r−12=0 → (r+4)(r−3)=0 → r=3. Verify: 2+6+18=26 ✓',
        grade8: 'r²+r−12=0 → r=3 (positive) or r=−4 (negative, rejected for this context). Sequence: 2, 6, 18. Sum=26 ✓',
      },
      examinerTip: 'Divide by the first term to simplify. The resulting quadratic usually factorises neatly. If a positive ratio is expected, reject the negative root.',
      auditStatus: 'pending',
    },
    {
      id: 'seq-C04', subtopic: 'alg-sequences', band: 'C', marks: 4,
      question: 'An arithmetic sequence has first term a and common difference d. The 4th term is 19 and the sum of the first 6 terms is 78. Find a and d.',
      steps: [
        {
          prompt: 'Write the equation for the 4th term: a + 3d = 19. Now write the sum of 6 terms formula and set equal to 78.',
          hint1: 'S₆ = (6/2)(2a + 5d) = 78 → 3(2a + 5d) = 78.',
          hint2: '2a + 5d = 26.',
          hint3: '26.',
          answer: 26, tolerance: 0, unit: '',
          explanation: '3(2a + 5d) = 78 → 2a + 5d = 26.',
        },
        {
          prompt: 'From a + 3d = 19: a = 19 − 3d. Substitute into 2a + 5d = 26. Solve for d.',
          hint1: '2(19 − 3d) + 5d = 26 → 38 − 6d + 5d = 26 → 38 − d = 26.',
          hint2: 'd = 38 − 26 = 12.',
          hint3: 'd = 12.',
          answer: 12, tolerance: 0, unit: '',
          explanation: '38 − d = 26 → d = 12.',
        },
        {
          prompt: 'Find a: a = 19 − 3d.',
          hint1: 'a = 19 − 3(12).',
          hint2: 'a = 19 − 36 = −17.',
          hint3: 'a = −17.',
          answer: -17, tolerance: 0, unit: '',
          explanation: 'a = 19 − 36 = −17.',
        },
        {
          prompt: 'Verify the sum: S₆ = (6/2)(2(−17) + 5(12)) = 3(−34 + 60) = ?',
          hint1: '3(26) = ?',
          hint2: '78. ✓',
          hint3: '78.',
          answer: 78, tolerance: 0, unit: '',
          explanation: 'S₆ = 3(26) = 78 ✓',
        },
      ],
      workedExample: {
        question: '3rd term = 9, S₄ = 24. Find a and d.',
        steps: [
          'a + 2d = 9. S₄ = 4/2 × (2a+3d) = 24 → 2a+3d = 12.',
          '2(9−2d)+3d=12 → 18−d=12 → d=6. a=9−12=−3.',
          'Verify: S₄=(4/2)(−6+18)=2×12=24 ✓',
        ],
      },
      sampleAnswer: {
        grade4: 'a = −17, d = 12',
        grade6: 'a+3d=19. 2a+5d=26. Sub a=19−3d: d=12, a=−17.',
        grade8: 'Two equations: a+3d=19 and 2a+5d=26. Eliminate a: d=12, a=−17. Sequence: −17, −5, 7, 19 ✓ (4th term = 19). S₆=3×26=78 ✓',
      },
      examinerTip: 'Sum formula Sₙ = (n/2)(2a + (n−1)d). For S₆: (6/2)(2a + 5d) = 78. Combine with the term equation to form simultaneous equations.',
      auditStatus: 'pending',
    },
"""

with open(FILE, encoding='utf-8') as f:
    content = f.read()

pos = content.find(MARKER)
if pos < 0:
    print('MARKER NOT FOUND')
else:
    print(f'Inserting at char {pos}')
    with open(FILE, 'w', encoding='utf-8') as f:
        f.write(content[:pos] + NEW + content[pos:])
    print('Done - batch 5 (12 seq questions)')
