FILE = r'C:\Users\jason\OneDrive\Documents\GitHub\mabel-gcse\js\maths-questions.js'
MARKER = "    {\n      id: 'pro-A01'"

NEW = """    {
      id: 'gph-A03', subtopic: 'alg-graphs', band: 'A', marks: 2,
      question: 'A straight line has equation y = −3x + 7. Write down the gradient and the y-intercept.',
      steps: [
        {
          prompt: 'The equation is in the form y = mx + c. What is the gradient m?',
          hint1: 'Compare y = −3x + 7 with y = mx + c.',
          hint2: 'm is the coefficient of x.',
          hint3: 'm = −3.',
          answer: -3, tolerance: 0, unit: '',
          explanation: 'The gradient is the coefficient of x: m = −3.',
        },
        {
          prompt: 'What is the y-intercept c?',
          hint1: 'c is the constant term.',
          hint2: 'It is the value of y when x = 0.',
          hint3: 'c = 7.',
          answer: 7, tolerance: 0, unit: '',
          explanation: 'The y-intercept c = 7 (the constant term).',
        },
      ],
      workedExample: {
        question: 'A line has equation y = 4x − 9. State the gradient and y-intercept.',
        steps: [
          'Write in the form y = mx + c: y = 4x − 9.',
          'Gradient m = 4 (coefficient of x).',
          'y-intercept c = −9 (constant term). The line crosses the y-axis at (0, −9).',
        ],
      },
      sampleAnswer: {
        grade4: 'gradient = −3, y-intercept = 7',
        grade6: 'The equation is y = mx + c. Gradient m = −3. y-intercept c = 7.',
        grade8: 'Comparing with y = mx + c: gradient = −3 (line falls 3 units for each 1 unit increase in x), y-intercept = 7 (crosses y-axis at (0, 7)).',
      },
      examinerTip: 'Always identify y = mx + c first. The gradient is the coefficient of x — include its sign. The y-intercept is the constant term.',
      auditStatus: 'pending',
    },
    {
      id: 'gph-A04', subtopic: 'alg-graphs', band: 'A', marks: 2,
      question: 'The line y = 3x − 4 passes through the point (2, k). Find the value of k.',
      steps: [
        {
          prompt: 'Substitute x = 2 into the equation. Calculate 3 × 2.',
          hint1: '3 × 2 = ?',
          hint2: '3 × 2 = 6.',
          hint3: '6.',
          answer: 6, tolerance: 0, unit: '',
          explanation: 'Substituting x = 2: y = 3(2) − 4 = 6 − 4.',
        },
        {
          prompt: 'Calculate k = 6 − 4.',
          hint1: '6 − 4 = ?',
          hint2: 'k = 2.',
          hint3: '2.',
          answer: 2, tolerance: 0, unit: '',
          explanation: 'k = 6 − 4 = 2.',
        },
      ],
      workedExample: {
        question: 'The line y = 2x + 5 passes through (3, k). Find k.',
        steps: [
          'Substitute x = 3: y = 2(3) + 5.',
          '2 × 3 = 6.',
          'k = 6 + 5 = <strong>11</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: 'k = 2',
        grade6: 'Substitute x = 2: y = 3(2) − 4 = 6 − 4 = 2. So k = 2.',
        grade8: 'Substituting x = 2: y = 3(2) − 4 = 6 − 4 = 2. The point (2, 2) lies on the line y = 3x − 4.',
      },
      examinerTip: 'Substitute the x value given into the equation and evaluate — this is a direct substitution. Do not rearrange the equation.',
      auditStatus: 'pending',
    },
    {
      id: 'gph-A05', subtopic: 'alg-graphs', band: 'A', marks: 2,
      question: 'Find the coordinates of the midpoint of the line segment joining (1, 3) and (7, 9).',
      steps: [
        {
          prompt: 'Average the x-coordinates: (1 + 7) ÷ 2.',
          hint1: '1 + 7 = 8.',
          hint2: '8 ÷ 2 = 4.',
          hint3: 'x-coordinate of midpoint = 4.',
          answer: 4, tolerance: 0, unit: '',
          explanation: 'x-midpoint = (1 + 7)/2 = 4.',
        },
        {
          prompt: 'Average the y-coordinates: (3 + 9) ÷ 2.',
          hint1: '3 + 9 = 12.',
          hint2: '12 ÷ 2 = 6.',
          hint3: 'y-coordinate of midpoint = 6.',
          answer: 6, tolerance: 0, unit: '',
          explanation: 'y-midpoint = (3 + 9)/2 = 6. Midpoint = (4, 6).',
          displayAnswer: 'Midpoint = (4, 6)',
        },
      ],
      workedExample: {
        question: 'Find the midpoint of (2, 8) and (10, 4).',
        steps: [
          'x-midpoint = (2 + 10)/2 = 12/2 = 6.',
          'y-midpoint = (8 + 4)/2 = 12/2 = 6.',
          'Midpoint = <strong>(6, 6)</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: '(4, 6)',
        grade6: 'x: (1+7)/2 = 4. y: (3+9)/2 = 6. Midpoint = (4, 6).',
        grade8: 'Midpoint = ((1+7)/2, (3+9)/2) = (8/2, 12/2) = (4, 6).',
      },
      examinerTip: 'Midpoint = (average of x-coordinates, average of y-coordinates). A common error is to add the coordinates without dividing by 2.',
      auditStatus: 'pending',
    },
    {
      id: 'gph-B02', subtopic: 'alg-graphs', band: 'B', marks: 3,
      question: 'A line passes through (0, −2) and (4, 10). Find the equation of the line.',
      steps: [
        {
          prompt: 'Find the gradient using m = (y₂ − y₁)/(x₂ − x₁).',
          hint1: 'Use (0, −2) and (4, 10): m = (10 − (−2))/(4 − 0).',
          hint2: 'm = 12/4.',
          hint3: 'm = 3.',
          answer: 3, tolerance: 0, unit: '',
          explanation: 'm = (10−(−2))/(4−0) = 12/4 = 3.',
        },
        {
          prompt: 'Find the y-intercept c. The line passes through (0, −2). What is c?',
          hint1: 'The y-intercept is the y value when x = 0.',
          hint2: 'The point (0, −2) is on the y-axis.',
          hint3: 'c = −2.',
          answer: -2, tolerance: 0, unit: '',
          explanation: 'Since the line passes through (0, −2), the y-intercept c = −2.',
          displayAnswer: 'y = 3x − 2',
        },
        {
          prompt: 'Write the complete equation of the line.',
          hint1: 'Use y = mx + c with m = 3 and c = −2.',
          hint2: 'y = 3x − 2.',
          hint3: 'y = 3x − 2.',
          answer: 0, tolerance: 0, unit: '',
          explanation: 'Equation: y = 3x − 2. Verify: (4, 10): 3(4)−2 = 10 ✓',
          checkType: 'skip',
          displayAnswer: 'y = 3x − 2',
        },
      ],
      workedExample: {
        question: 'Find the equation of the line through (0, 4) and (3, 13).',
        steps: [
          'm = (13 − 4)/(3 − 0) = 9/3 = 3.',
          'y-intercept: line passes through (0, 4), so c = 4.',
          'Equation: <strong>y = 3x + 4</strong>. Check: 3(3)+4=13 ✓',
        ],
      },
      sampleAnswer: {
        grade4: 'y = 3x − 2',
        grade6: 'm = (10+2)/4 = 3. y-intercept = −2. Equation: y = 3x − 2.',
        grade8: 'm = 12/4 = 3. Since line crosses y-axis at −2, equation is y = 3x − 2. Verify (4, 10): 3(4)−2=10 ✓',
      },
      examinerTip: 'When one point is on the y-axis (x = 0), the y-intercept c is simply that y value. No substitution needed.',
      auditStatus: 'pending',
    },
    {
      id: 'gph-B03', subtopic: 'alg-graphs', band: 'B', marks: 3,
      question: 'Find the equation of the line passing through (−1, 1) and (2, 7).',
      steps: [
        {
          prompt: 'Find the gradient: m = (7 − 1)/(2 − (−1)).',
          hint1: '(7 − 1) = 6. (2 − (−1)) = 3.',
          hint2: 'm = 6/3.',
          hint3: 'm = 2.',
          answer: 2, tolerance: 0, unit: '',
          explanation: 'm = (7−1)/(2−(−1)) = 6/3 = 2.',
        },
        {
          prompt: 'Substitute m = 2 and point (−1, 1) into y = mx + c to find c.',
          hint1: '1 = 2(−1) + c.',
          hint2: '1 = −2 + c → c = 3.',
          hint3: 'c = 3.',
          answer: 3, tolerance: 0, unit: '',
          explanation: '1 = 2(−1) + c → 1 = −2 + c → c = 3.',
          displayAnswer: 'y = 2x + 3',
        },
        {
          prompt: 'Write the equation. Verify using the second point (2, 7).',
          hint1: 'y = 2x + 3. Check (2, 7): 2(2)+3 = 7.',
          hint2: '4 + 3 = 7. ✓',
          hint3: 'Equation confirmed: y = 2x + 3.',
          answer: 0, tolerance: 0, unit: '',
          explanation: 'Equation y = 2x + 3. Verify (2, 7): 2(2)+3=7 ✓',
          checkType: 'skip',
          displayAnswer: 'y = 2x + 3',
        },
      ],
      workedExample: {
        question: 'Find the equation of the line through (1, 4) and (3, 10).',
        steps: [
          'm = (10 − 4)/(3 − 1) = 6/2 = 3.',
          'Sub (1, 4): 4 = 3(1) + c → c = 1.',
          'Equation: <strong>y = 3x + 1</strong>. Check (3, 10): 3(3)+1=10 ✓',
        ],
      },
      sampleAnswer: {
        grade4: 'y = 2x + 3',
        grade6: 'm = 6/3 = 2. Sub (−1, 1): c = 3. Equation: y = 2x + 3.',
        grade8: 'm = (7−1)/(2−(−1)) = 2. Sub (−1, 1): 1 = −2+c → c=3. y=2x+3. Verify (2,7): 4+3=7 ✓',
      },
      examinerTip: 'Find m first, then substitute one point to find c. Always verify using the other point.',
      auditStatus: 'pending',
    },
    {
      id: 'gph-B04', subtopic: 'alg-graphs', band: 'B', marks: 3,
      question: 'A line parallel to y = 2x + 5 passes through (3, 1). Find the equation of the line.',
      steps: [
        {
          prompt: 'Parallel lines have the same gradient. What is the gradient of the new line?',
          hint1: 'y = 2x + 5 has gradient 2.',
          hint2: 'Parallel lines have equal gradients.',
          hint3: 'm = 2.',
          answer: 2, tolerance: 0, unit: '',
          explanation: 'Parallel lines have the same gradient: m = 2.',
        },
        {
          prompt: 'Substitute m = 2 and point (3, 1) into y = mx + c to find c.',
          hint1: '1 = 2(3) + c.',
          hint2: '1 = 6 + c → c = 1 − 6.',
          hint3: 'c = −5.',
          answer: -5, tolerance: 0, unit: '',
          explanation: '1 = 2(3) + c → 1 = 6 + c → c = −5.',
          displayAnswer: 'y = 2x − 5',
        },
        {
          prompt: 'Write the equation of the parallel line.',
          hint1: 'y = mx + c with m = 2, c = −5.',
          hint2: 'y = 2x − 5.',
          hint3: 'y = 2x − 5.',
          answer: 0, tolerance: 0, unit: '',
          explanation: 'Equation: y = 2x − 5. (Parallel to y=2x+5, different c.)',
          checkType: 'skip',
          displayAnswer: 'y = 2x − 5',
        },
      ],
      workedExample: {
        question: 'Find the equation of the line parallel to y = 4x − 3 through (2, 5).',
        steps: [
          'Gradient = 4 (parallel → same gradient).',
          'Sub (2, 5): 5 = 4(2) + c → c = −3.',
          'Equation: <strong>y = 4x − 3</strong>. Wait — that is the original line. Sub again: 5 = 8 + c → c = −3. Equation: <strong>y = 4x − 3</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: 'y = 2x − 5',
        grade6: 'Gradient = 2 (parallel). Sub (3, 1): 1 = 6 + c → c = −5. Equation: y = 2x − 5.',
        grade8: 'Parallel → m = 2. Sub (3, 1): c = 1 − 6 = −5. y = 2x − 5. (Note: same gradient as y=2x+5 but different intercept.)',
      },
      examinerTip: 'Parallel lines have identical gradients. Only the y-intercept differs. Do not confuse parallel (same m) with perpendicular (product of gradients = −1).',
      auditStatus: 'pending',
    },
    {
      id: 'gph-B05', subtopic: 'alg-graphs', band: 'B', marks: 4,
      question: 'A straight line has gradient −2 and passes through (3, 4). Find the equation of the line and the coordinates of the x-intercept.',
      steps: [
        {
          prompt: 'Use y = mx + c with m = −2. Substitute x = 3 and y = 4. Calculate −2 × 3.',
          hint1: '−2 × 3 = ?',
          hint2: '−2 × 3 = −6.',
          hint3: '−6.',
          answer: -6, tolerance: 0, unit: '',
          explanation: '4 = −2(3) + c → 4 = −6 + c.',
        },
        {
          prompt: 'Find c: c = 4 − (−6).',
          hint1: '4 − (−6) = 4 + 6.',
          hint2: 'c = 10.',
          hint3: 'c = 10.',
          answer: 10, tolerance: 0, unit: '',
          explanation: 'c = 4 + 6 = 10. Equation: y = −2x + 10.',
          displayAnswer: 'y = −2x + 10',
        },
        {
          prompt: 'Write the equation of the line.',
          hint1: 'y = mx + c with m = −2, c = 10.',
          hint2: 'y = −2x + 10.',
          hint3: 'y = −2x + 10.',
          answer: 0, tolerance: 0, unit: '',
          explanation: 'Equation: y = −2x + 10.',
          checkType: 'skip',
          displayAnswer: 'y = −2x + 10',
        },
        {
          prompt: 'Find the x-intercept: set y = 0 and solve for x.',
          hint1: '0 = −2x + 10 → 2x = 10.',
          hint2: 'x = 5.',
          hint3: 'x-intercept at (5, 0).',
          answer: 5, tolerance: 0, unit: '',
          explanation: '0 = −2x + 10 → x = 5. x-intercept: (5, 0).',
          displayAnswer: 'x-intercept = (5, 0)',
        },
      ],
      workedExample: {
        question: 'A line has gradient −3 and passes through (2, 4). Find the equation and x-intercept.',
        steps: [
          'Sub (2, 4) into y = −3x + c: 4 = −6 + c → c = 10.',
          'Equation: y = −3x + 10.',
          'x-intercept: 0 = −3x + 10 → x = 10/3 ≈ 3.33. Point: (10/3, 0).',
        ],
      },
      sampleAnswer: {
        grade4: 'y = −2x + 10, x-intercept = 5',
        grade6: 'Sub (3,4): 4 = −6 + c → c = 10. Equation: y = −2x + 10. x-intercept: 2x = 10 → x = 5.',
        grade8: 'c = 4−(−2×3) = 10. y = −2x + 10. x-intercept (y=0): x = 5. Point (5, 0). Line has negative gradient, falls left to right.',
      },
      examinerTip: 'For the x-intercept, substitute y = 0 and solve. For the y-intercept, substitute x = 0. These are two different things.',
      auditStatus: 'pending',
    },
    {
      id: 'gph-B06', subtopic: 'alg-graphs', band: 'B', marks: 4,
      question: 'Find the coordinates of the intersection of the lines y = 3x − 4 and y = x + 2.',
      steps: [
        {
          prompt: 'At the intersection, both y values are equal. Set 3x − 4 = x + 2 and collect x terms.',
          hint1: '3x − 4 = x + 2 → 3x − x = ?',
          hint2: '2x = 2 + 4.',
          hint3: '2x = 6.',
          answer: 6, tolerance: 0, unit: '',
          explanation: '3x − 4 = x + 2 → 2x = 6.',
        },
        {
          prompt: 'Divide to find x.',
          hint1: '2x = 6 → x = ?',
          hint2: 'x = 3.',
          hint3: 'x = 3.',
          answer: 3, tolerance: 0, unit: '',
          explanation: 'x = 6/2 = 3.',
        },
        {
          prompt: 'Substitute x = 3 into y = x + 2 to find y.',
          hint1: 'y = 3 + 2.',
          hint2: 'y = 5.',
          hint3: 'y = 5.',
          answer: 5, tolerance: 0, unit: '',
          explanation: 'y = 3 + 2 = 5. Intersection at (3, 5).',
        },
        {
          prompt: 'Verify using the other equation: y = 3x − 4 when x = 3.',
          hint1: '3(3) − 4 = 9 − 4 = 5.',
          hint2: 'Both equations give y = 5. ✓',
          hint3: 'Intersection confirmed at (3, 5).',
          answer: 0, tolerance: 0, unit: '',
          explanation: '3(3)−4 = 5 = y ✓. Intersection: (3, 5).',
          checkType: 'skip',
          displayAnswer: 'Intersection: (3, 5)',
        },
      ],
      workedExample: {
        question: 'Find the intersection of y = 2x + 1 and y = x + 5.',
        steps: [
          'Set equal: 2x + 1 = x + 5 → x = 4.',
          'y = 4 + 5 = 9.',
          'Intersection: <strong>(4, 9)</strong>. Check: 2(4)+1=9 ✓',
        ],
      },
      sampleAnswer: {
        grade4: '(3, 5)',
        grade6: '3x − 4 = x + 2 → 2x = 6 → x = 3. y = 5. Intersection (3, 5).',
        grade8: 'Set equal: 2x = 6 → x = 3, y = 5. Verify: 3(3)−4=5 ✓ Intersection: (3, 5).',
      },
      examinerTip: 'To find intersection algebraically: set the two y expressions equal, solve for x, then substitute back. Always verify in the other equation.',
      auditStatus: 'pending',
    },
    {
      id: 'gph-C01', subtopic: 'alg-graphs', band: 'C', marks: 4,
      question: 'Find the equation of the perpendicular bisector of the line segment joining A(2, 4) and B(6, 8).',
      steps: [
        {
          prompt: 'Find the gradient of AB.',
          hint1: 'm = (8 − 4)/(6 − 2).',
          hint2: 'm = 4/4.',
          hint3: 'm = 1.',
          answer: 1, tolerance: 0, unit: '',
          explanation: 'm₁ = (8−4)/(6−2) = 4/4 = 1.',
        },
        {
          prompt: 'Find the gradient of the perpendicular bisector. (Product of perpendicular gradients = −1.)',
          hint1: 'm₁ × m₂ = −1.',
          hint2: '1 × m₂ = −1.',
          hint3: 'm₂ = −1.',
          answer: -1, tolerance: 0, unit: '',
          explanation: 'Perpendicular gradient = −1/1 = −1.',
        },
        {
          prompt: 'Find the midpoint of AB (the perpendicular bisector passes through it).',
          hint1: 'Midpoint = ((2+6)/2, (4+8)/2).',
          hint2: 'Midpoint = (4, 6).',
          hint3: '(4, 6).',
          answer: 0, tolerance: 0, unit: '',
          explanation: 'Midpoint = (4, 6).',
          checkType: 'skip',
          displayAnswer: 'Midpoint = (4, 6)',
        },
        {
          prompt: 'Use the midpoint (4, 6) and gradient −1 to find c. Then state the y-intercept.',
          hint1: '6 = −1(4) + c → c = 6 + 4.',
          hint2: 'c = 10.',
          hint3: 'Equation: y = −x + 10.',
          answer: 10, tolerance: 0, unit: '',
          explanation: '6 = −4 + c → c = 10. Perpendicular bisector: y = −x + 10.',
          displayAnswer: 'y = −x + 10',
        },
      ],
      workedExample: {
        question: 'Find the perpendicular bisector of (0, 2) and (4, 6).',
        steps: [
          'm₁ = (6−2)/(4−0) = 1. Perpendicular gradient m₂ = −1.',
          'Midpoint = (2, 4).',
          'Sub (2, 4): 4 = −2 + c → c = 6.',
          'Perpendicular bisector: <strong>y = −x + 6</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: 'y = −x + 10',
        grade6: 'm(AB) = 1. Perpendicular gradient = −1. Midpoint (4, 6). c = 10. Equation: y = −x + 10.',
        grade8: 'm(AB)=1, m⊥=−1. Midpoint=(4,6). y=−x+c: 6=−4+c → c=10. Perpendicular bisector: y=−x+10.',
      },
      examinerTip: 'Two steps: (1) find the negative reciprocal of the gradient for perpendicular, (2) use the midpoint (not an endpoint) to find c.',
      auditStatus: 'pending',
    },
    {
      id: 'gph-C02', subtopic: 'alg-graphs', band: 'C', marks: 4,
      question: 'Find the equation of the line perpendicular to y = 2x − 3 that passes through (4, 1).',
      steps: [
        {
          prompt: 'What is the gradient of y = 2x − 3?',
          hint1: 'Compare with y = mx + c.',
          hint2: 'm = 2.',
          hint3: 'm = 2.',
          answer: 2, tolerance: 0, unit: '',
          explanation: 'Gradient of given line = 2.',
        },
        {
          prompt: 'Find the perpendicular gradient. (m₁ × m₂ = −1, so m₂ = −1/m₁.)',
          hint1: 'm₂ = −1/2.',
          hint2: 'Perpendicular gradient = −1/2 = −0.5.',
          hint3: '−0.5.',
          answer: 0, tolerance: 0, unit: '',
          explanation: 'Perpendicular gradient = −1/2.',
          checkType: 'skip',
          displayAnswer: 'm₂ = −1/2',
        },
        {
          prompt: 'Substitute m = −1/2 and point (4, 1) into y = mx + c. Calculate c.',
          hint1: '1 = (−1/2)(4) + c → 1 = −2 + c.',
          hint2: 'c = 1 + 2.',
          hint3: 'c = 3.',
          answer: 3, tolerance: 0, unit: '',
          explanation: '1 = −2 + c → c = 3.',
        },
        {
          prompt: 'Write the equation of the perpendicular line.',
          hint1: 'y = (−1/2)x + c with c = 3.',
          hint2: 'y = −½x + 3.',
          hint3: 'y = −½x + 3.',
          answer: 0, tolerance: 0, unit: '',
          explanation: 'Equation: y = −½x + 3. Verify (4,1): −2+3=1 ✓',
          checkType: 'skip',
          displayAnswer: 'y = −½x + 3',
        },
      ],
      workedExample: {
        question: 'Find the equation of the line perpendicular to y = 3x + 1 through (3, 2).',
        steps: [
          'Gradient of given line = 3. Perpendicular gradient = −1/3.',
          'Sub (3, 2): 2 = (−1/3)(3) + c = −1 + c → c = 3.',
          'Equation: <strong>y = −⅓x + 3</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: 'y = −½x + 3',
        grade6: 'Gradient = 2. Perpendicular gradient = −1/2. Sub (4,1): c = 3. Equation: y = −½x + 3.',
        grade8: 'm = 2, m⊥ = −1/2. Sub (4,1): 1 = −2+c → c=3. Perpendicular line: y=−½x+3. Verify: −2+3=1 ✓',
      },
      examinerTip: 'Perpendicular gradient = −1/m. If m = 2, perpendicular gradient = −1/2. The product of perpendicular gradients is always −1.',
      auditStatus: 'pending',
    },
    {
      id: 'gph-C03', subtopic: 'alg-graphs', band: 'C', marks: 4,
      question: 'A straight line passes through A(2, 1) and B(6, 9). Find the equation of the line, then find where it meets y = −x + 12.',
      steps: [
        {
          prompt: 'Find the gradient of AB.',
          hint1: 'm = (9 − 1)/(6 − 2) = 8/4.',
          hint2: 'm = 2.',
          hint3: 'm = 2.',
          answer: 2, tolerance: 0, unit: '',
          explanation: 'm = (9−1)/(6−2) = 8/4 = 2.',
        },
        {
          prompt: 'Substitute m = 2 and A(2, 1) to find c.',
          hint1: '1 = 2(2) + c → c = 1 − 4.',
          hint2: 'c = −3.',
          hint3: 'c = −3.',
          answer: -3, tolerance: 0, unit: '',
          explanation: '1 = 4 + c → c = −3. Equation: y = 2x − 3.',
        },
        {
          prompt: 'Find the intersection with y = −x + 12. Set 2x − 3 = −x + 12 and solve.',
          hint1: '2x + x = 12 + 3 → 3x = 15.',
          hint2: 'x = 5.',
          hint3: '3x = 15 → x = 5.',
          answer: 5, tolerance: 0, unit: '',
          explanation: '3x = 15 → x = 5.',
        },
        {
          prompt: 'Calculate y by substituting x = 5 into y = −x + 12.',
          hint1: 'y = −5 + 12.',
          hint2: 'y = 7.',
          hint3: 'y = 7.',
          answer: 7, tolerance: 0, unit: '',
          explanation: 'y = −5 + 12 = 7. Intersection at (5, 7).',
          displayAnswer: 'Intersection: (5, 7)',
        },
      ],
      workedExample: {
        question: 'Line through (1, 2) and (4, 8). Where does it meet y = −x + 9?',
        steps: [
          'm = (8−2)/(4−1) = 2. Sub (1,2): 2=2+c → c=0. Equation: y=2x.',
          'Set 2x = −x + 9 → 3x = 9 → x = 3.',
          'y = −3+9 = 6. Intersection: <strong>(3, 6)</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: 'y = 2x − 3, intersection at (5, 7)',
        grade6: 'm=2, c=−3, so y=2x−3. Set equal: 3x=15 → x=5, y=7. Intersection (5, 7).',
        grade8: 'm=2. y=2x−3. Intersection: 2x−3=−x+12 → 3x=15 → x=5, y=7. Point (5,7). Verify in y=−x+12: −5+12=7 ✓',
      },
      examinerTip: 'Two-part questions: find the equation first, then use it in the second part. A clear working structure gains more marks.',
      auditStatus: 'pending',
    },
    {
      id: 'gph-C04', subtopic: 'alg-graphs', band: 'C', marks: 4,
      question: 'A(−1, 2), B(5, 10). Find the length of AB, the midpoint of AB, and the gradient of AB.',
      steps: [
        {
          prompt: 'Calculate d² using Pythagoras: d² = (x₂ − x₁)² + (y₂ − y₁)².',
          hint1: 'dx = 5−(−1) = 6. dy = 10−2 = 8.',
          hint2: 'd² = 6² + 8² = 36 + 64.',
          hint3: 'd² = 100.',
          answer: 100, tolerance: 0, unit: '',
          explanation: 'd² = 6² + 8² = 36 + 64 = 100.',
        },
        {
          prompt: 'Calculate the length AB = √d².',
          hint1: '√100 = ?',
          hint2: '√100 = 10.',
          hint3: 'AB = 10 units.',
          answer: 10, tolerance: 0, unit: '',
          explanation: 'AB = √100 = 10 units.',
        },
        {
          prompt: 'Find the x-coordinate of the midpoint of AB.',
          hint1: 'xₘ = (−1 + 5)/2.',
          hint2: '4/2 = 2.',
          hint3: 'xₘ = 2.',
          answer: 2, tolerance: 0, unit: '',
          explanation: 'xₘ = (−1+5)/2 = 2.',
        },
        {
          prompt: 'Find the y-coordinate of the midpoint, then calculate the gradient of AB.',
          hint1: 'yₘ = (2+10)/2 = 6. Gradient = dy/dx = 8/6.',
          hint2: '8/6 = 4/3 ≈ 1.33.',
          hint3: 'Midpoint (2, 6), gradient ≈ 1.33.',
          answer: 1.33, tolerance: 0.02, unit: '',
          explanation: 'yₘ=6. Midpoint (2, 6). Gradient = 8/6 = 4/3 ≈ 1.33.',
          displayAnswer: 'Midpoint (2, 6); gradient = 4/3',
        },
      ],
      workedExample: {
        question: 'P(0, 0) and Q(3, 4). Find PQ, midpoint, and gradient.',
        steps: [
          'd² = 3² + 4² = 9 + 16 = 25. PQ = 5.',
          'Midpoint = (1.5, 2).',
          'Gradient = (4−0)/(3−0) = 4/3.',
        ],
      },
      sampleAnswer: {
        grade4: 'Length = 10, midpoint = (2, 6), gradient = 4/3',
        grade6: 'd² = 36+64=100, AB=10. Midpoint (2,6). Gradient=8/6=4/3.',
        grade8: 'dx=6, dy=8. d=√100=10. Midpoint ((−1+5)/2, (2+10)/2)=(2,6). m=8/6=4/3≈1.33. (3,4,5 scaled by 2.)',
      },
      examinerTip: 'Distance formula is Pythagoras applied to coordinate differences. Midpoint is just averaging x and y separately. All three are linked by the same pair of points.',
      auditStatus: 'pending',
    },
"""

with open(FILE, encoding='utf-8') as f:
    content = f.read()

pos = content.find(MARKER)
if pos < 0:
    print('MARKER NOT FOUND')
else:
    print(f'Inserting at char {pos}')
    with open(FILE, 'w', encoding='utf-8') as f:
        f.write(content[:pos] + NEW + content[pos:])
    print('Done - batch 3 (12 gph questions)')
