FILE = r'C:\Users\jason\OneDrive\Documents\GitHub\mabel-gcse\js\maths-questions.js'
MARKER = "    {\n      id: 'pro-A01'"

NEW = """    {
      id: 'quad-A01', subtopic: 'alg-quadratics', band: 'A', marks: 2,
      question: 'Solve x² − x − 6 = 0 by factorising.',
      steps: [
        {
          prompt: 'Factorise: find two numbers multiplying to −6 and adding to −1. State the larger root.',
          hint1: '3 × (−2) = −6 and 3 + (−2) = 1. But coefficient of x is −1: try (x − 3)(x + 2) = 0.',
          hint2: 'x − 3 = 0 → x = 3.',
          hint3: 'x = 3.',
          answer: 3, tolerance: 0, unit: '',
          explanation: '(x − 3)(x + 2) = 0 → x = 3.',
        },
        {
          prompt: 'State the smaller root.',
          hint1: 'x + 2 = 0 → x = ?',
          hint2: 'x = −2.',
          hint3: '−2.',
          answer: -2, tolerance: 0, unit: '',
          explanation: 'x = −2. Solutions: x = 3 or x = −2.',
          displayAnswer: 'x = 3 or x = −2',
        },
      ],
      workedExample: {
        question: 'Solve x² − 2x − 8 = 0.',
        steps: [
          'Find numbers: −4 × 2 = −8, −4 + 2 = −2. ✓',
          '(x − 4)(x + 2) = 0.',
          'x = <strong>4</strong> or x = <strong>−2</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: 'x = 3 or x = −2',
        grade6: '(x−3)(x+2) = 0. x=3 or x=−2.',
        grade8: 'Factorising x²−x−6: need pair multiplying to −6, adding to −1 → 2 and −3. (x+2)(x−3)=0. x=−2 or x=3.',
      },
      examinerTip: 'Find two numbers whose product = constant term (c) and whose sum = middle coefficient (b). Signs matter — be systematic.',
      auditStatus: 'pending',
    },
    {
      id: 'quad-A02', subtopic: 'alg-quadratics', band: 'A', marks: 2,
      question: 'Solve x² − 16 = 0.',
      steps: [
        {
          prompt: 'Rearrange: x² = 16. What is the positive square root of 16?',
          hint1: '√16 = ?',
          hint2: '√16 = 4.',
          hint3: '4.',
          answer: 4, tolerance: 0, unit: '',
          explanation: 'x² = 16 → x = ±4.',
        },
        {
          prompt: 'State the negative root.',
          hint1: 'x = −√16.',
          hint2: 'x = −4.',
          hint3: '−4.',
          answer: -4, tolerance: 0, unit: '',
          explanation: 'x = −4. Solutions: x = 4 or x = −4.',
          displayAnswer: 'x = ±4',
        },
      ],
      workedExample: {
        question: 'Solve x² − 25 = 0.',
        steps: [
          'x² = 25.',
          'x = ±√25.',
          'x = <strong>5</strong> or x = <strong>−5</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: 'x = 4 or x = −4',
        grade6: 'x² = 16 → x = ±4.',
        grade8: 'x²−16=0 is a difference of two squares: (x−4)(x+4)=0. Solutions: x=4 or x=−4.',
      },
      examinerTip: 'When there is no x term, rearrange to x² = k and take the square root — giving two solutions: +√k and −√k. Do not forget the negative root.',
      auditStatus: 'pending',
    },
    {
      id: 'quad-A03', subtopic: 'alg-quadratics', band: 'A', marks: 3,
      question: 'Solve x² + 3x − 10 = 0 by factorising.',
      steps: [
        {
          prompt: 'Find two numbers that multiply to −10 and add to 3.',
          hint1: '5 × (−2) = −10 and 5 + (−2) = 3.',
          hint2: '(x + 5)(x − 2) = 0.',
          hint3: '(x + 5)(x − 2) = 0.',
          answer: 0, tolerance: 0, unit: '',
          explanation: '(x + 5)(x − 2) = 0.',
          checkType: 'skip',
          displayAnswer: '(x + 5)(x − 2) = 0',
        },
        {
          prompt: 'State the positive root.',
          hint1: 'x − 2 = 0 → x = ?',
          hint2: 'x = 2.',
          hint3: '2.',
          answer: 2, tolerance: 0, unit: '',
          explanation: 'x = 2.',
        },
        {
          prompt: 'State the negative root.',
          hint1: 'x + 5 = 0 → x = ?',
          hint2: 'x = −5.',
          hint3: '−5.',
          answer: -5, tolerance: 0, unit: '',
          explanation: 'x = −5. Solutions: x = 2 or x = −5.',
          displayAnswer: 'x = 2 or x = −5',
        },
      ],
      workedExample: {
        question: 'Solve x² + 4x − 12 = 0.',
        steps: [
          'Need: × = −12, + = 4 → 6 and −2.',
          '(x + 6)(x − 2) = 0.',
          'x = <strong>−6</strong> or x = <strong>2</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: 'x = 2 or x = −5',
        grade6: '(x+5)(x−2)=0 → x=−5 or x=2.',
        grade8: 'Factors of −10 summing to 3: 5 and −2. (x+5)(x−2)=0. Roots x=−5 and x=2.',
      },
      examinerTip: 'For x² + bx + c: find factors of c that add to b. List factor pairs systematically (include negatives) to avoid missing the answer.',
      auditStatus: 'pending',
    },
    {
      id: 'quad-A04', subtopic: 'alg-quadratics', band: 'A', marks: 2,
      question: 'Expand (x + 3)². State the coefficient of x and the constant term.',
      steps: [
        {
          prompt: '(x + 3)² = x² + 2(3)x + 9. What is the coefficient of x?',
          hint1: '2 × 3 = ?',
          hint2: '6.',
          hint3: 'Coefficient of x = 6.',
          answer: 6, tolerance: 0, unit: '',
          explanation: '(x+3)² = x²+6x+9. Coefficient of x = 6.',
        },
        {
          prompt: 'What is the constant term?',
          hint1: '3² = ?',
          hint2: '9.',
          hint3: 'Constant = 9.',
          answer: 9, tolerance: 0, unit: '',
          explanation: 'Constant term = 3² = 9.',
          displayAnswer: 'x² + 6x + 9',
        },
      ],
      workedExample: {
        question: 'Expand (x + 5)².',
        steps: [
          '(x+5)² = x² + 2(5)x + 5².',
          '= x² + 10x + 25.',
          'Coefficient of x = 10, constant = 25.',
        ],
      },
      sampleAnswer: {
        grade4: 'x² + 6x + 9',
        grade6: '(x+3)² = x²+6x+9. Coefficient of x = 6, constant = 9.',
        grade8: '(x+a)² = x²+2ax+a². Here a=3: x²+6x+9. The middle coefficient is always 2a.',
      },
      examinerTip: '(x + a)² = x² + 2ax + a². The middle coefficient is twice the number in the bracket. Squaring only the bracket number is a very common error.',
      auditStatus: 'pending',
    },
    {
      id: 'quad-A05', subtopic: 'alg-quadratics', band: 'A', marks: 3,
      question: 'Solve x² − 7x + 12 = 0 by factorising.',
      steps: [
        {
          prompt: 'Find two numbers that multiply to 12 and add to −7.',
          hint1: '−3 × (−4) = 12 and −3 + (−4) = −7.',
          hint2: '(x − 3)(x − 4) = 0.',
          hint3: '(x − 3)(x − 4) = 0.',
          answer: 0, tolerance: 0, unit: '',
          explanation: '(x − 3)(x − 4) = 0.',
          checkType: 'skip',
          displayAnswer: '(x − 3)(x − 4) = 0',
        },
        {
          prompt: 'Find the smaller root.',
          hint1: 'x − 3 = 0 → x = ?',
          hint2: 'x = 3.',
          hint3: '3.',
          answer: 3, tolerance: 0, unit: '',
          explanation: 'x = 3.',
        },
        {
          prompt: 'Find the larger root.',
          hint1: 'x − 4 = 0 → x = ?',
          hint2: 'x = 4.',
          hint3: '4.',
          answer: 4, tolerance: 0, unit: '',
          explanation: 'x = 4. Solutions: x = 3 or x = 4.',
          displayAnswer: 'x = 3 or x = 4',
        },
      ],
      workedExample: {
        question: 'Solve x² − 9x + 20 = 0.',
        steps: [
          '−4 × (−5) = 20, −4 + (−5) = −9.',
          '(x − 4)(x − 5) = 0.',
          'x = <strong>4</strong> or x = <strong>5</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: 'x = 3 or x = 4',
        grade6: '(x−3)(x−4)=0 → x=3 or x=4.',
        grade8: 'Both numbers negative (product +12, sum −7): −3 and −4. (x−3)(x−4)=0. Check: 3²−21+12=0 ✓',
      },
      examinerTip: 'When both factors are negative (product positive, sum negative), both roots will be positive. This is a common pattern in GCSE factorising.',
      auditStatus: 'pending',
    },
    {
      id: 'quad-B01', subtopic: 'alg-quadratics', band: 'B', marks: 3,
      question: 'Solve x² + 6x + 8 = 0 by completing the square.',
      steps: [
        {
          prompt: 'Complete the square: (x + 3)² = x² + 6x + 9. Rewrite the equation as (x + 3)² − ? = 0.',
          hint1: '(x + 3)² − 9 + 8 = 0.',
          hint2: '(x + 3)² − 1 = 0.',
          hint3: '1.',
          answer: 1, tolerance: 0, unit: '',
          explanation: '(x+3)² − 1 = 0.',
        },
        {
          prompt: 'Solve: (x + 3)² = 1 → x + 3 = ±1. Find the larger root.',
          hint1: 'x + 3 = +1 → x = ?',
          hint2: 'x = −2.',
          hint3: '−2.',
          answer: -2, tolerance: 0, unit: '',
          explanation: 'x = 1 − 3 = −2.',
        },
        {
          prompt: 'Find the smaller root.',
          hint1: 'x + 3 = −1 → x = ?',
          hint2: 'x = −4.',
          hint3: '−4.',
          answer: -4, tolerance: 0, unit: '',
          explanation: 'x = −1 − 3 = −4. Solutions: x = −2 or x = −4.',
          displayAnswer: 'x = −2 or x = −4',
        },
      ],
      workedExample: {
        question: 'Solve x² + 4x + 3 = 0 by completing the square.',
        steps: [
          '(x + 2)² − 4 + 3 = 0 → (x+2)² = 1.',
          'x + 2 = ±1.',
          'x = <strong>−1</strong> or x = <strong>−3</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: 'x = −2 or x = −4',
        grade6: '(x+3)²−1=0 → (x+3)²=1 → x=−2 or x=−4.',
        grade8: '(x+3)²=1 → x+3=±1 → x=−2 or x=−4. Alternative: factorise (x+2)(x+4)=0 gives same answers.',
      },
      examinerTip: 'Completing the square: half the x-coefficient goes inside the bracket. Subtract the square of that number to compensate. Then rearrange to solve.',
      auditStatus: 'pending',
    },
    {
      id: 'quad-B02', subtopic: 'alg-quadratics', band: 'B', marks: 4,
      question: 'Use the quadratic formula to solve 2x² + 5x − 3 = 0.',
      steps: [
        {
          prompt: 'Calculate the discriminant: b² − 4ac where a=2, b=5, c=−3.',
          hint1: '5² − 4(2)(−3) = 25 + 24.',
          hint2: '= 49.',
          hint3: '49.',
          answer: 49, tolerance: 0, unit: '',
          explanation: 'Discriminant = 25 + 24 = 49.',
        },
        {
          prompt: '√49 = ?',
          hint1: '√49 = 7.',
          hint2: '7.',
          hint3: '7.',
          answer: 7, tolerance: 0, unit: '',
          explanation: '√49 = 7.',
        },
        {
          prompt: 'Find the larger root: x = (−5 + 7)/(2×2).',
          hint1: '(−5 + 7)/4 = 2/4.',
          hint2: '= 0.5.',
          hint3: '0.5.',
          answer: 0.5, tolerance: 0.01, unit: '',
          explanation: 'x = (−5+7)/4 = 2/4 = 0.5.',
        },
        {
          prompt: 'Find the smaller root: x = (−5 − 7)/(2×2).',
          hint1: '(−5 − 7)/4 = −12/4.',
          hint2: '= −3.',
          hint3: '−3.',
          answer: -3, tolerance: 0, unit: '',
          explanation: 'x = −12/4 = −3. Solutions: x = 0.5 or x = −3.',
          displayAnswer: 'x = 0.5 or x = −3',
        },
      ],
      workedExample: {
        question: 'Solve 3x² − 10x + 3 = 0 using the formula.',
        steps: [
          'Discriminant = 100 − 36 = 64. √64 = 8.',
          'x = (10+8)/6 = 3 or x = (10−8)/6 = 1/3.',
          'Solutions: <strong>x = 3 or x = 1/3</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: 'x = 0.5 or x = −3',
        grade6: 'Discriminant = 49. x = (−5±7)/4. x=0.5 or x=−3.',
        grade8: 'x = (−b±√(b²−4ac))/(2a). a=2, b=5, c=−3. D=49, √D=7. x=0.5 or x=−3. Verify: 2(0.25)+2.5−3=0 ✓',
      },
      examinerTip: 'Always calculate the discriminant first. If it is a perfect square, the roots will be rational (exact). If not, give answers as surds or decimals.',
      auditStatus: 'pending',
    },
    {
      id: 'quad-B03', subtopic: 'alg-quadratics', band: 'B', marks: 4,
      question: 'Solve x² + 4x − 7 = 0 by completing the square. Give answers correct to 2 decimal places.',
      steps: [
        {
          prompt: 'Complete the square: (x + 2)² − 4 − 7 = 0 → (x + 2)² = 11. What number is inside the bracket?',
          hint1: 'Half of 4 = 2.',
          hint2: '(x + 2)² = 11.',
          hint3: '2.',
          answer: 2, tolerance: 0, unit: '',
          explanation: '(x+2)² = 4+7 = 11.',
        },
        {
          prompt: 'Calculate √11 to 2 decimal places.',
          hint1: '√11 ≈ 3.3.',
          hint2: '√11 ≈ 3.32.',
          hint3: '3.32.',
          answer: 3.32, tolerance: 0.01, unit: '',
          explanation: '√11 ≈ 3.3166 ≈ 3.32.',
        },
        {
          prompt: 'Larger root: x = −2 + √11 ≈ ?',
          hint1: '−2 + 3.32 = ?',
          hint2: '1.32.',
          hint3: '1.32.',
          answer: 1.32, tolerance: 0.02, unit: '',
          explanation: 'x ≈ −2 + 3.32 = 1.32.',
        },
        {
          prompt: 'Smaller root: x = −2 − √11 ≈ ?',
          hint1: '−2 − 3.32 = ?',
          hint2: '−5.32.',
          hint3: '−5.32.',
          answer: -5.32, tolerance: 0.02, unit: '',
          explanation: 'x ≈ −2 − 3.32 = −5.32. Solutions: x ≈ 1.32 or x ≈ −5.32.',
          displayAnswer: 'x ≈ 1.32 or x ≈ −5.32',
        },
      ],
      workedExample: {
        question: 'Solve x² + 6x − 2 = 0 by completing the square. Give answers to 2dp.',
        steps: [
          '(x + 3)² − 9 − 2 = 0 → (x+3)² = 11.',
          '√11 ≈ 3.32.',
          'x ≈ −3 + 3.32 = <strong>0.32</strong> or x ≈ −3 − 3.32 = <strong>−6.32</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: 'x ≈ 1.32 or x ≈ −5.32',
        grade6: '(x+2)²=11. x = −2 ± √11 ≈ 1.32 or −5.32.',
        grade8: 'Complete square: (x+2)²=11 → x=−2±√11. √11≈3.3166. x≈1.32 or x≈−5.32 (2dp).',
      },
      examinerTip: 'Completing the square gives exact form x = −p ± √q. Always give BOTH roots. Check your answer by substituting back.',
      auditStatus: 'pending',
    },
    {
      id: 'quad-B04', subtopic: 'alg-quadratics', band: 'B', marks: 4,
      question: 'A rectangle has length (x + 6) cm and width (x − 1) cm. Its area is 30 cm². Find x and the dimensions.',
      steps: [
        {
          prompt: 'Form the equation: (x+6)(x−1) = 30. Expand and rearrange to ax²+bx+c = 0.',
          hint1: 'x² + 5x − 6 = 30 → x² + 5x − 36 = 0.',
          hint2: '(x + 9)(x − 4) = 0.',
          hint3: 'x² + 5x − 36 = 0.',
          answer: 0, tolerance: 0, unit: '',
          explanation: 'x²+5x−36=0 → (x+9)(x−4)=0.',
          checkType: 'skip',
          displayAnswer: 'x² + 5x − 36 = 0',
        },
        {
          prompt: 'Solve: (x + 9)(x − 4) = 0. The positive value of x = ?',
          hint1: 'x = 4 or x = −9 (reject negative).',
          hint2: 'x = 4.',
          hint3: '4.',
          answer: 4, tolerance: 0, unit: '',
          explanation: 'x = 4 (positive, since dimensions must be positive).',
        },
        {
          prompt: 'Find the length: x + 6.',
          hint1: '4 + 6 = ?',
          hint2: '10.',
          hint3: '10.',
          answer: 10, tolerance: 0, unit: '',
          explanation: 'Length = 10 cm.',
        },
        {
          prompt: 'Find the width: x − 1.',
          hint1: '4 − 1 = ?',
          hint2: '3.',
          hint3: '3.',
          answer: 3, tolerance: 0, unit: '',
          explanation: 'Width = 3 cm. Check: 10 × 3 = 30 ✓',
          displayAnswer: 'Length = 10 cm, width = 3 cm',
        },
      ],
      workedExample: {
        question: '(x+5)(x+2) = 60. Find x and dimensions.',
        steps: [
          'x²+7x+10=60 → x²+7x−50=0.',
          '(x+?)(x−?) — check: discriminant = 49+200=249. Not a perfect square — adjust: use (x+5)(x−2)=60: x²+3x−10=60 → x²+3x−70=0. (x+10)(x−7)=0 → x=7.',
          'Length=12, width=5. Check: 60 ✓',
        ],
      },
      sampleAnswer: {
        grade4: 'x = 4, length = 10 cm, width = 3 cm',
        grade6: '(x+6)(x−1)=30 → x²+5x−36=0 → (x+9)(x−4)=0 → x=4. L=10, W=3.',
        grade8: 'x=4 (reject x=−9: gives negative width). 10×3=30 ✓. Dimensions: 10 cm by 3 cm.',
      },
      examinerTip: 'Reject negative values of x if they lead to negative dimensions. Always check by computing the area with your final dimensions.',
      auditStatus: 'pending',
    },
    {
      id: 'quad-B05', subtopic: 'alg-quadratics', band: 'B', marks: 4,
      question: 'Write x² + 8x + 3 in the form (x + a)² + b. State the minimum value and the x-value at which it occurs.',
      steps: [
        {
          prompt: 'Find a: a = half of 8.',
          hint1: 'a = 8/2.',
          hint2: 'a = 4.',
          hint3: '4.',
          answer: 4, tolerance: 0, unit: '',
          explanation: 'a = 4. (x+4)² = x²+8x+16.',
        },
        {
          prompt: 'Find b: (x+4)² − 16 + 3. What is b?',
          hint1: 'b = 3 − 16.',
          hint2: 'b = −13.',
          hint3: '−13.',
          answer: -13, tolerance: 0, unit: '',
          explanation: 'b = 3 − 4² = 3 − 16 = −13.',
        },
        {
          prompt: 'The minimum value of the expression is b (since (x+4)² ≥ 0). What is the minimum?',
          hint1: 'Minimum = b = −13.',
          hint2: '−13.',
          hint3: '−13.',
          answer: -13, tolerance: 0, unit: '',
          explanation: 'Minimum value = −13, when (x+4)² = 0.',
        },
        {
          prompt: 'At what value of x does the minimum occur?',
          hint1: '(x + 4)² = 0 → x + 4 = 0.',
          hint2: 'x = −4.',
          hint3: '−4.',
          answer: -4, tolerance: 0, unit: '',
          explanation: 'x = −4. Minimum at (−4, −13).',
          displayAnswer: 'Minimum = −13 at x = −4',
        },
      ],
      workedExample: {
        question: 'Write x² + 10x + 7 in completed square form. State minimum.',
        steps: [
          'a = 5. b = 7 − 25 = −18.',
          '(x+5)² − 18.',
          'Minimum = −18 at x = −5.',
        ],
      },
      sampleAnswer: {
        grade4: '(x+4)² − 13; minimum = −13 at x = −4',
        grade6: 'a=4, b=3−16=−13. Form: (x+4)²−13. Min = −13 when x = −4.',
        grade8: '(x+4)²−13. Since (x+4)²≥0, min occurs when (x+4)²=0 → x=−4, min value=−13.',
      },
      examinerTip: 'For (x+a)²+b: minimum value = b (for positive x² coefficient). It occurs when x = −a (not +a). Squaring can never give a negative result.',
      auditStatus: 'pending',
    },
    {
      id: 'quad-B06', subtopic: 'alg-quadratics', band: 'B', marks: 4,
      question: 'Use the quadratic formula to solve 3x² − 7x + 2 = 0.',
      steps: [
        {
          prompt: 'Calculate the discriminant: b² − 4ac where a=3, b=−7, c=2.',
          hint1: '(−7)² − 4(3)(2) = 49 − 24.',
          hint2: '= 25.',
          hint3: '25.',
          answer: 25, tolerance: 0, unit: '',
          explanation: 'Discriminant = 49 − 24 = 25.',
        },
        {
          prompt: '√25 = ?',
          hint1: '√25 = 5.',
          hint2: '5.',
          hint3: '5.',
          answer: 5, tolerance: 0, unit: '',
          explanation: '√25 = 5.',
        },
        {
          prompt: 'Find the larger root: x = (7 + 5)/(2×3).',
          hint1: '12/6 = ?',
          hint2: '2.',
          hint3: '2.',
          answer: 2, tolerance: 0, unit: '',
          explanation: 'x = 12/6 = 2.',
        },
        {
          prompt: 'Find the smaller root: x = (7 − 5)/(2×3).',
          hint1: '2/6 = ?',
          hint2: '1/3 ≈ 0.33.',
          hint3: '0.33.',
          answer: 0.333, tolerance: 0.01, unit: '',
          explanation: 'x = 2/6 = 1/3 ≈ 0.333. Solutions: x = 2 or x = 1/3.',
          displayAnswer: 'x = 2 or x = 1/3',
        },
      ],
      workedExample: {
        question: 'Solve 2x² − 7x + 6 = 0.',
        steps: [
          'Discriminant = 49 − 48 = 1. √1 = 1.',
          'x = (7+1)/4 = 2 or x = (7−1)/4 = 1.5.',
          'Solutions: <strong>x = 2 or x = 1.5</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: 'x = 2 or x = 1/3',
        grade6: 'Discriminant=25. x=(7±5)/6. x=2 or x=1/3.',
        grade8: 'D=25 (perfect square → rational roots). x=(7+5)/6=2 or x=(7−5)/6=1/3. Verify: 3(4)−14+2=0 ✓',
      },
      examinerTip: 'Note b = −7, so −b = +7. Take care with signs in the formula: x = (−b ± √D)/(2a). Write out −b = 7 explicitly to avoid sign errors.',
      auditStatus: 'pending',
    },
    {
      id: 'quad-C01', subtopic: 'alg-quadratics', band: 'C', marks: 4,
      question: 'Show that x² + 6x + 10 has no real roots. State the minimum value.',
      steps: [
        {
          prompt: 'Calculate the discriminant for x² + 6x + 10 = 0: b² − 4ac.',
          hint1: 'a=1, b=6, c=10. 6² − 4(1)(10).',
          hint2: '36 − 40.',
          hint3: '−4.',
          answer: -4, tolerance: 0, unit: '',
          explanation: 'Discriminant = 36 − 40 = −4 < 0.',
        },
        {
          prompt: 'Since discriminant < 0, there are no real roots. Complete the square to find the minimum.',
          hint1: '(x + 3)² − 9 + 10.',
          hint2: '(x + 3)² + 1.',
          hint3: 'Minimum = 1.',
          answer: 0, tolerance: 0, unit: '',
          explanation: '(x+3)² + 1. Minimum = 1.',
          checkType: 'skip',
          displayAnswer: '(x+3)² + 1',
        },
        {
          prompt: 'What is the minimum value of x² + 6x + 10?',
          hint1: '(x+3)² ≥ 0, so minimum = 1.',
          hint2: '1.',
          hint3: '1.',
          answer: 1, tolerance: 0, unit: '',
          explanation: 'Minimum = 1 (when x = −3).',
        },
        {
          prompt: 'Since the minimum is positive, confirm the expression is always positive. At x = −3, value = ?',
          hint1: '(−3)² + 6(−3) + 10 = 9 − 18 + 10.',
          hint2: '1.',
          hint3: '1.',
          answer: 1, tolerance: 0, unit: '',
          explanation: 'At x=−3: 9−18+10=1 > 0. Expression always positive → no real roots.',
          displayAnswer: 'No real roots; minimum = 1',
        },
      ],
      workedExample: {
        question: 'Show x² + 4x + 7 has no real roots.',
        steps: [
          'Discriminant = 16 − 28 = −12 < 0 → no real roots.',
          '(x+2)² + 3.',
          'Minimum = 3 > 0. Expression always positive.',
        ],
      },
      sampleAnswer: {
        grade4: 'Discriminant = −4 < 0, so no real roots. Minimum = 1.',
        grade6: 'D = 36−40 = −4 < 0 → no real roots. (x+3)²+1 → minimum = 1.',
        grade8: 'D=−4<0 (no real roots). Completed square form: (x+3)²+1 ≥ 1 > 0 for all real x. Expression is always positive.',
      },
      examinerTip: 'Two methods: (1) discriminant < 0 → no real roots. (2) Completing the square shows minimum > 0. For a "show" or "prove" question, use method 2 — it shows both facts at once.',
      auditStatus: 'pending',
    },
    {
      id: 'quad-C02', subtopic: 'alg-quadratics', band: 'C', marks: 4,
      question: 'Use the quadratic formula to solve x² − 5x + 5 = 0. Give answers correct to 2 decimal places.',
      steps: [
        {
          prompt: 'Calculate the discriminant: b² − 4ac where a=1, b=−5, c=5.',
          hint1: '(−5)² − 4(1)(5) = 25 − 20.',
          hint2: '= 5.',
          hint3: '5.',
          answer: 5, tolerance: 0, unit: '',
          explanation: 'Discriminant = 5.',
        },
        {
          prompt: '√5 ≈ ? (to 2 dp)',
          hint1: '√5 ≈ 2.2.',
          hint2: '≈ 2.24.',
          hint3: '2.24.',
          answer: 2.24, tolerance: 0.01, unit: '',
          explanation: '√5 ≈ 2.2361 ≈ 2.24.',
        },
        {
          prompt: 'Larger root: x = (5 + √5)/2 ≈ ?',
          hint1: '(5 + 2.24)/2 = 7.24/2.',
          hint2: '≈ 3.62.',
          hint3: '3.62.',
          answer: 3.62, tolerance: 0.02, unit: '',
          explanation: 'x ≈ (5+2.24)/2 = 3.62.',
        },
        {
          prompt: 'Smaller root: x = (5 − √5)/2 ≈ ?',
          hint1: '(5 − 2.24)/2 = 2.76/2.',
          hint2: '≈ 1.38.',
          hint3: '1.38.',
          answer: 1.38, tolerance: 0.02, unit: '',
          explanation: 'x ≈ 1.38. Solutions: x ≈ 3.62 or x ≈ 1.38.',
          displayAnswer: 'x ≈ 3.62 or x ≈ 1.38',
        },
      ],
      workedExample: {
        question: 'Solve x² − 7x + 8 = 0 to 2dp.',
        steps: [
          'D = 49 − 32 = 17. √17 ≈ 4.12.',
          'x = (7+4.12)/2 ≈ 5.56 or x = (7−4.12)/2 ≈ 1.44.',
          'Solutions: <strong>x ≈ 5.56 or x ≈ 1.44</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: 'x ≈ 3.62 or x ≈ 1.38',
        grade6: 'D=5. x=(5±√5)/2. √5≈2.24. x≈3.62 or x≈1.38.',
        grade8: 'D=5 (not a perfect square). x=(5±√5)/2. x₁≈3.618, x₂≈1.382. To 2dp: x≈3.62 or x≈1.38.',
      },
      examinerTip: 'Non-perfect-square discriminant → irrational roots. Use calculator for √D. Give answers to the precision stated (here: 2dp). Show all formula substitution for method marks.',
      auditStatus: 'pending',
    },
    {
      id: 'quad-C03', subtopic: 'alg-quadratics', band: 'C', marks: 5,
      question: 'A ball is thrown upward. Its height in metres is h = −5t² + 20t + 2, where t is time in seconds. Find the times when h = 17 and the maximum height.',
      steps: [
        {
          prompt: 'Set h = 17: −5t² + 20t + 2 = 17 → rearrange to standard form.',
          hint1: '−5t² + 20t − 15 = 0 → t² − 4t + 3 = 0.',
          hint2: '(t − 1)(t − 3) = 0.',
          hint3: 't² − 4t + 3 = 0.',
          answer: 0, tolerance: 0, unit: '',
          explanation: 't²−4t+3=0 → (t−1)(t−3)=0.',
          checkType: 'skip',
          displayAnswer: 't² − 4t + 3 = 0',
        },
        {
          prompt: 'Find the first time t when h = 17.',
          hint1: 't − 1 = 0 → t = 1.',
          hint2: '1.',
          hint3: 't = 1 s.',
          answer: 1, tolerance: 0, unit: '',
          explanation: 't = 1 second.',
        },
        {
          prompt: 'Find the second time t when h = 17.',
          hint1: 't − 3 = 0 → t = 3.',
          hint2: '3.',
          hint3: 't = 3 s.',
          answer: 3, tolerance: 0, unit: '',
          explanation: 't = 3 seconds.',
        },
        {
          prompt: 'Maximum height occurs at t = (1 + 3)/2 = 2 s (by symmetry). Calculate h at t = 2.',
          hint1: 'h = −5(4) + 20(2) + 2.',
          hint2: 'h = −20 + 40 + 2.',
          hint3: 'h = 22.',
          answer: 22, tolerance: 0, unit: '',
          explanation: 'h = −20+40+2 = 22 m.',
        },
        {
          prompt: 'Verify: at t = 2, h = 22. This is the maximum. What is the maximum height?',
          hint1: '22 metres.',
          hint2: '22.',
          hint3: '22.',
          answer: 22, tolerance: 0, unit: '',
          explanation: 'Maximum height = 22 m at t = 2 s.',
          displayAnswer: 'h = 17 at t=1s and t=3s; max h = 22m at t=2s',
        },
      ],
      workedExample: {
        question: 'h = −t² + 6t. Find when h = 5 and the maximum height.',
        steps: [
          '−t²+6t=5 → t²−6t+5=0 → (t−1)(t−5)=0 → t=1 or t=5.',
          'Max at t=3: h=−9+18=9.',
          'Max height = <strong>9 m</strong>.',
        ],
      },
      sampleAnswer: {
        grade4: 't = 1s and t = 3s; max height = 22m',
        grade6: 'Set h=17: t²−4t+3=0 → (t−1)(t−3)=0. t=1 and t=3. Max at t=2: h=22m.',
        grade8: 'h=17 at t=1s and t=3s (by symmetry of parabola, these are equal times before and after peak). Max at t=(1+3)/2=2s: h=22m.',
      },
      examinerTip: 'In projectile questions, the two times when h=k are symmetric about the time of maximum height. Use this symmetry to find the maximum efficiently.',
      auditStatus: 'pending',
    },
    {
      id: 'quad-C04', subtopic: 'alg-quadratics', band: 'C', marks: 4,
      question: 'Find the values of k such that x² + kx + 9 = 0 has exactly one solution (a repeated root).',
      steps: [
        {
          prompt: 'A quadratic has exactly one solution when the discriminant = 0. Write the discriminant.',
          hint1: 'Discriminant = k² − 4(1)(9).',
          hint2: 'k² − 36 = 0.',
          hint3: 'k² = 36.',
          answer: 36, tolerance: 0, unit: '',
          explanation: 'k² − 36 = 0 → k² = 36.',
        },
        {
          prompt: 'Find the positive value of k.',
          hint1: 'k = ±√36.',
          hint2: 'k = 6 or k = −6.',
          hint3: 'Positive: k = 6.',
          answer: 6, tolerance: 0, unit: '',
          explanation: 'k = 6.',
        },
        {
          prompt: 'Find the negative value of k.',
          hint1: 'k = −√36.',
          hint2: 'k = −6.',
          hint3: '−6.',
          answer: -6, tolerance: 0, unit: '',
          explanation: 'k = −6.',
        },
        {
          prompt: 'Verify: for k = 6, the equation x² + 6x + 9 = 0 gives a repeated root x = −3. Check (−3)² + 6(−3) + 9.',
          hint1: '9 − 18 + 9 = 0. ✓',
          hint2: '0.',
          hint3: '0.',
          answer: 0, tolerance: 0, unit: '',
          explanation: '(−3)² + 6(−3) + 9 = 9 − 18 + 9 = 0 ✓. Repeated root x = −3.',
          displayAnswer: 'k = 6 or k = −6',
        },
      ],
      workedExample: {
        question: 'Find k such that x² + kx + 4 = 0 has a repeated root.',
        steps: [
          'D = k² − 16 = 0.',
          'k² = 16 → k = ±4.',
          'For k=4: x²+4x+4=(x+2)²=0 → x=−2. For k=−4: (x−2)²=0 → x=2.',
        ],
      },
      sampleAnswer: {
        grade4: 'k = 6 or k = −6',
        grade6: 'D = k²−36 = 0 → k = ±6.',
        grade8: 'D=0 for repeated root: k²=36 → k=6 or k=−6. k=6: (x+3)²=0, x=−3. k=−6: (x−3)²=0, x=3.',
      },
      examinerTip: 'Discriminant = 0 ↔ exactly one (repeated) root. Set b²−4ac=0 and solve for the unknown parameter.',
      auditStatus: 'pending',
    },
"""

with open(FILE, encoding='utf-8') as f:
    content = f.read()

pos = content.find(MARKER)
if pos < 0:
    print('MARKER NOT FOUND')
else:
    print(f'Inserting at char {pos}')
    with open(FILE, 'w', encoding='utf-8') as f:
        f.write(content[:pos] + NEW + content[pos:])
    print('Done - batch 7 (15 quad questions)')
