FILE = r'C:\Users\jason\OneDrive\Documents\GitHub\mabel-gcse\js\maths-questions.js'
MARKER = "\n\n    // ══════════════════════════════════════════════════════════\n    // PROPERTIES OF SHAPES"

NEW = """    {
      id: 'ang-A03',
      subtopic: 'geo-angles',
      band: 'A',
      marks: 2,
      question: 'A triangle has angles 47°, 68° and x°. Find x.',
      steps: [
        {
          prompt: 'What do the angles of a triangle sum to?',
          hint1: 'Angles in a triangle always add to the same value.',
          hint2: '47 + 68 + x = 180.',
          hint3: '180°.',
          answer: 180,
          tolerance: 0,
          unit: '°',
          checkType: 'skip',
          displayAnswer: '47 + 68 + x = 180°',
          explanation: 'Angles in a triangle sum to 180°.',
        },
        {
          prompt: 'Find x.',
          hint1: 'x = 180 − 47 − 68.',
          hint2: '180 − 115 = ?',
          hint3: '65°.',
          answer: 65,
          tolerance: 0,
          unit: '°',
          explanation: 'x = 180 − 47 − 68 = 65°.',
        },
      ],
      workedExample: {
        question: 'A triangle has angles 53°, 72° and x°. Find x.',
        steps: ['Angles sum to 180°', 'x = 180 − 53 − 72 = <strong>55°</strong>'],
      },
      sampleAnswer: {
        grade4: 'x = 180 − 47 − 68 = 65°',
        grade6: 'Angles in a triangle sum to 180°. x = 180 − 47 − 68 = 65°.',
        grade8: 'x = 180 − (47 + 68) = 180 − 115 = 65°.',
      },
      examinerTip: 'Always state "angles in a triangle sum to 180°" as your reason.',
      auditStatus: 'pending',
    },
    {
      id: 'ang-A04',
      subtopic: 'geo-angles',
      band: 'A',
      marks: 2,
      question: 'The exterior angle of a regular polygon is 40°. How many sides does it have?',
      steps: [
        {
          prompt: 'Use the formula: number of sides = 360° ÷ exterior angle.',
          hint1: 'All exterior angles of a regular polygon sum to 360°.',
          hint2: '360 ÷ 40 = ?',
          hint3: '9 sides.',
          answer: 9,
          tolerance: 0,
          unit: 'sides',
          explanation: 'n = 360 ÷ 40 = 9 sides.',
        },
        {
          prompt: 'What is the interior angle of this polygon?',
          hint1: 'Interior + exterior = 180° (angles on a straight line).',
          hint2: '180 − 40 = ?',
          hint3: '140°.',
          answer: 140,
          tolerance: 0,
          unit: '°',
          explanation: 'Interior angle = 180 − 40 = 140°.',
        },
      ],
      workedExample: {
        question: 'Exterior angle of a regular polygon is 30°. How many sides?',
        steps: ['n = 360 ÷ 30 = <strong>12 sides</strong>', 'Interior = 180 − 30 = 150°'],
      },
      sampleAnswer: {
        grade4: 'n = 360 ÷ 40 = 9 sides.',
        grade6: 'Sum of exterior angles = 360°. n = 360 ÷ 40 = 9. Interior = 140°.',
        grade8: 'n = 360/exterior = 360/40 = 9. Interior = 180 − 40 = 140°.',
      },
      examinerTip: 'Exterior angles of any polygon sum to 360°. Interior + exterior = 180° for each angle.',
      auditStatus: 'pending',
    },
    {
      id: 'ang-A05',
      subtopic: 'geo-angles',
      band: 'A',
      marks: 2,
      question: 'Find the sum of the interior angles of an octagon.',
      steps: [
        {
          prompt: 'How many sides does an octagon have?',
          hint1: 'Oct- means 8.',
          hint2: 'n = 8.',
          hint3: '8 sides.',
          answer: 8,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'n = 8',
          explanation: 'An octagon has 8 sides.',
        },
        {
          prompt: 'Use the formula (n − 2) × 180°. Calculate the angle sum.',
          hint1: '(8 − 2) × 180 = 6 × 180.',
          hint2: '6 × 180 = ?',
          hint3: '1080°.',
          answer: 1080,
          tolerance: 0,
          unit: '°',
          explanation: '(8 − 2) × 180 = 6 × 180 = 1080°.',
        },
      ],
      workedExample: {
        question: 'Find the interior angle sum of a heptagon (7 sides).',
        steps: ['(7 − 2) × 180 = 5 × 180 = <strong>900°</strong>'],
      },
      sampleAnswer: {
        grade4: '1080°',
        grade6: '(n−2) × 180 = (8−2) × 180 = 6 × 180 = 1080°.',
        grade8: '(n−2) × 180 = 6 × 180 = 1080°.',
      },
      examinerTip: 'The formula (n−2) × 180 works for any polygon — n is the number of sides.',
      auditStatus: 'pending',
    },
    {
      id: 'ang-B02',
      subtopic: 'geo-angles',
      band: 'B',
      marks: 3,
      question: 'The angles of a triangle are (2x + 10)°, 3x° and (x + 20)°. Find x and the largest angle.',
      steps: [
        {
          prompt: 'Form an equation using the fact that angles in a triangle sum to 180°.',
          hint1: '(2x+10) + 3x + (x+20) = 180.',
          hint2: 'Simplify: 6x + 30 = 180.',
          hint3: '6x = 150.',
          answer: 150,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: '6x + 30 = 180, so 6x = 150',
          explanation: '(2x+10) + 3x + (x+20) = 6x+30 = 180, so 6x = 150.',
        },
        {
          prompt: 'Find x.',
          hint1: 'x = 150 ÷ 6.',
          hint2: '150 ÷ 6 = 25.',
          hint3: 'x = 25.',
          answer: 25,
          tolerance: 0,
          unit: '',
          explanation: 'x = 150 ÷ 6 = 25.',
        },
        {
          prompt: 'Find the largest angle.',
          hint1: 'Calculate each angle: 2(25)+10=60°, 3(25)=75°, 25+20=45°.',
          hint2: 'Largest is 3x = 3×25.',
          hint3: '75°.',
          answer: 75,
          tolerance: 0,
          unit: '°',
          explanation: 'Angles: 60°, 75°, 45°. Largest = 3×25 = 75°. Check: 60+75+45=180 ✓',
        },
      ],
      workedExample: {
        question: 'Triangle angles: (3x+5)°, (2x)°, (x−5)°. Find x and the largest angle.',
        steps: ['6x = 180, so x = 30', 'Angles: 95°, 60°, 25°. Largest = <strong>95°</strong>'],
      },
      sampleAnswer: {
        grade4: 'x = 25. Largest angle = 75°.',
        grade6: '6x+30=180, so x=25. Angles: 60°, 75°, 45°. Largest = 75°.',
        grade8: '6x+30=180. x=25. Angles 60°, 75°, 45°. Largest = 75°. Check: sum=180 ✓',
      },
      examinerTip: 'After finding x, always calculate all angles and verify they sum to 180°.',
      auditStatus: 'pending',
    },
    {
      id: 'ang-B03',
      subtopic: 'geo-angles',
      band: 'B',
      marks: 3,
      question: 'The exterior angle of a triangle is 112°. The two non-adjacent interior angles are 4y° and 3y°. Find y and both interior angles.',
      steps: [
        {
          prompt: 'Use the exterior angle theorem: exterior angle = sum of two non-adjacent interior angles.',
          hint1: '4y + 3y = 112.',
          hint2: '7y = 112.',
          hint3: 'y = 16.',
          answer: 16,
          tolerance: 0,
          unit: '',
          explanation: '7y = 112, so y = 16.',
        },
        {
          prompt: 'Find the first interior angle: 4y.',
          hint1: '4 × 16 = ?',
          hint2: '64°.',
          hint3: '64°.',
          answer: 64,
          tolerance: 0,
          unit: '°',
          explanation: '4 × 16 = 64°.',
        },
        {
          prompt: 'Find the second interior angle: 3y.',
          hint1: '3 × 16 = ?',
          hint2: '48°.',
          hint3: '48°.',
          answer: 48,
          tolerance: 0,
          unit: '°',
          explanation: '3 × 16 = 48°. Check: 64 + 48 = 112 ✓',
        },
      ],
      workedExample: {
        question: 'Exterior angle = 98°. Non-adjacent interior angles are 5y° and 2y°. Find y.',
        steps: ['7y = 98, so y = 14', 'Angles: 5×14=70° and 2×14=28°. Check: 70+28=98 ✓'],
      },
      sampleAnswer: {
        grade4: 'y=16. Angles: 64° and 48°.',
        grade6: '4y+3y=112. 7y=112. y=16. Angles: 64° and 48°.',
        grade8: 'Exterior angle theorem: 7y=112, y=16. Interior angles 64° and 48°. Check: 64+48=112 ✓',
      },
      examinerTip: 'The exterior angle equals the sum of the two non-adjacent (remote) interior angles — not the adjacent one.',
      auditStatus: 'pending',
    },
    {
      id: 'ang-B04',
      subtopic: 'geo-angles',
      band: 'B',
      marks: 3,
      question: 'Find the size of each exterior angle and each interior angle of a regular nonagon (9 sides).',
      steps: [
        {
          prompt: 'Find the exterior angle of a regular nonagon.',
          hint1: 'Exterior angles sum to 360°.',
          hint2: '360 ÷ 9 = ?',
          hint3: '40°.',
          answer: 40,
          tolerance: 0,
          unit: '°',
          explanation: 'Exterior angle = 360 ÷ 9 = 40°.',
        },
        {
          prompt: 'Find the interior angle.',
          hint1: 'Interior + exterior = 180°.',
          hint2: '180 − 40 = ?',
          hint3: '140°.',
          answer: 140,
          tolerance: 0,
          unit: '°',
          explanation: 'Interior angle = 180 − 40 = 140°.',
        },
        {
          prompt: 'Verify using the interior angle sum formula.',
          hint1: '(9−2) × 180 = 7 × 180 = 1260°.',
          hint2: '1260 ÷ 9 = 140°. ✓',
          hint3: 'Enter 1.',
          answer: 1,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: '(9−2)×180 ÷ 9 = 1260÷9 = 140° ✓',
          explanation: 'Interior angle sum = 1260°. Each angle = 1260÷9 = 140° ✓',
        },
      ],
      workedExample: {
        question: 'Find exterior and interior angles of a regular decagon (10 sides).',
        steps: ['Exterior = 360÷10 = 36°', 'Interior = 180−36 = <strong>144°</strong>', 'Check: (10−2)×180÷10=1440÷10=144 ✓'],
      },
      sampleAnswer: {
        grade4: 'Exterior = 40°. Interior = 140°.',
        grade6: 'Exterior = 360÷9 = 40°. Interior = 180−40 = 140°.',
        grade8: 'Exterior = 40°. Interior = 140°. Check: (9−2)×180/9 = 140° ✓',
      },
      examinerTip: 'Two methods for interior angle: 180−exterior, or (n−2)×180÷n. Both should give the same answer.',
      auditStatus: 'pending',
    },
    {
      id: 'ang-B05',
      subtopic: 'geo-angles',
      band: 'B',
      marks: 3,
      question: 'Two parallel lines are cut by a transversal. One angle is (3x + 5)° and its alternate angle is (5x − 15)°. Find x and the angle.',
      steps: [
        {
          prompt: 'Use the property of alternate angles to form an equation.',
          hint1: 'Alternate angles are equal: 3x+5 = 5x−15.',
          hint2: 'Rearrange: 20 = 2x.',
          hint3: 'x = 10.',
          answer: 10,
          tolerance: 0,
          unit: '',
          explanation: '3x+5=5x−15 → 20=2x → x=10.',
        },
        {
          prompt: 'Calculate the angle using 3x + 5.',
          hint1: '3 × 10 + 5 = ?',
          hint2: '35°.',
          hint3: '35°.',
          answer: 35,
          tolerance: 0,
          unit: '°',
          explanation: '3(10)+5 = 35°.',
        },
        {
          prompt: 'Verify: does 5x−15 also equal 35°?',
          hint1: '5(10) − 15 = ?',
          hint2: '50−15 = 35°.',
          hint3: 'Enter 1.',
          answer: 1,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: '5(10)−15 = 35° ✓',
          explanation: 'Both expressions give 35°. Alternate angles confirmed equal ✓',
        },
      ],
      workedExample: {
        question: 'Alternate angles: (4x+8)° and (6x−4)°. Find x and the angle.',
        steps: ['4x+8=6x−4 → 12=2x → x=6', 'Angle = 4(6)+8 = <strong>32°</strong>. Check: 6(6)−4=32 ✓'],
      },
      sampleAnswer: {
        grade4: 'x=10. Angle = 35°.',
        grade6: 'Alternate angles equal: 3x+5=5x−15. x=10. Angle = 35°.',
        grade8: '3x+5=5x−15 → x=10. Angle = 35°. Verified: 5(10)−15=35 ✓',
      },
      examinerTip: 'State the theorem (alternate angles are equal / co-interior angles sum to 180°) before forming your equation.',
      auditStatus: 'pending',
    },
    {
      id: 'ang-B06',
      subtopic: 'geo-angles',
      band: 'B',
      marks: 3,
      question: 'The interior angles of a pentagon are 110°, 95°, 125°, 3x° and 2x°. Find x.',
      steps: [
        {
          prompt: 'What is the sum of interior angles of a pentagon?',
          hint1: 'Use (n−2)×180 with n=5.',
          hint2: '(5−2)×180 = 3×180.',
          hint3: '540°.',
          answer: 540,
          tolerance: 0,
          unit: '°',
          explanation: 'Sum = (5−2)×180 = 540°.',
        },
        {
          prompt: 'Form and simplify the equation.',
          hint1: '110+95+125+3x+2x = 540.',
          hint2: '330+5x = 540.',
          hint3: '5x = 210.',
          answer: 210,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: '330 + 5x = 540, so 5x = 210',
          explanation: '330 + 5x = 540 → 5x = 210.',
        },
        {
          prompt: 'Find x.',
          hint1: 'x = 210 ÷ 5.',
          hint2: '42.',
          hint3: 'x = 42.',
          answer: 42,
          tolerance: 0,
          unit: '',
          explanation: 'x = 210 ÷ 5 = 42. Angles: 126° and 84°. Check: 110+95+125+126+84=540 ✓',
        },
      ],
      workedExample: {
        question: 'Pentagon angles: 100°, 110°, 120°, 4x°, x°. Find x.',
        steps: ['Sum = 540. 330+5x=540. 5x=210. x=42. But let\'s use these: 100+110+120+5x=540 → 5x=210 → x=42'],
      },
      sampleAnswer: {
        grade4: 'x=42.',
        grade6: 'Sum=540. 110+95+125+5x=540. 5x=210. x=42.',
        grade8: '5x+330=540. x=42. Angles: 126° and 84°. Check: 110+95+125+126+84=540 ✓',
      },
      examinerTip: 'Find the angle sum first, then form an equation with all angles equalling that sum.',
      auditStatus: 'pending',
    },
    {
      id: 'ang-C01',
      subtopic: 'geo-angles',
      band: 'C',
      marks: 4,
      question: 'The interior angles of a polygon are in arithmetic progression. The smallest is 100° and the largest is 140°. Find the number of sides.',
      steps: [
        {
          prompt: 'Find the mean of the angles in the arithmetic progression.',
          hint1: 'For an AP, mean = (first + last) ÷ 2.',
          hint2: '(100 + 140) ÷ 2 = ?',
          hint3: '120°.',
          answer: 120,
          tolerance: 0,
          unit: '°',
          explanation: 'Mean = (100+140)/2 = 120°.',
        },
        {
          prompt: 'Express the sum of angles two ways. Set n×120 = (n−2)×180. Expand the RHS.',
          hint1: '(n−2)×180 = 180n − 360.',
          hint2: 'So 120n = 180n − 360.',
          hint3: '360 = 60n.',
          answer: 360,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: '120n = 180n − 360, so 60n = 360',
          explanation: '120n = 180n−360 → 60n = 360.',
        },
        {
          prompt: 'Find n.',
          hint1: 'n = 360 ÷ 60.',
          hint2: '6.',
          hint3: 'n = 6 sides.',
          answer: 6,
          tolerance: 0,
          unit: 'sides',
          explanation: 'n = 360÷60 = 6.',
        },
        {
          prompt: 'Verify: sum of interior angles of a hexagon.',
          hint1: '(6−2)×180 = 4×180 = 720°.',
          hint2: '6×120 = 720. ✓',
          hint3: 'Enter 720.',
          answer: 720,
          tolerance: 0,
          unit: '°',
          explanation: 'Sum = (6−2)×180 = 720°. Also 6×120 = 720 ✓',
        },
      ],
      workedExample: {
        question: 'Polygon in AP: smallest = 90°, largest = 150°. Find number of sides.',
        steps: ['Mean = (90+150)/2 = 120°', 'n×120 = (n−2)×180 → 60n = 360 → n = 6', 'Check: (6−2)×180 = 720 = 6×120 ✓'],
      },
      sampleAnswer: {
        grade4: 'Mean=120°. 120n=(n−2)×180. n=6.',
        grade6: 'Mean=120°. 120n=180n−360. 60n=360. n=6.',
        grade8: 'AP mean=(100+140)/2=120°. Sum=120n=(n−2)×180. 60n=360. n=6. Check: 4×180=720=6×120 ✓',
      },
      examinerTip: 'For an AP, sum = n × mean. Set this equal to (n−2)×180 and solve.',
      auditStatus: 'pending',
    },
    {
      id: 'ang-C02',
      subtopic: 'geo-angles',
      band: 'C',
      marks: 4,
      question: 'Quadrilateral ABCD has ∠A = (x+15)°, ∠B = (2x)°, ∠C = (x+25)° and ∠D = (2x−40)°. Find all four angles.',
      steps: [
        {
          prompt: 'Form an equation using the angle sum of a quadrilateral (360°).',
          hint1: '(x+15)+(2x)+(x+25)+(2x−40) = 360.',
          hint2: 'Simplify: 6x + 0 = 360.',
          hint3: 'x = 60.',
          answer: 60,
          tolerance: 0,
          unit: '',
          explanation: '6x + (15+0+25−40) = 6x + 0 = 360. x = 60.',
        },
        {
          prompt: 'Find ∠A = x + 15.',
          hint1: '60 + 15 = ?',
          hint2: '75°.',
          hint3: '75°.',
          answer: 75,
          tolerance: 0,
          unit: '°',
          explanation: '∠A = 60+15 = 75°.',
        },
        {
          prompt: 'Find ∠B = 2x.',
          hint1: '2 × 60 = ?',
          hint2: '120°.',
          hint3: '120°.',
          answer: 120,
          tolerance: 0,
          unit: '°',
          explanation: '∠B = 2×60 = 120°.',
        },
        {
          prompt: 'Find ∠D = 2x − 40.',
          hint1: '2×60 − 40 = ?',
          hint2: '80°.',
          hint3: '80°.',
          answer: 80,
          tolerance: 0,
          unit: '°',
          explanation: '∠D = 120−40 = 80°. ∠C = 60+25 = 85°. Check: 75+120+85+80=360 ✓',
        },
      ],
      workedExample: {
        question: '∠A=(x+10)°, ∠B=(2x+5)°, ∠C=(x+15)°, ∠D=(2x−30)°. Find all angles.',
        steps: ['6x=360 → x=60', '∠A=70°, ∠B=125°, ∠C=75°, ∠D=90°. Check: 360 ✓'],
      },
      sampleAnswer: {
        grade4: 'x=60. Angles: 75°, 120°, 85°, 80°.',
        grade6: '6x=360, x=60. ∠A=75°, ∠B=120°, ∠C=85°, ∠D=80°. Sum=360 ✓',
        grade8: 'Sum=360: 6x=360, x=60. Angles: 75°, 120°, 85°, 80°. Check: 360 ✓',
      },
      examinerTip: 'Always verify by checking all angles sum to 360° for a quadrilateral.',
      auditStatus: 'pending',
    },
    {
      id: 'ang-C03',
      subtopic: 'geo-angles',
      band: 'C',
      marks: 4,
      question: 'A regular polygon has each interior angle equal to 5 times each exterior angle. Find the number of sides.',
      steps: [
        {
          prompt: 'Let the exterior angle = E°. Write an equation using interior + exterior = 180°.',
          hint1: 'Interior = 5E. So 5E + E = 180.',
          hint2: '6E = 180.',
          hint3: 'E = 30°.',
          answer: 30,
          tolerance: 0,
          unit: '°',
          explanation: '5E + E = 180 → 6E = 180 → E = 30°.',
        },
        {
          prompt: 'Find the number of sides: n = 360 ÷ E.',
          hint1: 'n = 360 ÷ 30.',
          hint2: '12.',
          hint3: 'n = 12.',
          answer: 12,
          tolerance: 0,
          unit: 'sides',
          explanation: 'n = 360 ÷ 30 = 12.',
        },
        {
          prompt: 'What is the interior angle?',
          hint1: 'Interior = 5E = 5 × 30.',
          hint2: '150°.',
          hint3: '150°.',
          answer: 150,
          tolerance: 0,
          unit: '°',
          explanation: 'Interior = 5 × 30 = 150°.',
        },
        {
          prompt: 'Verify using (n−2)×180÷n.',
          hint1: '(12−2)×180 = 1800.',
          hint2: '1800 ÷ 12 = 150°. ✓',
          hint3: 'Enter 150.',
          answer: 150,
          tolerance: 0,
          unit: '°',
          explanation: '(12−2)×180÷12 = 10×180÷12 = 150° ✓',
        },
      ],
      workedExample: {
        question: 'Interior angle = 3 × exterior angle. Find number of sides.',
        steps: ['3E+E=180 → E=45°', 'n=360÷45=<strong>8</strong>. Interior=135°. Check: (8−2)×180÷8=135 ✓'],
      },
      sampleAnswer: {
        grade4: 'E=30°. n=12.',
        grade6: '5E+E=180 → E=30°. n=360÷30=12. Interior=150°.',
        grade8: 'Let E=exterior. 5E+E=180 → E=30°. n=12. Interior=(12−2)×180÷12=150°=5×30 ✓',
      },
      examinerTip: 'Set up using interior + exterior = 180°, then solve for E before finding n.',
      auditStatus: 'pending',
    },
    {
      id: 'ang-C04',
      subtopic: 'geo-angles',
      band: 'C',
      marks: 4,
      question: 'Triangle PQR has exterior angle at R = (5x+10)°. The two non-adjacent interior angles are (2x+20)° and (x+40)°. Find x, the exterior angle, and verify with angles on a straight line.',
      steps: [
        {
          prompt: 'Apply the exterior angle theorem: exterior = sum of two non-adjacent interior angles.',
          hint1: '5x+10 = (2x+20)+(x+40).',
          hint2: '5x+10 = 3x+60.',
          hint3: '2x = 50.',
          answer: 50,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: '5x+10=3x+60 → 2x=50',
          explanation: '5x+10=3x+60 → 2x=50.',
        },
        {
          prompt: 'Find x.',
          hint1: 'x = 50 ÷ 2.',
          hint2: '25.',
          hint3: 'x = 25.',
          answer: 25,
          tolerance: 0,
          unit: '',
          explanation: 'x = 25.',
        },
        {
          prompt: 'Find the exterior angle at R.',
          hint1: '5x+10 = 5×25+10.',
          hint2: '125+10 = 135.',
          hint3: '135°.',
          answer: 135,
          tolerance: 0,
          unit: '°',
          explanation: 'Exterior angle = 5(25)+10 = 135°.',
        },
        {
          prompt: 'Find the interior angle at R and verify angles in the triangle sum to 180°.',
          hint1: 'Interior at R = 180−135 = 45°.',
          hint2: 'Sum: (2×25+20)+(25+40)+45 = 70+65+45 = 180. ✓',
          hint3: 'Enter 45.',
          answer: 45,
          tolerance: 0,
          unit: '°',
          explanation: 'Interior at R=45°. Triangle sum: 70+65+45=180 ✓',
        },
      ],
      workedExample: {
        question: 'Exterior at R=(4x+6)°. Non-adjacent: (x+30)° and (2x+4)°. Find x.',
        steps: ['4x+6=3x+34 → x=28', 'Exterior=118°. Interior at R=62°. Check: 58+60+62=180 ✓'],
      },
      sampleAnswer: {
        grade4: 'x=25. Exterior=135°.',
        grade6: '5x+10=3x+60. x=25. Exterior=135°. Interior=45°. Check: 70+65+45=180 ✓',
        grade8: '5x+10=(2x+20)+(x+40). 2x=50, x=25. Exterior=135°. Interior=45°. Sum=180 ✓',
      },
      examinerTip: 'Use the exterior angle theorem to form the equation, then verify with interior angle sum.',
      auditStatus: 'pending',
    },
"""

with open(FILE, encoding='utf-8') as f:
    content = f.read()
pos = content.find(MARKER)
if pos < 0:
    print('MARKER NOT FOUND')
else:
    print(f'Inserting at char {pos}')
    with open(FILE, 'w', encoding='utf-8') as f:
        f.write(content[:pos] + NEW + content[pos:])
    print('Done - geo_q1 (12 angle questions)')
