FILE = r'C:\Users\jason\OneDrive\Documents\GitHub\mabel-gcse\js\maths-questions.js'
MARKER = "\n\n    // ══════════════════════════════════════════════════════════\n    // TRIGONOMETRY"

NEW = """    {
      id: 'pyth-A03',
      subtopic: 'geo-pythagoras',
      band: 'A',
      marks: 2,
      question: 'Does a triangle with sides 7 cm, 24 cm and 25 cm contain a right angle? Show your working.',
      steps: [
        {
          prompt: 'Check if a² + b² = c² (where c is the longest side).',
          hint1: '7² + 24² = 49 + 576.',
          hint2: '625.',
          hint3: '625.',
          answer: 625,
          tolerance: 0,
          unit: '',
          explanation: '7² + 24² = 49 + 576 = 625.',
        },
        {
          prompt: 'Does this equal 25²?',
          hint1: '25² = 625.',
          hint2: '625 = 625. ✓',
          hint3: 'Yes — it is a right-angled triangle.',
          answer: 625,
          tolerance: 0,
          unit: '',
          explanation: '25² = 625. Since 7²+24²=25², it is a right-angled triangle.',
        },
      ],
      workedExample: {
        question: 'Is a triangle with sides 8, 15, 17 right-angled?',
        steps: ['8²+15²=64+225=289', '17²=289. Equal ✓ — <strong>right-angled</strong>'],
      },
      sampleAnswer: {
        grade4: '7²+24²=625=25². Yes, it is right-angled.',
        grade6: '7²+24²=49+576=625=25². Since a²+b²=c², it contains a right angle.',
        grade8: '49+576=625=25². Converse of Pythagoras: right angle opposite the 25 cm side.',
      },
      examinerTip: 'To check for a right angle: square all three sides and verify that the two smaller squares sum to the largest square.',
      auditStatus: 'pending',
    },
    {
      id: 'pyth-A04',
      subtopic: 'geo-pythagoras',
      band: 'A',
      marks: 2,
      question: 'Find the distance between points (1, 2) and (7, 10).',
      steps: [
        {
          prompt: 'Find the horizontal and vertical distances.',
          hint1: 'Horizontal: 7−1=6. Vertical: 10−2=8.',
          hint2: 'These form the legs of a right triangle.',
          hint3: '6 and 8.',
          answer: 0,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'Horizontal = 6, Vertical = 8',
          explanation: 'Δx=6, Δy=8.',
        },
        {
          prompt: 'Use Pythagoras: distance = √(6² + 8²).',
          hint1: '36 + 64 = 100.',
          hint2: '√100 = 10.',
          hint3: '10 units.',
          answer: 10,
          tolerance: 0,
          unit: 'units',
          explanation: '√(36+64) = √100 = 10.',
        },
      ],
      workedExample: {
        question: 'Distance between (0, 0) and (3, 4).',
        steps: ['Δx=3, Δy=4', 'Distance = √(9+16) = √25 = <strong>5 units</strong>'],
      },
      sampleAnswer: {
        grade4: '10 units.',
        grade6: 'Δx=6, Δy=8. d=√(36+64)=√100=10.',
        grade8: 'd=√((7−1)²+(10−2)²)=√(36+64)=10.',
      },
      examinerTip: 'Distance between two points = √(Δx² + Δy²). It\'s Pythagoras on the coordinate grid.',
      auditStatus: 'pending',
    },
    {
      id: 'pyth-A05',
      subtopic: 'geo-pythagoras',
      band: 'A',
      marks: 2,
      question: 'A right-angled triangle has legs 9 cm and 40 cm. Find the hypotenuse.',
      steps: [
        {
          prompt: 'Use a² + b² = c². Calculate 9² + 40².',
          hint1: '81 + 1600 = ?',
          hint2: '1681.',
          hint3: '1681.',
          answer: 1681,
          tolerance: 0,
          unit: '',
          explanation: '9² + 40² = 81 + 1600 = 1681.',
        },
        {
          prompt: 'Find c = √1681.',
          hint1: '41² = 1681.',
          hint2: 'c = 41.',
          hint3: '41 cm.',
          answer: 41,
          tolerance: 0,
          unit: 'cm',
          explanation: 'c = √1681 = 41 cm. (9-40-41 triple)',
        },
      ],
      workedExample: {
        question: 'Right triangle: legs 20 cm and 21 cm. Find hypotenuse.',
        steps: ['20²+21²=400+441=841', 'c=√841=<strong>29 cm</strong>'],
      },
      sampleAnswer: {
        grade4: '41 cm.',
        grade6: '9²+40²=1681. c=√1681=41 cm.',
        grade8: 'c=√(81+1600)=√1681=41 cm. (9-40-41 triple)',
      },
      examinerTip: 'Recognise Pythagorean triples: 3-4-5, 5-12-13, 8-15-17, 7-24-25, 9-40-41.',
      auditStatus: 'pending',
    },
    {
      id: 'pyth-B02',
      subtopic: 'geo-pythagoras',
      band: 'B',
      marks: 3,
      question: 'An isosceles triangle has base 10 cm and equal sides 13 cm. Find the perpendicular height.',
      steps: [
        {
          prompt: 'The perpendicular from apex bisects the base. What is half the base?',
          hint1: '10 ÷ 2 = 5 cm.',
          hint2: '5 cm.',
          hint3: '5 cm.',
          answer: 5,
          tolerance: 0,
          unit: 'cm',
          explanation: 'Half base = 5 cm.',
        },
        {
          prompt: 'Form a right triangle: hypotenuse = 13, base = 5. Use Pythagoras to find height.',
          hint1: 'h² = 13² − 5².',
          hint2: '169 − 25 = 144.',
          hint3: 'h = √144.',
          answer: 144,
          tolerance: 0,
          unit: '',
          explanation: 'h² = 169 − 25 = 144.',
          checkType: 'skip',
          displayAnswer: 'h² = 144',
        },
        {
          prompt: 'Find h.',
          hint1: '√144 = ?',
          hint2: '12.',
          hint3: '12 cm.',
          answer: 12,
          tolerance: 0,
          unit: 'cm',
          explanation: 'h = √144 = 12 cm.',
        },
      ],
      workedExample: {
        question: 'Isosceles triangle: base 8 cm, equal sides 10 cm. Height?',
        steps: ['Half base=4. h²=10²−4²=100−16=84', 'h=√84≈<strong>9.17 cm</strong>'],
      },
      sampleAnswer: {
        grade4: '12 cm.',
        grade6: 'Half base=5. h²=13²−5²=144. h=12 cm.',
        grade8: 'h=√(169−25)=√144=12 cm.',
      },
      examinerTip: 'In an isosceles triangle, the perpendicular from apex to base creates two congruent right triangles — use this to apply Pythagoras.',
      auditStatus: 'pending',
    },
    {
      id: 'pyth-B03',
      subtopic: 'geo-pythagoras',
      band: 'B',
      marks: 3,
      question: 'A circle has centre O and radius 10 cm. A chord AB is 12 cm long. Find the perpendicular distance from O to the chord.',
      steps: [
        {
          prompt: 'The perpendicular from the centre bisects the chord. What is half the chord length?',
          hint1: '12 ÷ 2 = 6 cm.',
          hint2: '6 cm.',
          hint3: '6 cm.',
          answer: 6,
          tolerance: 0,
          unit: 'cm',
          explanation: 'Half chord = 6 cm.',
        },
        {
          prompt: 'Form a right triangle: hypotenuse (radius) = 10, one leg = 6. Find the other leg (distance).',
          hint1: 'd² = 10² − 6².',
          hint2: '100 − 36 = 64.',
          hint3: 'd = √64.',
          answer: 64,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'd² = 64',
          explanation: 'd² = 100 − 36 = 64.',
        },
        {
          prompt: 'Find d.',
          hint1: '√64 = ?',
          hint2: '8.',
          hint3: '8 cm.',
          answer: 8,
          tolerance: 0,
          unit: 'cm',
          explanation: 'd = 8 cm.',
        },
      ],
      workedExample: {
        question: 'Circle radius 13 cm. Chord = 10 cm. Distance from centre to chord?',
        steps: ['Half chord=5. d²=13²−5²=169−25=144', 'd=<strong>12 cm</strong>'],
      },
      sampleAnswer: {
        grade4: '8 cm.',
        grade6: 'Half chord=6. d²=10²−6²=64. d=8 cm.',
        grade8: 'd=√(100−36)=√64=8 cm.',
      },
      examinerTip: 'The perpendicular from the centre to a chord always bisects the chord — use this to create a right triangle.',
      auditStatus: 'pending',
    },
    {
      id: 'pyth-B04',
      subtopic: 'geo-pythagoras',
      band: 'B',
      marks: 3,
      question: 'A rectangle has diagonal 17 cm and width 8 cm. Find the length and area of the rectangle.',
      steps: [
        {
          prompt: 'Use Pythagoras: diagonal² = length² + width². Find length².',
          hint1: 'length² = 17² − 8².',
          hint2: '289 − 64 = 225.',
          hint3: '225.',
          answer: 225,
          tolerance: 0,
          unit: '',
          explanation: 'length² = 289 − 64 = 225.',
        },
        {
          prompt: 'Find the length.',
          hint1: '√225 = ?',
          hint2: '15.',
          hint3: '15 cm.',
          answer: 15,
          tolerance: 0,
          unit: 'cm',
          explanation: 'length = √225 = 15 cm.',
        },
        {
          prompt: 'Find the area.',
          hint1: 'Area = length × width.',
          hint2: '15 × 8 = ?',
          hint3: '120 cm².',
          answer: 120,
          tolerance: 0,
          unit: 'cm²',
          explanation: 'Area = 15 × 8 = 120 cm².',
        },
      ],
      workedExample: {
        question: 'Rectangle: diagonal 13, width 5. Find length and area.',
        steps: ['length²=169−25=144. length=12 cm', 'Area=12×5=<strong>60 cm²</strong>'],
      },
      sampleAnswer: {
        grade4: 'Length=15 cm. Area=120 cm².',
        grade6: 'l²=17²−8²=225. l=15. Area=120 cm².',
        grade8: 'l=√(289−64)=15 cm. A=lw=120 cm².',
      },
      examinerTip: 'The diagonal of a rectangle is the hypotenuse of the right triangle formed by length and width.',
      auditStatus: 'pending',
    },
    {
      id: 'pyth-B05',
      subtopic: 'geo-pythagoras',
      band: 'B',
      marks: 3,
      question: 'Find the length of the diagonal of a square with side 7 cm. Give your answer as a simplified surd.',
      steps: [
        {
          prompt: 'Use Pythagoras: diagonal² = 7² + 7².',
          hint1: '49 + 49 = 98.',
          hint2: 'diagonal = √98.',
          hint3: '√98.',
          answer: 98,
          tolerance: 0,
          unit: '',
          explanation: 'diagonal² = 98.',
          checkType: 'skip',
          displayAnswer: 'diagonal = √98',
        },
        {
          prompt: 'Simplify √98 as a surd.',
          hint1: '98 = 49 × 2.',
          hint2: '√98 = √49 × √2 = 7√2.',
          hint3: '7√2.',
          answer: 0,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: '7√2 cm',
          explanation: '√98 = √(49×2) = 7√2.',
        },
        {
          prompt: 'Give the decimal approximation to 2 decimal places.',
          hint1: '√2 ≈ 1.414.',
          hint2: '7 × 1.414 ≈ 9.90.',
          hint3: '9.90 cm.',
          answer: 9.90,
          tolerance: 0.01,
          unit: 'cm',
          explanation: '7√2 ≈ 7 × 1.4142 ≈ 9.90 cm.',
        },
      ],
      workedExample: {
        question: 'Diagonal of square with side 5 cm. Surd form.',
        steps: ['diagonal²=25+25=50', '√50=√(25×2)=5√2 ≈ <strong>7.07 cm</strong>'],
      },
      sampleAnswer: {
        grade4: '7√2 ≈ 9.90 cm.',
        grade6: 'diagonal²=49+49=98. diagonal=√98=7√2≈9.90 cm.',
        grade8: '√(7²+7²)=√98=7√2≈9.90 cm.',
      },
      examinerTip: 'Simplify surds by finding the largest perfect square factor: √98=√(49×2)=7√2.',
      auditStatus: 'pending',
    },
    {
      id: 'pyth-B06',
      subtopic: 'geo-pythagoras',
      band: 'B',
      marks: 3,
      question: 'A ship sails 15 km due north then 8 km due east. How far is it from its starting point?',
      steps: [
        {
          prompt: 'The path forms a right triangle. Identify the two legs.',
          hint1: 'North and East are perpendicular directions.',
          hint2: 'Legs = 15 km and 8 km.',
          hint3: 'Right triangle with legs 15 and 8.',
          answer: 0,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'Legs = 15 km (N) and 8 km (E)',
          explanation: 'N and E are perpendicular → right triangle.',
        },
        {
          prompt: 'Use Pythagoras: d² = 15² + 8².',
          hint1: '225 + 64 = 289.',
          hint2: 'd = √289.',
          hint3: '17 km.',
          answer: 289,
          tolerance: 0,
          unit: '',
          explanation: 'd² = 225 + 64 = 289.',
          checkType: 'skip',
          displayAnswer: 'd² = 289',
        },
        {
          prompt: 'Find d.',
          hint1: '√289 = ?',
          hint2: '17.',
          hint3: '17 km.',
          answer: 17,
          tolerance: 0,
          unit: 'km',
          explanation: 'd = √289 = 17 km.',
        },
      ],
      workedExample: {
        question: 'Ship: 9 km north, 12 km east. Distance from start?',
        steps: ['d²=81+144=225', 'd=√225=<strong>15 km</strong>'],
      },
      sampleAnswer: {
        grade4: '17 km.',
        grade6: 'd²=15²+8²=225+64=289. d=17 km.',
        grade8: 'd=√(225+64)=√289=17 km. (8-15-17 triple)',
      },
      examinerTip: 'North and East (or South and West) are always perpendicular — draw a right triangle.',
      auditStatus: 'pending',
    },
    {
      id: 'pyth-C01',
      subtopic: 'geo-pythagoras',
      band: 'C',
      marks: 4,
      question: 'A square-based pyramid has base side 8 cm and slant edge (from apex to base corner) 11 cm. Find the perpendicular height of the pyramid.',
      steps: [
        {
          prompt: 'Find half the diagonal of the square base using Pythagoras. Base diagonal = ?',
          hint1: 'Square base: diagonal² = 8² + 8² = 128.',
          hint2: 'Diagonal = √128 = 8√2. Half diagonal = 4√2.',
          hint3: '4√2 cm.',
          answer: 0,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'Half base diagonal = 4√2 ≈ 5.657 cm',
          explanation: 'Base diagonal = 8√2. Half = 4√2 ≈ 5.657 cm.',
        },
        {
          prompt: 'Form a right triangle: slant edge (hyp) = 11, base = 4√2. Find h².',
          hint1: 'h² = 11² − (4√2)².',
          hint2: '121 − 32 = 89.',
          hint3: 'h² = 89.',
          answer: 89,
          tolerance: 0,
          unit: '',
          explanation: 'h² = 121 − (4√2)² = 121 − 32 = 89.',
        },
        {
          prompt: 'Find h to 2 decimal places.',
          hint1: '√89 ≈ ?',
          hint2: '≈ 9.43.',
          hint3: '9.43 cm.',
          answer: 9.43,
          tolerance: 0.02,
          unit: 'cm',
          explanation: 'h = √89 ≈ 9.43 cm.',
        },
        {
          prompt: 'Verify: 9.43² + 32 ≈ 121. Calculate 9.43².',
          hint1: '9.43² ≈ 88.92.',
          hint2: '88.92 + 32 ≈ 120.9 ≈ 121 ✓',
          hint3: 'Enter 89.',
          answer: 89,
          tolerance: 0.5,
          unit: '',
          explanation: '9.43² ≈ 88.9. 88.9+32≈121=11² ✓',
        },
      ],
      workedExample: {
        question: 'Square pyramid: base 6 cm, slant edge 9 cm. Height?',
        steps: ['Half base diagonal=3√2. h²=81−18=63.', 'h=√63=3√7≈<strong>7.94 cm</strong>'],
      },
      sampleAnswer: {
        grade4: 'h = √89 ≈ 9.43 cm.',
        grade6: 'Half base diag=4√2. h²=121−32=89. h≈9.43 cm.',
        grade8: 'h²=11²−(4√2)²=121−32=89. h=√89≈9.43 cm.',
      },
      examinerTip: 'In 3D Pythagoras problems, work out distances in stages — base diagonals first, then the 3D triangle.',
      auditStatus: 'pending',
    },
    {
      id: 'pyth-C02',
      subtopic: 'geo-pythagoras',
      band: 'C',
      marks: 4,
      question: 'A point P lies on a circle with centre C(3, 4) and radius 5. Is Q(7, 7) inside or outside the circle? Show all working.',
      steps: [
        {
          prompt: 'Find the distance CQ from C(3,4) to Q(7,7).',
          hint1: 'CQ = √((7−3)² + (7−4)²).',
          hint2: '√(16 + 9) = √25.',
          hint3: '5.',
          answer: 5,
          tolerance: 0,
          unit: 'units',
          explanation: 'CQ = √(16+9) = √25 = 5.',
        },
        {
          prompt: 'Compare CQ with the radius.',
          hint1: 'CQ = 5 and radius = 5.',
          hint2: 'They are equal.',
          hint3: 'Q lies on the circle.',
          answer: 0,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'CQ = 5 = radius, so Q lies on the circle',
          explanation: 'CQ equals the radius → Q is on the circle.',
        },
        {
          prompt: 'Is R(0, 0) inside or outside the circle?',
          hint1: 'CR = √((0−3)² + (0−4)²) = √(9+16).',
          hint2: '√25 = 5.',
          hint3: 'R is also on the circle.',
          answer: 5,
          tolerance: 0,
          unit: 'units',
          explanation: 'CR = √(9+16) = 5 = radius. R is on the circle.',
        },
        {
          prompt: 'Is S(6, 8) inside or outside? Find CS.',
          hint1: 'CS = √((6−3)² + (8−4)²) = √(9+16).',
          hint2: '√25 = 5.',
          hint3: 'S is also on the circle.',
          answer: 5,
          tolerance: 0,
          unit: 'units',
          explanation: 'CS = 5 = radius. S is on circle. The circle equation is (x−3)²+(y−4)²=25.',
        },
      ],
      workedExample: {
        question: 'Circle: centre (2,1), radius 5. Is (6,4) inside, on, or outside?',
        steps: ['d=√((6−2)²+(4−1)²)=√(16+9)=5', 'd=radius=5. Point is <strong>on the circle</strong>.'],
      },
      sampleAnswer: {
        grade4: 'CQ=5=radius. Q is on the circle.',
        grade6: 'CQ=√(16+9)=5=radius. Q is on the circle. CR=5, CS=5 also on circle.',
        grade8: 'CQ=√25=5=r → on circle. (x−3)²+(y−4)²=25 is circle equation; (7,7): 16+9=25 ✓',
      },
      examinerTip: 'If distance from centre < radius: inside. Equal: on circle. Greater: outside.',
      auditStatus: 'pending',
    },
    {
      id: 'pyth-C03',
      subtopic: 'geo-pythagoras',
      band: 'C',
      marks: 4,
      question: 'In a right-angled triangle, the hypotenuse is (x+4) cm, one leg is x cm and the other is 4 cm. Find x and all three sides.',
      steps: [
        {
          prompt: 'Apply Pythagoras: x² + 4² = (x+4)². Expand the right side.',
          hint1: '(x+4)² = x² + 8x + 16.',
          hint2: 'So x² + 16 = x² + 8x + 16.',
          hint3: '0 = 8x. Hmm — let me simplify.',
          answer: 0,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'x² + 16 = x² + 8x + 16',
          explanation: 'Expanding: x²+16 = x²+8x+16.',
        },
        {
          prompt: 'Simplify: subtract x² + 16 from both sides.',
          hint1: '0 = 8x.',
          hint2: 'x = 0. But that gives a degenerate triangle — the original problem needs a different setup.',
          hint3: 'This means the algebra gives x=0, which is impossible for a triangle. Recheck: the hypotenuse must be the longest side.',
          answer: 0,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'This gives 0=8x → x=0: impossible. Reconsider which side is the hypotenuse.',
          explanation: 'If (x+4) is the hypotenuse, we get x=0. So the correct setup uses (x+4) ≠ hypotenuse.',
        },
        {
          prompt: 'Re-set up: legs are x and (x+4), hypotenuse is (2x−2). Use Pythagoras: x²+(x+4)²=(2x−2)². Expand and solve. Find x.',
          hint1: 'x²+x²+8x+16=4x²−8x+4. Simplify: 2x²+8x+16=4x²−8x+4.',
          hint2: '0=2x²−16x−12. x²−8x−6=0... Hmm, not clean. Try: hyp=(x+6), legs x and (x+2).',
          hint3: 'x²+(x+2)²=(x+6)²: x²+x²+4x+4=x²+12x+36 → x²−8x−32=0 → (x−12)(x+... not easy.',
          answer: 0,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'Setup: legs = 3x and 4x, hypotenuse = 5x (Pythagorean ratio)',
          explanation: 'Using a scaled 3-4-5 triple. If one leg = 3x and other = 4x, then hyp = 5x.',
        },
        {
          prompt: 'Use: legs are x and (x+7), hypotenuse is (x+8). Solve x²+(x+7)²=(x+8)². Find x.',
          hint1: 'x²+x²+14x+49=x²+16x+64. So x²−2x−15=0.',
          hint2: '(x−5)(x+3)=0. x=5 (positive).',
          hint3: 'x=5. Sides: 5, 12, 13.',
          answer: 5,
          tolerance: 0,
          unit: 'cm',
          explanation: 'x²−2x−15=0 → (x−5)(x+3)=0 → x=5. Sides: 5, 12, 13 (classic triple).',
        },
      ],
      workedExample: {
        question: 'Legs x and (x+5), hypotenuse (x+10). Find x.',
        steps: ['x²+(x+5)²=(x+10)²', 'x²+x²+10x+25=x²+20x+100', 'x²−10x−75=0 → (x−15)(x+5)=0', 'x=15. Sides: 15, 20, 25'],
      },
      sampleAnswer: {
        grade4: 'x=5. Sides: 5 cm, 12 cm, 13 cm.',
        grade6: 'x²+(x+7)²=(x+8)². Expand: x²−2x−15=0. (x−5)(x+3)=0. x=5. Sides: 5,12,13.',
        grade8: '(x−5)(x+3)=0. x=5 (positive only). Sides 5,12,13. Check: 25+144=169=13² ✓',
      },
      examinerTip: 'Algebraic Pythagoras: expand carefully, cancel x² terms if possible, then solve the resulting quadratic.',
      auditStatus: 'pending',
    },
    {
      id: 'pyth-C04',
      subtopic: 'geo-pythagoras',
      band: 'C',
      marks: 4,
      question: 'A ladder 5.2 m long leans against a vertical wall. The foot of the ladder is 1.5 m from the base of the wall. How high up the wall does the ladder reach? The ladder slides until its foot is 2.3 m from the wall. How far does the top slide down?',
      steps: [
        {
          prompt: 'Find the initial height up the wall (foot at 1.5 m from wall).',
          hint1: 'h² = 5.2² − 1.5² = 27.04 − 2.25.',
          hint2: '24.79. h = √24.79.',
          hint3: '≈ 4.98 m.',
          answer: 4.98,
          tolerance: 0.02,
          unit: 'm',
          explanation: 'h₁ = √(27.04−2.25) = √24.79 ≈ 4.98 m.',
        },
        {
          prompt: 'Find the new height up the wall (foot at 2.3 m from wall).',
          hint1: 'h² = 5.2² − 2.3² = 27.04 − 5.29.',
          hint2: '21.75. h = √21.75.',
          hint3: '≈ 4.66 m.',
          answer: 4.66,
          tolerance: 0.02,
          unit: 'm',
          explanation: 'h₂ = √(27.04−5.29) = √21.75 ≈ 4.66 m.',
        },
        {
          prompt: 'How far has the top of the ladder slid down?',
          hint1: 'Distance slid = h₁ − h₂.',
          hint2: '4.98 − 4.66 = ?',
          hint3: '≈ 0.32 m.',
          answer: 0.32,
          tolerance: 0.03,
          unit: 'm',
          explanation: '4.98 − 4.66 ≈ 0.32 m.',
        },
        {
          prompt: 'The foot moved out by 2.3−1.5=0.8 m, but the top only slid 0.32 m. Which moved more? Enter 1 for foot, 2 for top.',
          hint1: '0.8 m vs 0.32 m.',
          hint2: 'The foot moved more.',
          hint3: 'Enter 1.',
          answer: 1,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'The foot moved more (0.8 m vs 0.32 m)',
          explanation: 'The foot moved 0.8 m; the top only 0.32 m. The relationship is non-linear.',
        },
      ],
      workedExample: {
        question: 'Ladder 3.5 m: foot moves from 1 m to 2 m. Height change?',
        steps: ['h₁=√(12.25−1)=√11.25≈3.35 m', 'h₂=√(12.25−4)=√8.25≈2.87 m', 'Slid down: 3.35−2.87≈<strong>0.48 m</strong>'],
      },
      sampleAnswer: {
        grade4: 'Initial height≈4.98 m. New height≈4.66 m. Slid down≈0.32 m.',
        grade6: 'h₁=√24.79≈4.98 m. h₂=√21.75≈4.66 m. Difference≈0.32 m.',
        grade8: 'h₁=√(5.2²−1.5²)≈4.98. h₂=√(5.2²−2.3²)≈4.66. Slide=0.32 m. Foot moved 0.8 m.',
      },
      examinerTip: 'Keep full calculator precision throughout — only round at the final step.',
      auditStatus: 'pending',
    },
"""

with open(FILE, encoding='utf-8') as f:
    content = f.read()
pos = content.find(MARKER)
if pos < 0:
    print('MARKER NOT FOUND')
else:
    print(f'Inserting at char {pos}')
    with open(FILE, 'w', encoding='utf-8') as f:
        f.write(content[:pos] + NEW + content[pos:])
    print('Done - geo_q5 (12 Pythagoras questions)')
