FILE = r'C:\Users\jason\OneDrive\Documents\GitHub\mabel-gcse\js\maths-questions.js'
MARKER = "\n\n    // ══════════════════════════════════════════════════════════\n    // PYTHAGORAS"

NEW = """    {
      id: 'tr-A03',
      subtopic: 'geo-transformations',
      band: 'A',
      marks: 2,
      question: 'Translate point (3, −2) by vector (−5, 4). Give the image coordinates.',
      steps: [
        {
          prompt: 'Add the x-components: 3 + (−5).',
          hint1: '3 + (−5) = 3 − 5.',
          hint2: '−2.',
          hint3: 'New x = −2.',
          answer: -2,
          tolerance: 0,
          unit: '',
          explanation: 'x: 3 + (−5) = −2.',
        },
        {
          prompt: 'Add the y-components: −2 + 4.',
          hint1: '−2 + 4 = ?',
          hint2: '2.',
          hint3: 'New y = 2.',
          answer: 2,
          tolerance: 0,
          unit: '',
          explanation: 'y: −2 + 4 = 2. Image = (−2, 2).',
        },
      ],
      workedExample: {
        question: 'Translate (4, 1) by vector (−3, 5).',
        steps: ['x: 4+(−3)=1, y: 1+5=6', 'Image = <strong>(1, 6)</strong>'],
      },
      sampleAnswer: {
        grade4: 'Image = (−2, 2).',
        grade6: 'x: 3+(−5)=−2. y: −2+4=2. Image (−2, 2).',
        grade8: 'Translation (3,−2)+(−5,4)=(−2,2).',
      },
      examinerTip: 'Add vector components separately to x and y coordinates.',
      auditStatus: 'pending',
    },
    {
      id: 'tr-A04',
      subtopic: 'geo-transformations',
      band: 'A',
      marks: 2,
      question: 'Shape A has vertices (2, 1), (5, 1), (5, 4). Reflect it in the y-axis. Give the image vertices.',
      steps: [
        {
          prompt: 'When reflecting in the y-axis, which coordinate changes sign?',
          hint1: 'Reflection in y-axis: (x, y) → (−x, y).',
          hint2: 'The x-coordinate changes sign; y stays the same.',
          hint3: 'x-coordinates negate.',
          answer: 0,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: '(x, y) → (−x, y)',
          explanation: 'Reflection in y-axis: x-coordinate changes sign.',
        },
        {
          prompt: 'Apply to all vertices. Give the x-coordinate of the image of (5, 1).',
          hint1: '(2,1)→(−2,1), (5,1)→(−5,1), (5,4)→(−5,4).',
          hint2: 'x of (5,1) image = −5.',
          hint3: '−5.',
          answer: -5,
          tolerance: 0,
          unit: '',
          explanation: 'Image vertices: (−2,1), (−5,1), (−5,4).',
          displayAnswer: 'Image: (−2, 1), (−5, 1), (−5, 4)',
        },
      ],
      workedExample: {
        question: 'Reflect (3, 2), (6, 2), (6, 5) in the y-axis.',
        steps: ['(x,y)→(−x,y)', 'Image: <strong>(−3,2), (−6,2), (−6,5)</strong>'],
      },
      sampleAnswer: {
        grade4: 'Image: (−2,1), (−5,1), (−5,4).',
        grade6: 'Reflection in y-axis: x→−x. Image: (−2,1), (−5,1), (−5,4).',
        grade8: '(x,y)→(−x,y). Image: (−2,1), (−5,1), (−5,4).',
      },
      examinerTip: 'Reflection in y-axis: negate x. Reflection in x-axis: negate y.',
      auditStatus: 'pending',
    },
    {
      id: 'tr-A05',
      subtopic: 'geo-transformations',
      band: 'A',
      marks: 2,
      question: 'Rotate point (4, 2) by 180° about the origin. Give the image coordinates.',
      steps: [
        {
          prompt: '180° rotation about origin: (x, y) → (−x, −y). What is the image of (4, 2)?',
          hint1: 'Negate both coordinates.',
          hint2: '(−4, −2).',
          hint3: '(−4, −2).',
          answer: -4,
          tolerance: 0,
          unit: '',
          explanation: '(4,2)→(−4,−2) under 180° rotation.',
          displayAnswer: '(−4, −2)',
        },
      ],
      workedExample: {
        question: 'Rotate (3, −1) by 180° about origin.',
        steps: ['(x,y)→(−x,−y)', 'Image = <strong>(−3, 1)</strong>'],
      },
      sampleAnswer: {
        grade4: '(−4, −2).',
        grade6: '180° rotation: (x,y)→(−x,−y). Image = (−4,−2).',
        grade8: '(4,2) → (−4,−2). Equivalent to reflection in both axes.',
      },
      examinerTip: '180° rotation about origin: negate both coordinates. Order of negation doesn\'t matter.',
      auditStatus: 'pending',
    },
    {
      id: 'tr-B02',
      subtopic: 'geo-transformations',
      band: 'B',
      marks: 3,
      question: 'Triangle with vertices A(1, 1), B(3, 1), C(1, 3) is enlarged by scale factor 3 from centre (−1, −1). Find the image vertices.',
      steps: [
        {
          prompt: 'To enlarge from a non-origin centre, find the vector from centre to each point, scale it, then add back the centre.',
          hint1: 'For A(1,1): vector from (−1,−1) to (1,1) = (2, 2). Scale by 3: (6, 6). Add centre: (6+(−1), 6+(−1)) = (5, 5).',
          hint2: 'A\' = (5, 5).',
          hint3: '(5, 5).',
          answer: 5,
          tolerance: 0,
          unit: '',
          explanation: 'A(1,1): (2,2)×3=(6,6). Image=(5,5).',
          displayAnswer: "A' = (5, 5)",
        },
        {
          prompt: 'Find image of B(3, 1).',
          hint1: 'Vector from (−1,−1) to (3,1) = (4,2). Scale by 3: (12,6). Add centre.',
          hint2: '(12+(−1), 6+(−1)) = (11, 5).',
          hint3: "(11, 5).",
          answer: 11,
          tolerance: 0,
          unit: '',
          explanation: "B(3,1): (4,2)×3=(12,6). Image=(11,5).",
          displayAnswer: "B' = (11, 5)",
        },
        {
          prompt: 'Find image of C(1, 3).',
          hint1: 'Vector from (−1,−1) to (1,3) = (2,4). Scale by 3: (6,12). Add centre.',
          hint2: '(6+(−1), 12+(−1)) = (5, 11).',
          hint3: '(5, 11).',
          answer: 11,
          tolerance: 0,
          unit: '',
          explanation: "C(1,3): (2,4)×3=(6,12). Image=(5,11).",
          displayAnswer: "C' = (5, 11)",
        },
      ],
      workedExample: {
        question: 'Enlarge (2,3) by SF=2 from centre (1,1).',
        steps: ['Vector: (1,2). Scale: (2,4). Add centre: (3,5).', "Image = <strong>(3, 5)</strong>"],
      },
      sampleAnswer: {
        grade4: "A'=(5,5), B'=(11,5), C'=(5,11).",
        grade6: 'From centre (−1,−1): vectors scaled by 3, add back centre. A\'=(5,5), B\'=(11,5), C\'=(5,11).',
        grade8: "A'=3×(2,2)+(−1,−1)=(5,5). B'=3×(4,2)+(−1,−1)=(11,5). C'=3×(2,4)+(−1,−1)=(5,11).",
      },
      examinerTip: 'Enlargement from non-origin centre: scale the vector from centre to point, then add the centre coordinates.',
      auditStatus: 'pending',
    },
    {
      id: 'tr-B03',
      subtopic: 'geo-transformations',
      band: 'B',
      marks: 3,
      question: 'Describe fully the transformation that maps triangle PQR with vertices P(2,4), Q(6,4), R(6,7) to P\'(1,2), Q\'(3,2), R\'(3,3.5).',
      steps: [
        {
          prompt: 'What has happened to the size of the shape?',
          hint1: 'PQ = 4 units. P\'Q\' = 2 units.',
          hint2: 'The shape has shrunk. Scale factor = 2÷4 = 0.5.',
          hint3: 'Scale factor = 0.5 (or ½).',
          answer: 0.5,
          tolerance: 0,
          unit: '',
          explanation: 'Lengths halved: SF = 0.5.',
        },
        {
          prompt: 'What type of transformation is this?',
          hint1: 'Shape changes size but remains similar.',
          hint2: 'Enlargement (with SF < 1, it reduces in size).',
          hint3: 'Enlargement, scale factor 0.5.',
          answer: 0,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'Enlargement, scale factor 0.5',
          explanation: 'An enlargement with SF=0.5 reduces size.',
        },
        {
          prompt: 'Find the centre of enlargement. Extend lines PP\', QQ\' — they meet at the centre.',
          hint1: 'P=(2,4), P\'=(1,2). The line passes through... extend backward.',
          hint2: 'Line through P and P\': slope = (4−2)/(2−1) = 2. Through (0,0): y=2x.',
          hint3: 'Centre = (0, 0).',
          answer: 0,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'Centre of enlargement = (0, 0)',
          explanation: 'Lines from P and P\', Q and Q\' converge at origin (0,0).',
        },
      ],
      workedExample: {
        question: 'A(4,6) maps to A\'(2,3). What transformation?',
        steps: ['Coordinates halved → SF=0.5', 'Lines through A,A\' pass through (0,0)', 'Enlargement SF=0.5 from (0,0)'],
      },
      sampleAnswer: {
        grade4: 'Enlargement, scale factor 0.5, centre (0,0).',
        grade6: 'Lengths halved → SF=0.5. Lines AA\' extended meet at origin. Enlargement SF=0.5 from (0,0).',
        grade8: 'SF=P\'Q\'/PQ=2/4=0.5. Centre at origin. Enlargement, SF=½, centre (0,0).',
      },
      examinerTip: 'Always state: type, scale factor, and centre for an enlargement. SF < 1 = reduction.',
      auditStatus: 'pending',
    },
    {
      id: 'tr-B04',
      subtopic: 'geo-transformations',
      band: 'B',
      marks: 3,
      question: 'Reflect the triangle with vertices (2,3), (4,3), (4,6) in the line y = x. Give the image vertices.',
      steps: [
        {
          prompt: 'Reflection in y = x: what rule maps (x, y) to the image?',
          hint1: 'The x and y coordinates swap.',
          hint2: '(x, y) → (y, x).',
          hint3: '(x, y) → (y, x).',
          answer: 0,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: '(x, y) → (y, x)',
          explanation: 'Reflection in y=x swaps coordinates.',
        },
        {
          prompt: 'Find the image of (2, 3).',
          hint1: 'Swap x and y.',
          hint2: '(3, 2).',
          hint3: '(3, 2).',
          answer: 3,
          tolerance: 0,
          unit: '',
          explanation: '(2,3)→(3,2).',
          displayAnswer: '(3, 2)',
        },
        {
          prompt: 'Find the images of (4,3) and (4,6). Enter the y-coordinate of the image of (4,6).',
          hint1: '(4,3)→(3,4). (4,6)→(6,4).',
          hint2: 'Image of (4,6) is (6,4). y-coordinate = 4.',
          hint3: '4.',
          answer: 4,
          tolerance: 0,
          unit: '',
          explanation: 'Images: (3,2), (3,4), (4,6)→(6,4).',
          displayAnswer: 'Images: (3,2), (3,4), (6,4)',
        },
      ],
      workedExample: {
        question: 'Reflect (1,5), (3,5), (3,8) in y=x.',
        steps: ['(x,y)→(y,x)', 'Images: (5,1), (5,3), (8,3)'],
      },
      sampleAnswer: {
        grade4: 'Images: (3,2), (3,4), (6,4).',
        grade6: 'y=x reflection: swap coords. (2,3)→(3,2), (4,3)→(3,4), (4,6)→(6,4).',
        grade8: '(x,y)→(y,x). Images: (3,2),(3,4),(6,4).',
      },
      examinerTip: 'Reflection in y = x: swap the x and y coordinates.',
      auditStatus: 'pending',
    },
    {
      id: 'tr-B05',
      subtopic: 'geo-transformations',
      band: 'B',
      marks: 3,
      question: 'Rotate point (5, 2) by 90° clockwise about the centre (1, 1). Give the image coordinates.',
      steps: [
        {
          prompt: 'Find the vector from centre (1,1) to point (5,2).',
          hint1: '(5−1, 2−1) = (4, 1).',
          hint2: 'Vector = (4, 1).',
          hint3: '(4, 1).',
          answer: 0,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'Vector from centre = (4, 1)',
          explanation: 'Vector = (5−1, 2−1) = (4, 1).',
        },
        {
          prompt: '90° clockwise rotation: (a, b) → (b, −a). Apply to (4, 1).',
          hint1: '(a,b)→(b,−a). (4,1)→(1,−4).',
          hint2: 'Rotated vector = (1, −4).',
          hint3: '(1, −4).',
          answer: -4,
          tolerance: 0,
          unit: '',
          explanation: '90° CW: (4,1)→(1,−4).',
          displayAnswer: 'Rotated vector = (1, −4)',
        },
        {
          prompt: 'Add the rotated vector to the centre (1,1). Find the image.',
          hint1: 'Image = (1+1, 1+(−4)).',
          hint2: '(2, −3).',
          hint3: '(2, −3).',
          answer: -3,
          tolerance: 0,
          unit: '',
          explanation: 'Image = (1+1, 1−4) = (2, −3).',
          displayAnswer: 'Image = (2, −3)',
        },
      ],
      workedExample: {
        question: 'Rotate (4, 5) 90° CW about centre (2, 3).',
        steps: ['Vector=(2,2). 90° CW: (2,2)→(2,−2).', 'Image=(2+2, 3+(−2))=(4,1)'],
      },
      sampleAnswer: {
        grade4: 'Image = (2, −3).',
        grade6: 'Vector=(4,1). 90°CW→(1,−4). Image=(2,−3).',
        grade8: 'V=(4,1). CW90: (a,b)→(b,−a)=(1,−4). Image=centre+V\'=(2,−3).',
      },
      examinerTip: '90° clockwise: (a,b)→(b,−a). 90° anticlockwise: (a,b)→(−b,a).',
      auditStatus: 'pending',
    },
    {
      id: 'tr-B06',
      subtopic: 'geo-transformations',
      band: 'B',
      marks: 4,
      question: 'Triangle A has vertices (1,0), (3,0), (3,2). It is first reflected in the x-axis to give B, then B is translated by vector (−4, 1) to give C. Find the vertices of C.',
      steps: [
        {
          prompt: 'Reflect A in the x-axis: (x,y)→(x,−y).',
          hint1: '(1,0)→(1,0). (3,0)→(3,0). (3,2)→(3,−2).',
          hint2: 'B: (1,0), (3,0), (3,−2).',
          hint3: 'B = {(1,0),(3,0),(3,−2)}.',
          answer: -2,
          tolerance: 0,
          unit: '',
          explanation: 'B: (1,0), (3,0), (3,−2).',
          displayAnswer: 'B: (1,0), (3,0), (3,−2)',
        },
        {
          prompt: 'Translate B by (−4, 1). Apply to (1, 0).',
          hint1: '(1+(−4), 0+1) = (−3, 1).',
          hint2: '(−3, 1).',
          hint3: '(−3, 1).',
          answer: -3,
          tolerance: 0,
          unit: '',
          explanation: '(1,0)+(−4,1)=(−3,1).',
          displayAnswer: "(1,0) → (−3,1)",
        },
        {
          prompt: 'Apply translation to (3, 0).',
          hint1: '(3+(−4), 0+1) = (−1, 1).',
          hint2: '(−1, 1).',
          hint3: '(−1, 1).',
          answer: -1,
          tolerance: 0,
          unit: '',
          explanation: '(3,0)+(−4,1)=(−1,1).',
          displayAnswer: '(3,0) → (−1,1)',
        },
        {
          prompt: 'Apply translation to (3, −2). Give final vertex.',
          hint1: '(3+(−4), −2+1) = (−1, −1).',
          hint2: '(−1, −1).',
          hint3: '(−1, −1).',
          answer: -1,
          tolerance: 0,
          unit: '',
          explanation: 'C vertices: (−3,1), (−1,1), (−1,−1).',
          displayAnswer: 'C: (−3,1), (−1,1), (−1,−1)',
        },
      ],
      workedExample: {
        question: '(2,1),(4,1),(4,3) reflected in x-axis then translated (−2,3). Final vertices?',
        steps: ['Reflect: (2,−1),(4,−1),(4,−3)', 'Translate: (0,2),(2,2),(2,0)'],
      },
      sampleAnswer: {
        grade4: 'C: (−3,1),(−1,1),(−1,−1).',
        grade6: 'Reflect in x-axis: B=(1,0),(3,0),(3,−2). Translate: C=(−3,1),(−1,1),(−1,−1).',
        grade8: 'Reflect: y→−y. Translate: add (−4,1). C=(−3,1),(−1,1),(−1,−1).',
      },
      examinerTip: 'For combined transformations, apply them in order — the result is path-dependent.',
      auditStatus: 'pending',
    },
    {
      id: 'tr-C01',
      subtopic: 'geo-transformations',
      band: 'C',
      marks: 4,
      question: 'Triangle ABC has vertices A(−2, 1), B(2, 1), C(0, 4). It is enlarged by scale factor −2 from centre (0, 0). Find the image and describe what happens with a negative scale factor.',
      steps: [
        {
          prompt: 'Apply SF = −2: multiply each coordinate by −2.',
          hint1: 'A(−2,1)→(4,−2). B(2,1)→(−4,−2). C(0,4)→(0,−8).',
          hint2: 'A\'=(4,−2), B\'=(−4,−2), C\'=(0,−8).',
          hint3: 'Enter 4 (x-coord of A\').',
          answer: 4,
          tolerance: 0,
          unit: '',
          explanation: 'A: (−2,1)×(−2)=(4,−2). B: (2,1)×(−2)=(−4,−2). C: (0,4)×(−2)=(0,−8).',
          displayAnswer: "A'=(4,−2), B'=(−4,−2), C'=(0,−8)",
        },
        {
          prompt: 'How does the size change? (What is |SF|?)',
          hint1: '|−2| = 2.',
          hint2: 'The image is 2 times larger than the original.',
          hint3: 'Twice as large.',
          answer: 2,
          tolerance: 0,
          unit: '',
          explanation: '|SF| = 2, so image is 2× larger.',
        },
        {
          prompt: 'Negative SF also causes a rotation. By how many degrees?',
          hint1: 'A negative scale factor causes a 180° rotation as well as the enlargement.',
          hint2: '180°.',
          hint3: '180°.',
          answer: 180,
          tolerance: 0,
          unit: '°',
          explanation: 'Negative SF = enlargement + 180° rotation about the centre.',
        },
        {
          prompt: 'Are the original triangle and its image on the same or opposite sides of the centre?',
          hint1: 'Original: above x-axis. Image: below x-axis.',
          hint2: 'Opposite sides of the centre (0,0).',
          hint3: 'Enter 1 for opposite sides.',
          answer: 1,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'Opposite sides of the centre — the image is rotated 180°',
          explanation: 'Negative SF maps points through the centre to the opposite side.',
        },
      ],
      workedExample: {
        question: 'Enlarge (1,2) by SF=−3 from origin.',
        steps: ['(1,2)×(−3)=(−3,−6)', 'Image is 3× larger and on opposite side of origin (rotated 180°)'],
      },
      sampleAnswer: {
        grade4: "A'=(4,−2), B'=(−4,−2), C'=(0,−8). Image is larger and rotated.",
        grade6: 'SF=−2: multiply all coords by −2. Image is 2× larger, rotated 180° about origin.',
        grade8: 'SF=−2: image 2× size, rotated 180°. A\'=(4,−2), B\'=(−4,−2), C\'=(0,−8).',
      },
      examinerTip: 'A negative scale factor = enlargement × 180° rotation. The image appears on the opposite side of the centre.',
      auditStatus: 'pending',
    },
    {
      id: 'tr-C02',
      subtopic: 'geo-transformations',
      band: 'C',
      marks: 4,
      question: 'Point P(3, 1) is transformed by the matrix M = [[0,−1],[1,0]]. Find the image P\'. Then find the image of P(3,1) under M². Describe both transformations.',
      steps: [
        {
          prompt: 'Apply M to (3, 1): multiply [[0,−1],[1,0]] × (3,1). New x = 0×3 + (−1)×1.',
          hint1: 'New x = 0(3)+(−1)(1) = −1.',
          hint2: 'New y = 1(3)+0(1) = 3.',
          hint3: "P' = (−1, 3).",
          answer: -1,
          tolerance: 0,
          unit: '',
          explanation: "P': x=0(3)−1(1)=−1, y=1(3)+0(1)=3. P'=(−1,3).",
          displayAnswer: "P' = (−1, 3)",
        },
        {
          prompt: 'What rotation does M represent? (−1, 3) from (3, 1)?',
          hint1: '(x,y)→(−y,x) is 90° anticlockwise.',
          hint2: '3→−1: the x-coord became −y. 1→3: y-coord became x.',
          hint3: '90° anticlockwise rotation about origin.',
          answer: 90,
          tolerance: 0,
          unit: '°',
          explanation: 'M represents 90° anticlockwise rotation.',
        },
        {
          prompt: 'Apply M to P\'=(−1,3) to get P\'\'.',
          hint1: 'x=0(−1)+(−1)(3)=−3. y=1(−1)+0(3)=−1.',
          hint2: "P'' = (−3, −1).",
          hint3: '(−3, −1).',
          answer: -3,
          tolerance: 0,
          unit: '',
          explanation: "P''=(−3,−1). This is 180° rotation of original.",
          displayAnswer: "P'' = (−3, −1)",
        },
        {
          prompt: 'M² represents 90°+90°=180° rotation. Check: does (3,1)→(−3,−1) match 180° rotation?',
          hint1: '180° rotation: (x,y)→(−x,−y). (3,1)→(−3,−1).',
          hint2: 'Yes ✓.',
          hint3: 'Enter 1.',
          answer: 1,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'M²=(−3,−1) ✓ — M²=180° rotation',
          explanation: 'M²=180° rotation. (3,1)→(−3,−1) ✓',
        },
      ],
      workedExample: {
        question: 'Apply M=[[0,−1],[1,0]] to (2,0).',
        steps: ['x=0(2)−1(0)=0. y=1(2)+0(0)=2.', "P'=(0,2). M = 90° ACW rotation."],
      },
      sampleAnswer: {
        grade4: "P'=(−1,3). P''=(−3,−1).",
        grade6: 'M×(3,1)=(−1,3): 90° ACW. M²×(3,1)=(−3,−1): 180° rotation.',
        grade8: 'M: 90°ACW. P\'=(−1,3). M²: 180°. P\'\'=(−3,−1). Check: (x,y)→(−x,−y) ✓',
      },
      examinerTip: 'Matrix [[0,−1],[1,0]] represents 90° anticlockwise rotation. M² represents 180°.',
      auditStatus: 'pending',
    },
    {
      id: 'tr-C03',
      subtopic: 'geo-transformations',
      band: 'C',
      marks: 4,
      question: 'Triangle A has vertices (2,1),(4,1),(2,4). It is reflected in the line y = x to give B, then reflected in the x-axis to give C. Describe the single transformation that maps A directly to C.',
      steps: [
        {
          prompt: 'Find B: reflect A in y=x. Apply (x,y)→(y,x).',
          hint1: '(2,1)→(1,2). (4,1)→(1,4). (2,4)→(4,2).',
          hint2: 'B: (1,2),(1,4),(4,2).',
          hint3: 'B = {(1,2),(1,4),(4,2)}.',
          answer: 0,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'B: (1,2), (1,4), (4,2)',
          explanation: 'Reflection in y=x swaps coordinates.',
        },
        {
          prompt: 'Find C: reflect B in x-axis. Apply (x,y)→(x,−y).',
          hint1: '(1,2)→(1,−2). (1,4)→(1,−4). (4,2)→(4,−2).',
          hint2: 'C: (1,−2),(1,−4),(4,−2).',
          hint3: 'C = {(1,−2),(1,−4),(4,−2)}.',
          answer: 0,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'C: (1,−2), (1,−4), (4,−2)',
          explanation: 'Reflection in x-axis: negate y.',
        },
        {
          prompt: 'What single transformation maps (2,1)→(1,−2)? The rule is (x,y)→(y,−x).',
          hint1: '(x,y)→(y,−x) is a 90° clockwise rotation.',
          hint2: 'Check: does (2,1)→(1,−2)? y=1, −x=−2. Yes ✓.',
          hint3: '90° clockwise about origin.',
          answer: 90,
          tolerance: 0,
          unit: '°',
          explanation: '(x,y)→(y,−x) = 90° clockwise rotation about origin.',
        },
        {
          prompt: 'Verify with second vertex: does (4,1)→(1,−4) under 90° CW?',
          hint1: '(4,1)→(y,−x)=(1,−4). ✓',
          hint2: 'Yes, confirmed.',
          hint3: 'Enter 1.',
          answer: 1,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: '(4,1)→(1,−4) ✓ — 90° clockwise rotation confirmed',
          explanation: 'Single transformation: 90° clockwise rotation about the origin.',
        },
      ],
      workedExample: {
        question: 'Reflect in y=x then x-axis. Rule (x,y)→?',
        steps: ['y=x: (x,y)→(y,x). Then x-axis: (y,x)→(y,−x).', 'Combined: (x,y)→(y,−x) = 90° CW rotation'],
      },
      sampleAnswer: {
        grade4: 'The single transformation is a 90° clockwise rotation about the origin.',
        grade6: 'A→B (y=x reflection): swap coords. B→C (x-axis): negate y. Combined: (x,y)→(y,−x) = 90° CW rotation.',
        grade8: 'Composite: (x,y)→(y,x)→(y,−x). Rule=(y,−x)=90° CW rotation about origin.',
      },
      examinerTip: 'Two reflections in perpendicular lines produce a rotation. The angle of rotation = 2 × angle between mirror lines.',
      auditStatus: 'pending',
    },
    {
      id: 'tr-C04',
      subtopic: 'geo-transformations',
      band: 'C',
      marks: 4,
      question: 'Shape A has vertices (1,2),(3,2),(3,5). It is enlarged by SF=2 from centre (−1,0) to give B. It is also reflected in the line x=2 to give C. Are shapes B and C congruent? Explain.',
      steps: [
        {
          prompt: 'Find vertices of B (enlarged by SF=2 from (−1,0)).',
          hint1: 'Vector from (−1,0) to (1,2) = (2,2). ×2=(4,4). Add (−1,0): (3,4).',
          hint2: 'Similarly: (3,2)→(3+4,2+4)=(7,4). (3,5)→(7,10).',
          hint3: "B: (3,4),(7,4),(7,10).",
          answer: 0,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: "B: (3,4), (7,4), (7,10)",
          explanation: 'B: (3,4),(7,4),(7,10).',
        },
        {
          prompt: 'Find vertices of C (reflected in x=2). Rule: x→ 2×2−x = 4−x.',
          hint1: '(1,2)→(3,2). (3,2)→(1,2). (3,5)→(1,5).',
          hint2: 'C: (3,2),(1,2),(1,5).',
          hint3: 'C = {(3,2),(1,2),(1,5)}.',
          answer: 0,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'C: (3,2), (1,2), (1,5)',
          explanation: 'Reflection in x=2: x→4−x.',
        },
        {
          prompt: 'Find the side length of base in A: from (1,2) to (3,2). Length = ?',
          hint1: '3−1 = 2 units.',
          hint2: '2 units.',
          hint3: '2.',
          answer: 2,
          tolerance: 0,
          unit: 'units',
          explanation: 'Base of A = 2. Base of C = 2 (same). Base of B = 4 (doubled).',
        },
        {
          prompt: 'Are B and C congruent to each other? Enter 1 for yes, 2 for no.',
          hint1: 'B has base 4; C has base 2. Different sizes.',
          hint2: 'B is larger than C — they are similar but not congruent.',
          hint3: 'No — enter 2.',
          answer: 2,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'No — B is twice the size of C. B ~ A ~ C but B ≇ C',
          explanation: 'B has SF=2 applied; C is a reflection (same size). B and C are similar but not congruent.',
        },
      ],
      workedExample: {
        question: 'Enlargement vs reflection: which preserves size?',
        steps: ['Reflection: isometry — size preserved (congruent).', 'Enlargement (SF≠1): size changes — similar, not congruent.'],
      },
      sampleAnswer: {
        grade4: 'B and C are not congruent. B is bigger (SF=2).',
        grade6: 'Reflection preserves size so C≅A. Enlargement doubles size so B is twice A. B≇C.',
        grade8: 'C is congruent to A (reflection = isometry). B is similar to A with SF=2. B≇C as their sides differ by factor 2.',
      },
      examinerTip: 'Reflections, rotations and translations preserve size (isometries). Enlargements (SF≠±1) change size.',
      auditStatus: 'pending',
    },
"""

with open(FILE, encoding='utf-8') as f:
    content = f.read()
pos = content.find(MARKER)
if pos < 0:
    print('MARKER NOT FOUND')
else:
    print(f'Inserting at char {pos}')
    with open(FILE, 'w', encoding='utf-8') as f:
        f.write(content[:pos] + NEW + content[pos:])
    print('Done - geo_q4 (12 transformation questions)')
