FILE = r'C:\Users\jason\OneDrive\Documents\GitHub\mabel-gcse\js\maths-questions.js'
MARKER = "\n\n    // ══════════════════════════════════════════════════════════\n    // AREA & VOLUME"

NEW = """    {
      id: 'shp-A03',
      subtopic: 'geo-shapes',
      band: 'A',
      marks: 2,
      question: 'Two triangles share two equal sides of 6 cm and 9 cm with an included angle of 50°. Which congruence condition applies?',
      steps: [
        {
          prompt: 'What is the name of the congruence condition when two sides and the included angle are equal?',
          hint1: 'Side — Angle — Side.',
          hint2: 'The angle must be between the two sides.',
          hint3: 'SAS.',
          answer: 0,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'SAS (Side-Angle-Side)',
          explanation: 'Two sides and the included angle equal → SAS congruence.',
        },
        {
          prompt: 'Are the triangles congruent? Enter 1 for yes.',
          hint1: 'SAS is a valid congruence condition.',
          hint2: 'Yes — the triangles are congruent.',
          hint3: 'Enter 1.',
          answer: 1,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'Yes — SAS guarantees congruence',
          explanation: 'SAS is a valid congruence condition, so the triangles are congruent.',
        },
      ],
      workedExample: {
        question: 'Two triangles have angles 40°, 70°, 70° and a side of 8 cm between the 40° and 70° angles. Which condition?',
        steps: ['Angle-Side-Angle (the side is between the two known angles)', 'Condition: <strong>ASA</strong>'],
      },
      sampleAnswer: {
        grade4: 'SAS — two sides and the included angle are equal.',
        grade6: 'Two equal sides (6 cm, 9 cm) with the angle between them equal (50°). Condition: SAS.',
        grade8: 'SAS (Side-Angle-Side): two sides and the included angle. Sufficient for congruence.',
      },
      examinerTip: 'The angle must be BETWEEN the two sides for SAS. If it is not included, the condition does not guarantee congruence.',
      auditStatus: 'pending',
    },
    {
      id: 'shp-A04',
      subtopic: 'geo-shapes',
      band: 'A',
      marks: 2,
      question: 'Two similar shapes have a length scale factor of 4. What is the area scale factor?',
      steps: [
        {
          prompt: 'The area scale factor = (length scale factor)². Calculate it.',
          hint1: 'Area SF = 4².',
          hint2: '4² = 16.',
          hint3: '16.',
          answer: 16,
          tolerance: 0,
          unit: '',
          explanation: 'Area scale factor = 4² = 16.',
        },
        {
          prompt: 'If the smaller shape has area 5 cm², find the area of the larger shape.',
          hint1: 'Larger area = smaller area × area scale factor.',
          hint2: '5 × 16 = ?',
          hint3: '80 cm².',
          answer: 80,
          tolerance: 0,
          unit: 'cm²',
          explanation: 'Area = 5 × 16 = 80 cm².',
        },
      ],
      workedExample: {
        question: 'Length SF = 3. Smaller area = 7 cm². Find larger area.',
        steps: ['Area SF = 3² = 9', 'Larger area = 7 × 9 = <strong>63 cm²</strong>'],
      },
      sampleAnswer: {
        grade4: 'Area SF = 16. Larger area = 80 cm².',
        grade6: 'Area scale factor = 4² = 16. Larger area = 5 × 16 = 80 cm².',
        grade8: 'Area SF = (length SF)² = 16. Larger area = 5×16 = 80 cm².',
      },
      examinerTip: 'Area scales by the square of the length ratio. Never apply the length scale factor to areas directly.',
      auditStatus: 'pending',
    },
    {
      id: 'shp-A05',
      subtopic: 'geo-shapes',
      band: 'A',
      marks: 2,
      question: 'Two similar rectangles have lengths 5 cm and 15 cm. The smaller has width 3 cm. Find the width of the larger.',
      steps: [
        {
          prompt: 'Find the length scale factor.',
          hint1: 'Scale factor = larger length ÷ smaller length.',
          hint2: '15 ÷ 5 = ?',
          hint3: 'Scale factor = 3.',
          answer: 3,
          tolerance: 0,
          unit: '',
          explanation: 'Scale factor = 15/5 = 3.',
        },
        {
          prompt: 'Find the width of the larger rectangle.',
          hint1: 'Width scales by the same factor.',
          hint2: '3 × 3 = ?',
          hint3: '9 cm.',
          answer: 9,
          tolerance: 0,
          unit: 'cm',
          explanation: 'Larger width = 3 × 3 = 9 cm.',
        },
      ],
      workedExample: {
        question: 'Similar rectangles: lengths 4 cm and 12 cm. Smaller width = 2 cm. Find larger width.',
        steps: ['Scale factor = 12÷4 = 3', 'Larger width = 2×3 = <strong>6 cm</strong>'],
      },
      sampleAnswer: {
        grade4: 'Width = 9 cm.',
        grade6: 'Scale factor = 15÷5 = 3. Larger width = 3×3 = 9 cm.',
        grade8: 'SF = 3. All lengths scale by same factor. Width = 3×3 = 9 cm.',
      },
      examinerTip: 'In similar shapes, all corresponding lengths share the same scale factor.',
      auditStatus: 'pending',
    },
    {
      id: 'shp-B02',
      subtopic: 'geo-shapes',
      band: 'B',
      marks: 3,
      question: 'In triangle ABC, DE is parallel to BC where D is on AB and E is on AC. AD = 4 cm, DB = 6 cm and BC = 15 cm. Find DE.',
      steps: [
        {
          prompt: 'Find the scale factor from triangle ADE to triangle ABC.',
          hint1: 'AB = AD + DB = 4 + 6 = 10 cm.',
          hint2: 'Scale factor = AD/AB = 4/10.',
          hint3: '0.4.',
          answer: 0.4,
          tolerance: 0,
          unit: '',
          explanation: 'SF = AD/AB = 4/10 = 0.4.',
        },
        {
          prompt: 'Find DE using the scale factor.',
          hint1: 'DE = BC × scale factor.',
          hint2: '15 × 0.4 = ?',
          hint3: '6 cm.',
          answer: 6,
          tolerance: 0,
          unit: 'cm',
          explanation: 'DE = 15 × 0.4 = 6 cm.',
        },
        {
          prompt: 'State the theorem used.',
          hint1: 'DE is parallel to BC, so triangle ADE is similar to triangle ABC.',
          hint2: 'Basic Proportionality Theorem (or similar triangles).',
          hint3: 'Enter 1.',
          answer: 1,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'Triangle ADE ~ Triangle ABC (DE || BC, AAA similarity)',
          explanation: 'DE || BC → equiangular triangles → similar by AA.',
        },
      ],
      workedExample: {
        question: 'AD=3, DB=9, BC=20. DE is parallel to BC. Find DE.',
        steps: ['AB=12. SF=3/12=0.25', 'DE=20×0.25=<strong>5 cm</strong>'],
      },
      sampleAnswer: {
        grade4: 'DE = 6 cm.',
        grade6: 'AB=10. SF=4/10=0.4. DE=15×0.4=6 cm.',
        grade8: 'SF=AD/AB=0.4. DE=BC×0.4=6 cm. (ADE ~ ABC by AA similarity)',
      },
      examinerTip: 'When a line is parallel to one side of a triangle it creates a smaller similar triangle. Find the scale factor using corresponding sides.',
      auditStatus: 'pending',
    },
    {
      id: 'shp-B03',
      subtopic: 'geo-shapes',
      band: 'B',
      marks: 3,
      question: 'Two similar solids have volume ratio 27 : 125. Find the length scale factor and the surface area ratio.',
      steps: [
        {
          prompt: 'Find the length scale factor from the volume ratio. Volume ratio = (length SF)³.',
          hint1: '∛27 : ∛125 = ?',
          hint2: '3 : 5.',
          hint3: 'Length SF = 3:5.',
          answer: 0,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'Length scale factor = 3:5',
          explanation: 'Length SF = ∛27 : ∛125 = 3 : 5.',
        },
        {
          prompt: 'Find the surface area ratio. Area ratio = (length SF)².',
          hint1: '3² : 5² = ?',
          hint2: '9 : 25.',
          hint3: '9:25.',
          answer: 25,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'Surface area ratio = 9:25',
          explanation: 'Area ratio = 3² : 5² = 9 : 25.',
        },
        {
          prompt: 'If the smaller solid has surface area 63 cm², find the larger solid\'s surface area.',
          hint1: 'Larger SA = 63 × (25/9).',
          hint2: '63 × 25/9 = 1575/9.',
          hint3: '175 cm².',
          answer: 175,
          tolerance: 0,
          unit: 'cm²',
          explanation: '63 × 25/9 = 175 cm².',
        },
      ],
      workedExample: {
        question: 'Volume ratio 8:27. Smaller SA = 24 cm². Find larger SA.',
        steps: ['Length SF = 2:3', 'Area ratio = 4:9', 'Larger SA = 24×9/4 = <strong>54 cm²</strong>'],
      },
      sampleAnswer: {
        grade4: 'Length SF = 3:5. Area ratio = 9:25. Larger SA = 175 cm².',
        grade6: 'Volume ratio 27:125 → length SF 3:5. Area ratio 9:25. Larger SA = 63×25/9 = 175 cm².',
        grade8: 'V ratio = k³ → k=3/5. Area ratio = k² = 9/25. SA = 63×25/9 = 175 cm².',
      },
      examinerTip: 'Volume → cube root → length ratio → square → area ratio.',
      auditStatus: 'pending',
    },
    {
      id: 'shp-B04',
      subtopic: 'geo-shapes',
      band: 'B',
      marks: 3,
      question: 'Two similar cones have radii 3 cm and 5 cm. The smaller has volume 36π cm³. Find the volume of the larger cone.',
      steps: [
        {
          prompt: 'Find the length scale factor.',
          hint1: 'SF = larger radius ÷ smaller radius.',
          hint2: '5 ÷ 3.',
          hint3: '5/3.',
          answer: 0,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'Length scale factor = 5/3',
          explanation: 'SF = 5/3.',
        },
        {
          prompt: 'Find the volume scale factor = (length SF)³.',
          hint1: '(5/3)³ = 125/27.',
          hint2: '≈ 4.63.',
          hint3: '125/27.',
          answer: 0,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'Volume SF = (5/3)³ = 125/27',
          explanation: 'Volume SF = (5/3)³ = 125/27.',
        },
        {
          prompt: 'Find the volume of the larger cone.',
          hint1: 'Larger volume = 36π × 125/27.',
          hint2: '36 × 125/27 = 4500/27 = 500/3.',
          hint3: '500π/3 cm³ ≈ 523.6 cm³.',
          answer: 523.6,
          tolerance: 0.5,
          unit: 'cm³',
          explanation: 'V = 36π × 125/27 = (500/3)π ≈ 523.6 cm³.',
        },
      ],
      workedExample: {
        question: 'Similar cones: radii 2 cm and 6 cm. Smaller volume = 10π cm³. Find larger volume.',
        steps: ['SF = 3. Volume SF = 27.', 'Larger V = 10π × 27 = <strong>270π cm³</strong>'],
      },
      sampleAnswer: {
        grade4: 'Volume SF = (5/3)³ = 125/27. V = 36π × 125/27 ≈ 523.6 cm³.',
        grade6: 'SF=5/3. Vol SF=(5/3)³=125/27. V=36π×125/27=(500/3)π≈523.6 cm³.',
        grade8: 'V = 36π × (5/3)³ = 36π × 125/27 = (500π)/3 ≈ 523.6 cm³.',
      },
      examinerTip: 'For volume in similar solids, cube the length scale factor — never square it.',
      auditStatus: 'pending',
    },
    {
      id: 'shp-B05',
      subtopic: 'geo-shapes',
      band: 'B',
      marks: 3,
      question: 'Two similar triangles: the larger has area 75 cm² and the smaller has area 27 cm². A side of the smaller triangle is 6 cm. Find the corresponding side of the larger.',
      steps: [
        {
          prompt: 'Find the area scale factor.',
          hint1: 'Area SF = larger area ÷ smaller area.',
          hint2: '75 ÷ 27 = 25/9.',
          hint3: '25/9.',
          answer: 0,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'Area SF = 75/27 = 25/9',
          explanation: 'Area SF = 75/27 = 25/9.',
        },
        {
          prompt: 'Find the length scale factor = √(area SF).',
          hint1: '√(25/9) = ?',
          hint2: '5/3.',
          hint3: '5/3.',
          answer: 0,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'Length SF = √(25/9) = 5/3',
          explanation: 'Length SF = √(25/9) = 5/3.',
        },
        {
          prompt: 'Find the corresponding side of the larger triangle.',
          hint1: 'Larger side = 6 × (5/3).',
          hint2: '6 × 5/3 = 10.',
          hint3: '10 cm.',
          answer: 10,
          tolerance: 0,
          unit: 'cm',
          explanation: 'Side = 6 × 5/3 = 10 cm.',
        },
      ],
      workedExample: {
        question: 'Areas: large=48 cm², small=12 cm². Smaller side=5 cm. Find larger side.',
        steps: ['Area SF=4. Length SF=√4=2.', 'Larger side = 5×2 = <strong>10 cm</strong>'],
      },
      sampleAnswer: {
        grade4: 'Larger side = 10 cm.',
        grade6: 'Area SF=25/9. Length SF=5/3. Larger side=6×5/3=10 cm.',
        grade8: 'Length SF=√(75/27)=5/3. Larger side=6×5/3=10 cm.',
      },
      examinerTip: 'Take the square root of the area ratio to get the length ratio.',
      auditStatus: 'pending',
    },
    {
      id: 'shp-B06',
      subtopic: 'geo-shapes',
      band: 'B',
      marks: 3,
      question: 'A small model of a building has height 8 cm and volume 160 cm³. The real building is 20 m tall. Find the volume of the real building in m³.',
      steps: [
        {
          prompt: 'Convert heights to the same unit. Find the length scale factor.',
          hint1: 'Heights: 8 cm and 2000 cm (20 m).',
          hint2: 'SF = 2000 ÷ 8 = 250.',
          hint3: 'Length SF = 250.',
          answer: 250,
          tolerance: 0,
          unit: '',
          explanation: 'SF = 2000/8 = 250.',
        },
        {
          prompt: 'Find the volume scale factor = SF³.',
          hint1: '250³ = 250 × 250 × 250.',
          hint2: '250³ = 15 625 000.',
          hint3: '15 625 000.',
          answer: 15625000,
          tolerance: 0,
          unit: '',
          explanation: 'Volume SF = 250³ = 15 625 000.',
        },
        {
          prompt: 'Find the volume of the real building in cm³, then convert to m³.',
          hint1: 'Volume = 160 × 15 625 000 = 2 500 000 000 cm³.',
          hint2: '1 m³ = 1 000 000 cm³. ÷ 1 000 000.',
          hint3: '2500 m³.',
          answer: 2500,
          tolerance: 0,
          unit: 'm³',
          explanation: '160 × 15 625 000 = 2.5×10⁹ cm³ = 2500 m³.',
        },
      ],
      workedExample: {
        question: 'Model height 5 cm, volume 50 cm³. Real height 10 m. Real volume in m³?',
        steps: ['SF = 1000/5=200. Volume SF=200³=8 000 000.', 'Volume=50×8 000 000=400 000 000 cm³=<strong>400 m³</strong>'],
      },
      sampleAnswer: {
        grade4: 'SF=250. Volume SF=250³. Volume=2500 m³.',
        grade6: 'SF=250. Vol SF=15 625 000. Vol=160×15 625 000 cm³=2500 m³.',
        grade8: 'SF=250. V=160×250³ cm³=2.5×10⁹ cm³÷10⁶=2500 m³.',
      },
      examinerTip: 'When converting volumes between cm³ and m³, remember 1 m³ = 1 000 000 cm³ (100³).',
      auditStatus: 'pending',
    },
    {
      id: 'shp-C01',
      subtopic: 'geo-shapes',
      band: 'C',
      marks: 4,
      question: 'Two similar pyramids have surface areas 36 cm² and 100 cm². The larger pyramid has volume 500 cm³. Find the volume of the smaller pyramid.',
      steps: [
        {
          prompt: 'Find the area scale factor.',
          hint1: 'Area SF = 36/100 = 9/25.',
          hint2: '9/25.',
          hint3: '9/25.',
          answer: 0,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'Area SF = 36/100 = 9/25',
          explanation: 'Area SF = 36/100 = 9/25.',
        },
        {
          prompt: 'Find the length scale factor.',
          hint1: 'Length SF = √(area SF) = √(9/25).',
          hint2: '3/5.',
          hint3: '3/5.',
          answer: 0,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'Length SF = 3/5',
          explanation: 'Length SF = √(9/25) = 3/5.',
        },
        {
          prompt: 'Find the volume scale factor.',
          hint1: 'Volume SF = (length SF)³ = (3/5)³.',
          hint2: '27/125.',
          hint3: '27/125.',
          answer: 0,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'Volume SF = (3/5)³ = 27/125',
          explanation: 'Volume SF = 27/125.',
        },
        {
          prompt: 'Find the volume of the smaller pyramid.',
          hint1: 'Smaller volume = larger volume × (27/125).',
          hint2: '500 × 27/125 = ?',
          hint3: '108 cm³.',
          answer: 108,
          tolerance: 0,
          unit: 'cm³',
          explanation: 'V = 500 × 27/125 = 108 cm³.',
        },
      ],
      workedExample: {
        question: 'Similar cones: SAs 16 cm² and 36 cm². Larger volume = 270 cm³. Find smaller volume.',
        steps: ['Area SF=16/36=4/9. Length SF=2/3. Volume SF=8/27.', 'V=270×8/27=<strong>80 cm³</strong>'],
      },
      sampleAnswer: {
        grade4: 'Length SF=3/5. Volume SF=27/125. V=108 cm³.',
        grade6: 'Area SF=9/25. Length SF=3/5. Vol SF=27/125. V=500×27/125=108 cm³.',
        grade8: 'SA ratio → length ratio (√) → vol ratio (³). 9/25→3/5→27/125. V=500×27/125=108 cm³.',
      },
      examinerTip: 'Chain: area ratio → √ → length ratio → ³ → volume ratio. Never skip steps.',
      auditStatus: 'pending',
    },
    {
      id: 'shp-C02',
      subtopic: 'geo-shapes',
      band: 'C',
      marks: 4,
      question: 'Prove that triangles ABE and CDE are congruent, given that AB is parallel to CD, AB = CD, and E is the intersection of AC and BD.',
      steps: [
        {
          prompt: 'State the equal angles from the parallel lines AB and CD.',
          hint1: 'AB || CD, so alternate angles are equal.',
          hint2: '∠ABE = ∠CDE and ∠BAE = ∠DCE (alternate angles).',
          hint3: 'Enter 1.',
          answer: 1,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: '∠ABE = ∠CDE and ∠BAE = ∠DCE (alternate angles, AB || CD)',
          explanation: 'Alternate angles are equal when lines are parallel.',
        },
        {
          prompt: 'State the equal sides.',
          hint1: 'AB = CD is given.',
          hint2: 'AB = CD.',
          hint3: 'Enter 1.',
          answer: 1,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'AB = CD (given)',
          explanation: 'AB = CD is given in the question.',
        },
        {
          prompt: 'Which congruence condition applies?',
          hint1: 'We have two angles and the side between them.',
          hint2: 'Angle-Side-Angle.',
          hint3: 'ASA.',
          answer: 0,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'ASA (Angle-Side-Angle)',
          explanation: 'Two angles and the included side → ASA.',
        },
        {
          prompt: 'State the conclusion.',
          hint1: 'ABE ≅ CDE by ASA.',
          hint2: 'Therefore triangles ABE and CDE are congruent.',
          hint3: 'Enter 1.',
          answer: 1,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: '△ABE ≅ △CDE (ASA)',
          explanation: '∠ABE=∠CDE, AB=CD, ∠BAE=∠DCE → ASA → △ABE ≅ △CDE.',
        },
      ],
      workedExample: {
        question: 'Prove △AOB ≅ △COD if O is midpoint of both AC and BD.',
        steps: ['AO=CO and BO=DO (midpoints)', '∠AOB=∠COD (vertically opposite)', 'SAS → △AOB ≅ △COD'],
      },
      sampleAnswer: {
        grade4: 'ASA: ∠ABE=∠CDE, AB=CD, ∠BAE=∠DCE. Triangles are congruent.',
        grade6: 'AB∥CD → alternate angles: ∠ABE=∠CDE and ∠BAE=∠DCE. AB=CD (given). ASA → △ABE≅△CDE.',
        grade8: 'In △ABE and △CDE: ∠ABE=∠CDE (alt ∠s, AB∥CD), AB=CD (given), ∠BAE=∠DCE (alt ∠s). ASA → △ABE≅△CDE.',
      },
      examinerTip: 'In congruence proofs: state each equal element with a reason, then name the condition and the conclusion.',
      auditStatus: 'pending',
    },
    {
      id: 'shp-C03',
      subtopic: 'geo-shapes',
      band: 'C',
      marks: 4,
      question: 'In triangle ABC, D lies on AB and E lies on AC such that DE is parallel to BC. AD = 5 cm, AB = 8 cm and the area of triangle ADE = 25 cm². Find the area of trapezium BCED.',
      steps: [
        {
          prompt: 'Find the length scale factor from triangle ADE to triangle ABC.',
          hint1: 'SF = AD/AB.',
          hint2: '5/8.',
          hint3: '5/8.',
          answer: 0,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'Length SF = 5/8',
          explanation: 'SF = AD/AB = 5/8.',
        },
        {
          prompt: 'Find the area scale factor.',
          hint1: 'Area SF = (5/8)².',
          hint2: '25/64.',
          hint3: '25/64.',
          answer: 0,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'Area SF = (5/8)² = 25/64',
          explanation: 'Area SF = 25/64.',
        },
        {
          prompt: 'Find the area of triangle ABC.',
          hint1: 'Area ADE / Area ABC = 25/64.',
          hint2: 'Area ABC = 25 × 64/25 = 64 cm².',
          hint3: '64 cm².',
          answer: 64,
          tolerance: 0,
          unit: 'cm²',
          explanation: 'Area ABC = 25 ÷ (25/64) = 64 cm².',
        },
        {
          prompt: 'Find the area of trapezium BCED.',
          hint1: 'Area BCED = Area ABC − Area ADE.',
          hint2: '64 − 25 = 39.',
          hint3: '39 cm².',
          answer: 39,
          tolerance: 0,
          unit: 'cm²',
          explanation: 'BCED = 64 − 25 = 39 cm².',
        },
      ],
      workedExample: {
        question: 'AD=3, AB=6, area ADE=9 cm². Find area of trapezium BCED.',
        steps: ['SF=1/2. Area SF=1/4. Area ABC=9×4=36 cm².', 'BCED=36−9=<strong>27 cm²</strong>'],
      },
      sampleAnswer: {
        grade4: 'Area ABC=64 cm². Trapezium=39 cm².',
        grade6: 'SF=5/8. Area SF=25/64. Area ABC=64 cm². BCED=64−25=39 cm².',
        grade8: 'Length SF=5/8. Area SF=25/64. Area ABC=25/(25/64)=64. BCED=64−25=39 cm².',
      },
      examinerTip: 'Find the area of the whole triangle first, then subtract the smaller triangle to find the trapezium.',
      auditStatus: 'pending',
    },
    {
      id: 'shp-C04',
      subtopic: 'geo-shapes',
      band: 'C',
      marks: 4,
      question: 'Two similar cylinders have heights 4 cm and 10 cm. The total surface area of the smaller is 96π cm². Find: (a) the total surface area of the larger, (b) the ratio of their volumes.',
      steps: [
        {
          prompt: 'Find the length scale factor.',
          hint1: 'SF = 10/4 = 5/2.',
          hint2: '5/2.',
          hint3: '2.5.',
          answer: 2.5,
          tolerance: 0,
          unit: '',
          explanation: 'SF = 10/4 = 5/2 = 2.5.',
        },
        {
          prompt: '(a) Find the surface area of the larger cylinder. Area SF = SF².',
          hint1: 'Area SF = (5/2)² = 25/4.',
          hint2: 'Larger SA = 96π × 25/4.',
          hint3: '600π cm².',
          answer: 600,
          tolerance: 0,
          unit: 'π cm²',
          explanation: 'SA = 96π × 25/4 = 600π cm².',
        },
        {
          prompt: '(b) Find the volume scale factor = SF³.',
          hint1: '(5/2)³ = 125/8.',
          hint2: '125/8.',
          hint3: '125/8.',
          answer: 0,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'Volume SF = (5/2)³ = 125/8',
          explanation: 'Volume SF = 125/8.',
        },
        {
          prompt: 'Express the volume ratio (smaller : larger) in the form a : b.',
          hint1: 'Volume ratio = 1 : 125/8 = 8 : 125.',
          hint2: '8:125.',
          hint3: '8:125.',
          answer: 125,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'Volume ratio = 8 : 125',
          explanation: 'Volume ratio = (4/10)³ = (2/5)³ = 8/125, i.e. 8:125.',
        },
      ],
      workedExample: {
        question: 'Similar cylinders: heights 3 cm and 6 cm. Smaller SA=36π. Find larger SA and volume ratio.',
        steps: ['SF=2. Area SF=4. Larger SA=36π×4=<strong>144π cm²</strong>', 'Volume ratio=1:8 (or 8 times bigger)'],
      },
      sampleAnswer: {
        grade4: 'SA=600π cm². Volume ratio=8:125.',
        grade6: 'SF=5/2. Area SF=25/4. SA=96π×25/4=600π. Vol SF=125/8. Ratio=8:125.',
        grade8: 'SF=5/2. SA=96π×(5/2)²=600π cm². Vol ratio=(2/5)³:(1)=(8:125) smaller to larger.',
      },
      examinerTip: 'Volume ratio = (length ratio)³. Express as integers in lowest terms.',
      auditStatus: 'pending',
    },
"""

with open(FILE, encoding='utf-8') as f:
    content = f.read()
pos = content.find(MARKER)
if pos < 0:
    print('MARKER NOT FOUND')
else:
    print(f'Inserting at char {pos}')
    with open(FILE, 'w', encoding='utf-8') as f:
        f.write(content[:pos] + NEW + content[pos:])
    print('Done - geo_q2 (12 shapes questions)')
