FILE = r'C:\Users\jason\OneDrive\Documents\GitHub\mabel-gcse\js\maths-questions.js'
MARKER = "\n\n    // ══════════════════════════════════════════════════════════\n    // TRANSFORMATIONS"

NEW = """    {
      id: 'av-A03',
      subtopic: 'geo-area-volume',
      band: 'A',
      marks: 2,
      question: 'Find the area of a trapezium with parallel sides 8 cm and 12 cm, and height 5 cm.',
      steps: [
        {
          prompt: 'Use the formula: Area = ½ × (a + b) × h.',
          hint1: 'a = 8, b = 12, h = 5.',
          hint2: '½ × (8+12) × 5 = ½ × 20 × 5.',
          hint3: '50 cm².',
          answer: 50,
          tolerance: 0,
          unit: 'cm²',
          explanation: 'Area = ½ × (8+12) × 5 = ½ × 100 = 50 cm².',
        },
      ],
      workedExample: {
        question: 'Trapezium: parallel sides 6 cm and 10 cm, height 4 cm. Find area.',
        steps: ['Area = ½ × (6+10) × 4 = ½ × 64 = <strong>32 cm²</strong>'],
      },
      sampleAnswer: {
        grade4: '50 cm².',
        grade6: 'Area = ½(a+b)h = ½(8+12)×5 = 50 cm².',
        grade8: '½(8+12)×5 = 50 cm².',
      },
      examinerTip: 'The height must be perpendicular to the parallel sides — not the slant side.',
      auditStatus: 'pending',
    },
    {
      id: 'av-A04',
      subtopic: 'geo-area-volume',
      band: 'A',
      marks: 2,
      question: 'Find the volume of a sphere with radius 3 cm. Give your answer in terms of π.',
      steps: [
        {
          prompt: 'Use the formula: V = (4/3)πr³.',
          hint1: 'r = 3, so r³ = 27.',
          hint2: 'V = (4/3) × π × 27.',
          hint3: '36π cm³.',
          answer: 36,
          tolerance: 0,
          unit: '',
          displayAnswer: '36π cm³',
          explanation: 'V = (4/3)π×27 = 36π cm³.',
        },
      ],
      workedExample: {
        question: 'Sphere radius 6 cm. Volume in terms of π.',
        steps: ['V = (4/3)π × 6³ = (4/3)π × 216 = <strong>288π cm³</strong>'],
      },
      sampleAnswer: {
        grade4: '36π cm³.',
        grade6: 'V = (4/3)πr³ = (4/3)π×27 = 36π cm³.',
        grade8: 'V = (4/3)π(3)³ = 36π cm³.',
      },
      examinerTip: 'Cube the radius (not double it): 3³ = 27, not 6.',
      auditStatus: 'pending',
    },
    {
      id: 'av-A05',
      subtopic: 'geo-area-volume',
      band: 'A',
      marks: 2,
      question: 'A sector has radius 10 cm and angle 72°. Find the arc length. Use π = 3.14.',
      steps: [
        {
          prompt: 'Use: arc length = (angle/360) × 2πr.',
          hint1: '(72/360) × 2 × 3.14 × 10.',
          hint2: '0.2 × 62.8 = ?',
          hint3: '12.56 cm.',
          answer: 12.56,
          tolerance: 0.05,
          unit: 'cm',
          explanation: 'Arc = (72/360) × 2 × 3.14 × 10 = 0.2 × 62.8 = 12.56 cm.',
        },
      ],
      workedExample: {
        question: 'Sector: radius 5 cm, angle 90°. Arc length (π=3.14)?',
        steps: ['Arc = (90/360) × 2 × 3.14 × 5 = 0.25 × 31.4 = <strong>7.85 cm</strong>'],
      },
      sampleAnswer: {
        grade4: '12.56 cm.',
        grade6: 'Arc = (72/360) × 2π × 10 = 0.2 × 62.8 = 12.56 cm.',
        grade8: 'Arc = (θ/360) × 2πr = (72/360) × 20π = 4π ≈ 12.56 cm.',
      },
      examinerTip: 'The fraction (angle/360) tells you what fraction of the full circle you have.',
      auditStatus: 'pending',
    },
    {
      id: 'av-B02',
      subtopic: 'geo-area-volume',
      band: 'B',
      marks: 3,
      question: 'Find the volume of a square-based pyramid with base side 6 cm and height 8 cm.',
      steps: [
        {
          prompt: 'Find the area of the square base.',
          hint1: 'Area = side².',
          hint2: '6² = 36.',
          hint3: '36 cm².',
          answer: 36,
          tolerance: 0,
          unit: 'cm²',
          explanation: 'Base area = 6² = 36 cm².',
        },
        {
          prompt: 'Use: Volume of pyramid = (1/3) × base area × height.',
          hint1: 'V = (1/3) × 36 × 8.',
          hint2: '(1/3) × 288 = ?',
          hint3: '96 cm³.',
          answer: 96,
          tolerance: 0,
          unit: 'cm³',
          explanation: 'V = (1/3) × 36 × 8 = 96 cm³.',
        },
        {
          prompt: 'If another pyramid has the same base but double the height, what is its volume?',
          hint1: 'Height = 16 cm. V = (1/3) × 36 × 16.',
          hint2: '(1/3) × 576 = 192.',
          hint3: '192 cm³.',
          answer: 192,
          tolerance: 0,
          unit: 'cm³',
          explanation: 'V = (1/3)×36×16 = 192 cm³. Doubling height doubles volume.',
        },
      ],
      workedExample: {
        question: 'Square pyramid: base 4 cm, height 9 cm. Volume?',
        steps: ['Base area = 16 cm²', 'V = (1/3)×16×9 = <strong>48 cm³</strong>'],
      },
      sampleAnswer: {
        grade4: 'V = 96 cm³. Double height gives 192 cm³.',
        grade6: 'Base = 36 cm². V = (1/3)×36×8 = 96 cm³. Double height: 192 cm³.',
        grade8: 'V = ⅓Ah = ⅓×36×8 = 96 cm³. 2×height → 2×volume = 192 cm³.',
      },
      examinerTip: 'Pyramid volume = (1/3) × prism volume. Height must be perpendicular to the base.',
      auditStatus: 'pending',
    },
    {
      id: 'av-B03',
      subtopic: 'geo-area-volume',
      band: 'B',
      marks: 3,
      question: 'A sector has radius 9 cm and angle 120°. Find (a) the arc length and (b) the area of the sector. Give answers in terms of π.',
      steps: [
        {
          prompt: '(a) Arc length = (angle/360) × 2πr.',
          hint1: '(120/360) × 2π × 9.',
          hint2: '(1/3) × 18π = 6π.',
          hint3: '6π cm.',
          answer: 6,
          tolerance: 0,
          unit: '',
          displayAnswer: '6π cm',
          explanation: 'Arc = (120/360) × 2π × 9 = 6π cm.',
        },
        {
          prompt: '(b) Area of sector = (angle/360) × πr².',
          hint1: '(120/360) × π × 9².',
          hint2: '(1/3) × 81π = 27π.',
          hint3: '27π cm².',
          answer: 27,
          tolerance: 0,
          unit: '',
          displayAnswer: '27π cm²',
          explanation: 'Area = (120/360) × π × 81 = 27π cm².',
        },
        {
          prompt: 'Find the perimeter of the sector (arc + 2 radii). Answer in terms of π.',
          hint1: 'Perimeter = arc length + 2r = 6π + 2×9.',
          hint2: '6π + 18.',
          hint3: '(6π + 18) cm.',
          answer: 18,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: 'Perimeter = (6π + 18) cm',
          explanation: 'Perimeter = arc + 2r = 6π + 18 cm.',
        },
      ],
      workedExample: {
        question: 'Sector: r=6 cm, angle=90°. Arc length and area in terms of π.',
        steps: ['Arc = (90/360)×2π×6 = 3π cm', 'Area = (90/360)×π×36 = <strong>9π cm²</strong>', 'Perimeter = 3π+12 cm'],
      },
      sampleAnswer: {
        grade4: 'Arc=6π cm. Area=27π cm². Perimeter=6π+18 cm.',
        grade6: 'Arc=(1/3)×2π×9=6π. Area=(1/3)×81π=27π. Perimeter=6π+18 cm.',
        grade8: 'Arc=6π cm. Area=27π cm². Perimeter=(6π+18) cm.',
      },
      examinerTip: 'Perimeter of sector = arc length + two radii (not arc length alone).',
      auditStatus: 'pending',
    },
    {
      id: 'av-B04',
      subtopic: 'geo-area-volume',
      band: 'B',
      marks: 3,
      question: 'Find the surface area of a sphere with radius 5 cm. Give your answer to 3 significant figures.',
      steps: [
        {
          prompt: 'Use: Surface area = 4πr².',
          hint1: '4 × π × 5².',
          hint2: '4 × π × 25 = 100π.',
          hint3: '100π cm².',
          answer: 100,
          tolerance: 0,
          unit: '',
          displayAnswer: '100π cm²',
          explanation: 'SA = 4π × 25 = 100π cm².',
        },
        {
          prompt: 'Calculate 100π to 3 significant figures.',
          hint1: 'π ≈ 3.14159...',
          hint2: '100 × 3.14159 ≈ 314.2.',
          hint3: '314 cm².',
          answer: 314,
          tolerance: 0.5,
          unit: 'cm²',
          explanation: 'SA = 100π ≈ 314 cm² (3 s.f.).',
        },
        {
          prompt: 'What would the surface area be if the radius were doubled to 10 cm?',
          hint1: 'Doubling radius multiplies SA by 4.',
          hint2: 'SA = 4π × 100 = 400π ≈ 1257 cm².',
          hint3: '≈ 1260 cm² (3 s.f.).',
          answer: 1260,
          tolerance: 2,
          unit: 'cm²',
          explanation: 'SA = 4π×100 = 400π ≈ 1257 cm² ≈ 1260 (3 s.f.).',
        },
      ],
      workedExample: {
        question: 'Sphere radius 4 cm. SA to 3 s.f.',
        steps: ['SA = 4π×16 = 64π ≈ <strong>201 cm²</strong> (3 s.f.)'],
      },
      sampleAnswer: {
        grade4: 'SA ≈ 314 cm².',
        grade6: 'SA = 4πr² = 4π×25 = 100π ≈ 314 cm². Double radius: 400π ≈ 1260 cm².',
        grade8: 'SA = 4π(5²) = 100π ≈ 314 cm² (3 s.f.). Double r: SA × 4 = 400π ≈ 1260 cm².',
      },
      examinerTip: 'Doubling the radius quadruples the surface area (SA ∝ r²).',
      auditStatus: 'pending',
    },
    {
      id: 'av-B05',
      subtopic: 'geo-area-volume',
      band: 'B',
      marks: 3,
      question: 'A composite shape consists of a cylinder (radius 4 cm, height 6 cm) with a hemisphere (radius 4 cm) on top. Find the total volume. Use π = 3.14.',
      steps: [
        {
          prompt: 'Find the volume of the cylinder.',
          hint1: 'V = πr²h = 3.14 × 16 × 6.',
          hint2: '3.14 × 96 = ?',
          hint3: '301.44 cm³.',
          answer: 301.44,
          tolerance: 0.5,
          unit: 'cm³',
          explanation: 'Cylinder V = 3.14 × 16 × 6 = 301.44 cm³.',
        },
        {
          prompt: 'Find the volume of the hemisphere (half a sphere).',
          hint1: 'V = (2/3)πr³ = (2/3) × 3.14 × 64.',
          hint2: '(2/3) × 200.96 = ?',
          hint3: '134.0 cm³.',
          answer: 134.0,
          tolerance: 0.5,
          unit: 'cm³',
          explanation: 'Hemisphere V = (2/3) × 3.14 × 64 ≈ 134.0 cm³.',
        },
        {
          prompt: 'Find the total volume.',
          hint1: '301.44 + 134.0 = ?',
          hint2: '435.44 cm³.',
          hint3: '≈ 435 cm³.',
          answer: 435.44,
          tolerance: 1,
          unit: 'cm³',
          explanation: 'Total = 301.44 + 134.0 ≈ 435.4 cm³.',
        },
      ],
      workedExample: {
        question: 'Cylinder (r=3, h=5) + hemisphere (r=3) on top. Volume (π=3.14)?',
        steps: ['Cylinder: 3.14×9×5=141.3 cm³', 'Hemisphere: (2/3)×3.14×27=56.52 cm³', 'Total: <strong>197.8 cm³</strong>'],
      },
      sampleAnswer: {
        grade4: 'Cylinder≈301.4, Hemisphere≈134.0. Total≈435.4 cm³.',
        grade6: 'V_cyl=3.14×16×6=301.44. V_hemi=(2/3)×3.14×64=134.0. Total=435.4 cm³.',
        grade8: 'V=πr²h+(2/3)πr³=3.14×16×6+(2/3)×3.14×64≈435.4 cm³.',
      },
      examinerTip: 'Hemisphere volume = half of sphere = (2/3)πr³.',
      auditStatus: 'pending',
    },
    {
      id: 'av-B06',
      subtopic: 'geo-area-volume',
      band: 'B',
      marks: 3,
      question: 'A garden has a rectangular lawn 12 m × 8 m with a circular pond of diameter 4 m cut from it. Find the remaining area of the lawn. Use π = 3.14.',
      steps: [
        {
          prompt: 'Find the area of the rectangular lawn.',
          hint1: 'Area = length × width.',
          hint2: '12 × 8 = ?',
          hint3: '96 m².',
          answer: 96,
          tolerance: 0,
          unit: 'm²',
          explanation: 'Rectangle area = 12 × 8 = 96 m².',
        },
        {
          prompt: 'Find the area of the circular pond. (Diameter = 4 m, so radius = 2 m.)',
          hint1: 'A = πr² = 3.14 × 2².',
          hint2: '3.14 × 4 = ?',
          hint3: '12.56 m².',
          answer: 12.56,
          tolerance: 0.05,
          unit: 'm²',
          explanation: 'Circle area = 3.14 × 4 = 12.56 m².',
        },
        {
          prompt: 'Find the remaining area of lawn.',
          hint1: 'Lawn − circle = ?',
          hint2: '96 − 12.56 = ?',
          hint3: '83.44 m².',
          answer: 83.44,
          tolerance: 0.1,
          unit: 'm²',
          explanation: 'Remaining = 96 − 12.56 = 83.44 m².',
        },
      ],
      workedExample: {
        question: 'Rectangle 10×6 m with circular pond radius 2 m removed. Remaining area (π=3.14)?',
        steps: ['Rectangle=60 m². Circle=3.14×4=12.56 m².', 'Remaining=60−12.56=<strong>47.44 m²</strong>'],
      },
      sampleAnswer: {
        grade4: 'Lawn=96 m². Pond=12.56 m². Remaining=83.44 m².',
        grade6: 'Rectangle=96 m². Circle (r=2)=12.56 m². Remaining=83.44 m².',
        grade8: '96 − π(2²) = 96 − 12.56 = 83.44 m².',
      },
      examinerTip: 'Diameter ÷ 2 to get radius before using A = πr².',
      auditStatus: 'pending',
    },
    {
      id: 'av-C01',
      subtopic: 'geo-area-volume',
      band: 'C',
      marks: 4,
      question: 'A solid is made of a cone (radius 6 cm, height 8 cm) on top of a cylinder (radius 6 cm, height 10 cm). Find the total surface area. Use π = 3.14.',
      steps: [
        {
          prompt: 'Find the slant height of the cone using Pythagoras.',
          hint1: 'l² = r² + h² = 6² + 8².',
          hint2: '36 + 64 = 100. l = √100.',
          hint3: 'l = 10 cm.',
          answer: 10,
          tolerance: 0,
          unit: 'cm',
          explanation: 'l = √(36+64) = √100 = 10 cm.',
        },
        {
          prompt: 'Find the curved surface area of the cone: πrl.',
          hint1: '3.14 × 6 × 10 = ?',
          hint2: '188.4 cm².',
          hint3: '188.4 cm².',
          answer: 188.4,
          tolerance: 0.5,
          unit: 'cm²',
          explanation: 'Cone CSA = π×6×10 = 188.4 cm².',
        },
        {
          prompt: 'Find the curved surface area of the cylinder (no top or bottom, just the side): 2πrh.',
          hint1: '2 × 3.14 × 6 × 10.',
          hint2: '376.8 cm².',
          hint3: '376.8 cm².',
          answer: 376.8,
          tolerance: 0.5,
          unit: 'cm²',
          explanation: 'Cylinder CSA = 2π×6×10 = 376.8 cm².',
        },
        {
          prompt: 'Add the base circle of the cylinder and find total SA. (Only one circular base.)',
          hint1: 'Base = πr² = 3.14×36 = 113.04 cm².',
          hint2: 'Total = 188.4 + 376.8 + 113.04.',
          hint3: '678.24 cm².',
          answer: 678.24,
          tolerance: 1,
          unit: 'cm²',
          explanation: 'Total SA = 188.4 + 376.8 + 113.04 = 678.24 cm².',
        },
      ],
      workedExample: {
        question: 'Cone (r=3, h=4) on cylinder (r=3, h=6). Total SA (π=3.14).',
        steps: ['Slant=√(9+16)=5. Cone CSA=3.14×3×5=47.1.', 'Cyl CSA=2×3.14×3×6=113.04. Base=3.14×9=28.26.', 'Total=<strong>188.4 cm²</strong>'],
      },
      sampleAnswer: {
        grade4: 'l=10. CSA cone=188.4. CSA cyl=376.8. Base=113.04. Total=678.24 cm².',
        grade6: 'l=10 cm. Total=πrl + 2πrh + πr² = 188.4+376.8+113.04=678.24 cm².',
        grade8: 'l=√(r²+h²)=10. SA=πrl+2πrh+πr²=188.4+376.8+113.04≈678 cm².',
      },
      examinerTip: 'The shared face (top of cylinder = base of cone) is internal — do not include it. Only add the visible base circle.',
      auditStatus: 'pending',
    },
    {
      id: 'av-C02',
      subtopic: 'geo-area-volume',
      band: 'C',
      marks: 4,
      question: 'A spherical ball of radius 6 cm is melted down and recast into small spheres of radius 1.5 cm. How many small spheres can be made?',
      steps: [
        {
          prompt: 'Find the volume of the large sphere. (In terms of π.)',
          hint1: 'V = (4/3)πr³ = (4/3)π × 6³.',
          hint2: '(4/3)π × 216 = 288π.',
          hint3: '288π cm³.',
          answer: 288,
          tolerance: 0,
          unit: '',
          displayAnswer: '288π cm³',
          explanation: 'V_large = (4/3)π × 216 = 288π cm³.',
        },
        {
          prompt: 'Find the volume of one small sphere. (In terms of π.)',
          hint1: 'V = (4/3)π × 1.5³.',
          hint2: '1.5³ = 3.375. (4/3) × 3.375 = 4.5.',
          hint3: '4.5π cm³.',
          answer: 4.5,
          tolerance: 0,
          unit: '',
          displayAnswer: '4.5π cm³',
          explanation: 'V_small = (4/3)π × 1.5³ = (4/3)π × 3.375 = 4.5π cm³.',
        },
        {
          prompt: 'Calculate the number of small spheres.',
          hint1: 'n = V_large ÷ V_small.',
          hint2: '288π ÷ 4.5π = 288 ÷ 4.5.',
          hint3: '64.',
          answer: 64,
          tolerance: 0,
          unit: '',
          explanation: 'n = 288π / 4.5π = 64.',
        },
        {
          prompt: 'Verify using scale factor: radius ratio = 6/1.5 = 4. Volume ratio = 4³ = ?',
          hint1: '4³ = 64.',
          hint2: '64 small spheres can be made. ✓',
          hint3: 'Enter 64.',
          answer: 64,
          tolerance: 0,
          unit: '',
          explanation: 'Radius ratio=4. Volume ratio=64. One large → 64 small. ✓',
        },
      ],
      workedExample: {
        question: 'Large sphere r=3 cm melted into small spheres r=1 cm. How many?',
        steps: ['V_large=(4/3)π×27=36π.', 'V_small=(4/3)π×1=4π/3.', 'n=36π÷(4π/3)=36×3/4=<strong>27</strong>.'],
      },
      sampleAnswer: {
        grade4: '64 small spheres.',
        grade6: 'V_large=288π. V_small=4.5π. n=288/4.5=64.',
        grade8: 'n=V_large/V_small=288π/4.5π=64. Check: (6/1.5)³=4³=64 ✓',
      },
      examinerTip: 'The π cancels when dividing volumes — you only need to divide the numerical coefficients.',
      auditStatus: 'pending',
    },
    {
      id: 'av-C03',
      subtopic: 'geo-area-volume',
      band: 'C',
      marks: 4,
      question: 'A sector has radius 12 cm and angle 150°. Find the area of the segment (the region between the chord and the arc). Use π = 3.14 and sin 150° = 0.5.',
      steps: [
        {
          prompt: 'Find the area of the sector.',
          hint1: 'Area = (150/360) × π × r².',
          hint2: '(5/12) × 3.14 × 144.',
          hint3: '188.4 cm².',
          answer: 188.4,
          tolerance: 0.5,
          unit: 'cm²',
          explanation: 'Sector area = (150/360)×3.14×144 = (5/12)×452.16 = 188.4 cm².',
        },
        {
          prompt: 'Find the area of the triangle formed by the two radii and the chord. Use: Area = ½r²sinθ.',
          hint1: 'Area = ½ × 12² × sin 150° = ½ × 144 × 0.5.',
          hint2: '72 × 0.5 = 36.',
          hint3: '36 cm².',
          answer: 36,
          tolerance: 0,
          unit: 'cm²',
          explanation: 'Triangle area = ½ × 144 × sin150° = ½ × 144 × 0.5 = 36 cm².',
        },
        {
          prompt: 'Find the area of the segment.',
          hint1: 'Segment = Sector − Triangle.',
          hint2: '188.4 − 36 = ?',
          hint3: '152.4 cm².',
          answer: 152.4,
          tolerance: 0.5,
          unit: 'cm²',
          explanation: 'Segment = 188.4 − 36 = 152.4 cm².',
        },
        {
          prompt: 'Check: is the segment larger than half the circle\'s area? Full circle = 3.14×144=452.16. Half = 226 cm². Is 152.4 < 226? Enter 1 for yes.',
          hint1: 'The 150° sector is less than a semicircle (180°), so the segment should be less than the semicircle.',
          hint2: '152.4 < 226. Yes.',
          hint3: 'Enter 1.',
          answer: 1,
          tolerance: 0,
          unit: '',
          checkType: 'skip',
          displayAnswer: '152.4 < 226 cm² — reasonable answer ✓',
          explanation: 'Segment area 152.4 cm² is less than half the circle (226 cm²). Reasonable ✓',
        },
      ],
      workedExample: {
        question: 'Sector r=10, θ=60°. Segment area (π=3.14, sin60°=0.866).',
        steps: ['Sector=(60/360)×3.14×100=52.33 cm².', 'Triangle=½×100×0.866=43.3 cm².', 'Segment=52.33−43.3=<strong>9.03 cm²</strong>'],
      },
      sampleAnswer: {
        grade4: 'Sector=188.4. Triangle=36. Segment=152.4 cm².',
        grade6: 'Sector=188.4 cm². Triangle=½r²sinθ=36 cm². Segment=152.4 cm².',
        grade8: 'Segment=sector−triangle=(5/12)π×144−½×144×sin150°=188.4−36=152.4 cm².',
      },
      examinerTip: 'Segment area = sector area − triangle area. Use ½r²sinθ for the triangle inside a sector.',
      auditStatus: 'pending',
    },
    {
      id: 'av-C04',
      subtopic: 'geo-area-volume',
      band: 'C',
      marks: 4,
      question: 'A frustum is made by removing a small cone (radius 2 cm, height 3 cm) from a large cone (radius 6 cm, height 9 cm). Find the volume of the frustum. Use π = 3.14.',
      steps: [
        {
          prompt: 'Find the volume of the large cone.',
          hint1: 'V = (1/3)πr²h = (1/3) × 3.14 × 36 × 9.',
          hint2: '(1/3) × 3.14 × 324 = ?',
          hint3: '339.12 cm³.',
          answer: 339.12,
          tolerance: 0.5,
          unit: 'cm³',
          explanation: 'V_large = (1/3)×3.14×36×9 = 339.12 cm³.',
        },
        {
          prompt: 'Find the volume of the small cone.',
          hint1: 'V = (1/3) × 3.14 × 4 × 3.',
          hint2: '(1/3) × 3.14 × 12 = ?',
          hint3: '12.56 cm³.',
          answer: 12.56,
          tolerance: 0.1,
          unit: 'cm³',
          explanation: 'V_small = (1/3)×3.14×4×3 = 12.56 cm³.',
        },
        {
          prompt: 'Find the volume of the frustum.',
          hint1: 'V_frustum = V_large − V_small.',
          hint2: '339.12 − 12.56 = ?',
          hint3: '326.56 cm³.',
          answer: 326.56,
          tolerance: 1,
          unit: 'cm³',
          explanation: 'V_frustum = 339.12 − 12.56 = 326.56 cm³.',
        },
        {
          prompt: 'Verify the cones are similar: check ratio of radii = ratio of heights.',
          hint1: 'Radius ratio = 6/2 = 3. Height ratio = 9/3 = 3. ✓',
          hint2: 'Both ratios = 3, so the cones are similar.',
          hint3: 'Enter 3.',
          answer: 3,
          tolerance: 0,
          unit: '',
          explanation: 'Radii 6:2=3:1 and heights 9:3=3:1. Similar cones confirmed ✓',
        },
      ],
      workedExample: {
        question: 'Large cone (r=4, h=12) with small cone (r=2, h=6) removed. Frustum volume (π=3.14)?',
        steps: ['V_large=(1/3)×3.14×16×12=200.96.', 'V_small=(1/3)×3.14×4×6=25.12.', 'V_frustum=200.96−25.12=<strong>175.84 cm³</strong>'],
      },
      sampleAnswer: {
        grade4: 'V_large=339.12. V_small=12.56. Frustum=326.56 cm³.',
        grade6: 'V_large=(1/3)×3.14×36×9=339.12. V_small=12.56. Frustum=326.56 cm³.',
        grade8: 'V_frustum=⅓π(R²H−r²h)=⅓×3.14(36×9−4×3)=⅓×3.14×312≈326.6 cm³.',
      },
      examinerTip: 'To make a frustum, subtract the small cone volume from the large cone. Verify the cones are similar before applying this method.',
      auditStatus: 'pending',
    },
"""

with open(FILE, encoding='utf-8') as f:
    content = f.read()
pos = content.find(MARKER)
if pos < 0:
    print('MARKER NOT FOUND')
else:
    print(f'Inserting at char {pos}')
    with open(FILE, 'w', encoding='utf-8') as f:
        f.write(content[:pos] + NEW + content[pos:])
    print('Done - geo_q3 (12 area-volume questions)')
