import sys

FILE = r'C:\Users\jason\OneDrive\Documents\GitHub\mabel-gcse\js\maths-questions.js'
MARKER = "\n\n    // ── pct-A04 ──────────────────────────────────────────────"

NEW = (
    "\n\n    // ══════════════════════════════════════════════════════════\n"
    "    // BOX PLOTS (stat-boxplots) — Higher\n"
    "    // ══════════════════════════════════════════════════════════\n"

    # ── stat-boxplots-A01 ──────────────────────────────────────────
    "    {\n"
    "      id: 'stat-boxplots-A01', subtopic: 'stat-boxplots', band: 'A', marks: 3,\n"
    "      question: 'A box plot shows: min = 5, Q1 = 12, median = 18, Q3 = 27, max = 35. Find (a) the IQR, (b) the range, and (c) state what percentage of data lies between Q1 and Q3.',\n"
    "      steps: [\n"
    "        {\n"
    "          prompt: 'Calculate the interquartile range (IQR = Q3 − Q1).', hint1: 'IQR = Q3 − Q1', hint2: 'IQR = 27 − 12', hint3: 'IQR = 27 − 12 = 15',\n"
    "          answer: 15, tolerance: 0, unit: '',\n"
    "          explanation: 'IQR = Q3 − Q1 = 27 − 12 = 15.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'Calculate the range (max − min).', hint1: 'Range = max − min', hint2: 'Range = 35 − 5', hint3: 'Range = 35 − 5 = 30',\n"
    "          answer: 30, tolerance: 0, unit: '',\n"
    "          explanation: 'Range = max − min = 35 − 5 = 30.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'What percentage of data lies between Q1 and Q3?', hint1: 'Think about what the quartiles represent.', hint2: 'The box in a box plot contains the middle 50%.', hint3: 'By definition, 50% of the data lies between Q1 and Q3.',\n"
    "          answer: 0, tolerance: 0, unit: '', checkType: 'skip', displayAnswer: '50%',\n"
    "          explanation: 'By definition, 50% of the data lies between the lower quartile (Q1) and upper quartile (Q3).',\n"
    "        },\n"
    "      ],\n"
    "      workedExample: {\n"
    "        question: 'A box plot shows: min = 10, Q1 = 18, median = 25, Q3 = 34, max = 42. Find the IQR, range, and the percentage of data between the quartiles.',\n"
    "        steps: [\n"
    "          'IQR — IQR = Q3 − Q1 = 34 − 18 = <strong>16</strong>',\n"
    "          'Range — Range = max − min = 42 − 10 = <strong>32</strong>',\n"
    "          'Percentage between quartiles — By definition, <strong>50%</strong> of data lies between Q1 and Q3',\n"
    "        ],\n"
    "      },\n"
    "      sampleAnswer: { grade4: 'IQR = 15; range = 30.', grade6: 'IQR = Q3 − Q1 = 27 − 12 = 15. Range = 35 − 5 = 30. 50% of data lies between Q1 and Q3.', grade8: 'IQR = 27 − 12 = 15. Range = 35 − 5 = 30. By definition, 50% of all values fall between Q1 and Q3 (the middle two quartiles).' },\n"
    "      examinerTip: 'Always subtract Q1 from Q3 for IQR — not max minus min. The IQR covers exactly 50% of the data.',\n"
    "      auditStatus: 'pending',\n"
    "    },\n"

    # ── stat-boxplots-A02 ──────────────────────────────────────────
    "    {\n"
    "      id: 'stat-boxplots-A02', subtopic: 'stat-boxplots', band: 'A', marks: 2,\n"
    "      question: 'Dataset A has median = 45 and IQR = 20. Dataset B has median = 38 and IQR = 15. State (a) which dataset has the higher median and (b) which has the greater spread.',\n"
    "      steps: [\n"
    "        {\n"
    "          prompt: 'Which dataset has the higher median?', hint1: 'Compare 45 and 38.', hint2: '45 > 38', hint3: 'Dataset A has the higher median.',\n"
    "          answer: 0, tolerance: 0, unit: '', checkType: 'skip', displayAnswer: 'Dataset A (median 45 > 38)',\n"
    "          explanation: 'Dataset A has the higher median: 45 > 38.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'Which dataset has the greater spread (compare IQRs)?', hint1: 'Compare IQR values: 20 and 15.', hint2: '20 > 15', hint3: 'Dataset A has the greater spread.',\n"
    "          answer: 0, tolerance: 0, unit: '', checkType: 'skip', displayAnswer: 'Dataset A (IQR 20 > 15)',\n"
    "          explanation: 'IQR measures spread. IQR_A = 20 > IQR_B = 15, so Dataset A has greater spread.',\n"
    "        },\n"
    "      ],\n"
    "      workedExample: {\n"
    "        question: 'Dataset C has median = 62, IQR = 25. Dataset D has median = 70, IQR = 18. Which has the higher median? Which has the greater spread?',\n"
    "        steps: [\n"
    "          'Higher median — D has median 70 vs C median 62: <strong>Dataset D</strong> has the higher median',\n"
    "          'Greater spread — C has IQR 25 vs D IQR 18: <strong>Dataset C</strong> has the greater spread',\n"
    "        ],\n"
    "      },\n"
    "      sampleAnswer: { grade4: 'Dataset A has the higher median. Dataset A has greater spread.', grade6: 'Dataset A has the higher median (45 > 38). Dataset A has greater spread (IQR 20 > 15).', grade8: 'Median comparison: A (45) > B (38), so A has a higher typical value. Spread comparison: IQR_A (20) > IQR_B (15), so A has greater variability in the middle 50% of its data.' },\n"
    "      examinerTip: 'Use median to compare averages and IQR to compare spread. Never use range to compare spread if IQR is available.',\n"
    "      auditStatus: 'pending',\n"
    "    },\n"

    # ── stat-boxplots-A03 ──────────────────────────────────────────
    "    {\n"
    "      id: 'stat-boxplots-A03', subtopic: 'stat-boxplots', band: 'A', marks: 2,\n"
    "      question: 'A box plot for n = 80 values shows Q1 = 14 and Q3 = 26. Find (a) the IQR and (b) how many values lie between Q1 and Q3.',\n"
    "      steps: [\n"
    "        {\n"
    "          prompt: 'Calculate the IQR.', hint1: 'IQR = Q3 − Q1', hint2: 'IQR = 26 − 14', hint3: 'IQR = 26 − 14 = 12',\n"
    "          answer: 12, tolerance: 0, unit: '',\n"
    "          explanation: 'IQR = Q3 − Q1 = 26 − 14 = 12.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'How many of the 80 values lie between Q1 and Q3?', hint1: '50% of values lie between Q1 and Q3.', hint2: '50% of 80 = ?', hint3: '0.5 × 80 = 40',\n"
    "          answer: 40, tolerance: 0, unit: '',\n"
    "          explanation: '50% of the data lies between Q1 and Q3. 50% of 80 = 40 values.',\n"
    "        },\n"
    "      ],\n"
    "      workedExample: {\n"
    "        question: 'A box plot for n = 60 values shows Q1 = 20 and Q3 = 44. Find the IQR and how many values lie between Q1 and Q3.',\n"
    "        steps: [\n"
    "          'IQR — Q3 − Q1 = 44 − 20 = <strong>24</strong>',\n"
    "          'Values between Q1 and Q3 — 50% of 60 = <strong>30</strong> values',\n"
    "        ],\n"
    "      },\n"
    "      sampleAnswer: { grade4: 'IQR = 12. 40 values lie between Q1 and Q3.', grade6: 'IQR = 26 − 14 = 12. 50% of 80 = 40 values lie between Q1 and Q3.', grade8: 'IQR = Q3 − Q1 = 26 − 14 = 12. Since Q1 and Q3 are the lower and upper quartiles, 50% of all values fall between them: 0.5 × 80 = 40 values.' },\n"
    "      examinerTip: 'Always remember: 50% of data lies in the box (between Q1 and Q3). Multiply n by 0.5 to find the count.',\n"
    "      auditStatus: 'pending',\n"
    "    },\n"

    # ── stat-boxplots-A04 ──────────────────────────────────────────
    "    {\n"
    "      id: 'stat-boxplots-A04', subtopic: 'stat-boxplots', band: 'A', marks: 2,\n"
    "      question: 'From a box plot: min = 3, Q1 = 8, median = 13, Q3 = 19, max = 25. Find (a) the IQR and (b) the range.',\n"
    "      steps: [\n"
    "        {\n"
    "          prompt: 'Calculate the IQR.', hint1: 'IQR = Q3 − Q1', hint2: 'IQR = 19 − 8', hint3: 'IQR = 19 − 8 = 11',\n"
    "          answer: 11, tolerance: 0, unit: '',\n"
    "          explanation: 'IQR = Q3 − Q1 = 19 − 8 = 11.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'Calculate the range.', hint1: 'Range = max − min', hint2: 'Range = 25 − 3', hint3: 'Range = 25 − 3 = 22',\n"
    "          answer: 22, tolerance: 0, unit: '',\n"
    "          explanation: 'Range = max − min = 25 − 3 = 22.',\n"
    "        },\n"
    "      ],\n"
    "      workedExample: {\n"
    "        question: 'A box plot shows: min = 1, Q1 = 6, median = 10, Q3 = 16, max = 22. Find the IQR and the range.',\n"
    "        steps: [\n"
    "          'IQR — Q3 − Q1 = 16 − 6 = <strong>10</strong>',\n"
    "          'Range — max − min = 22 − 1 = <strong>21</strong>',\n"
    "        ],\n"
    "      },\n"
    "      sampleAnswer: { grade4: 'IQR = 11; range = 22.', grade6: 'IQR = Q3 − Q1 = 19 − 8 = 11. Range = max − min = 25 − 3 = 22.', grade8: 'IQR = 19 − 8 = 11 (measures spread of the middle 50%). Range = 25 − 3 = 22 (measures total spread, affected by extremes).' },\n"
    "      examinerTip: 'Two key measures: IQR uses quartiles (Q3 − Q1); range uses the extremes (max − min). Don't mix them up.',\n"
    "      auditStatus: 'pending',\n"
    "    },\n"

    # ── stat-boxplots-A05 ──────────────────────────────────────────
    "    {\n"
    "      id: 'stat-boxplots-A05', subtopic: 'stat-boxplots', band: 'A', marks: 2,\n"
    "      question: 'A box plot shows that 25% of data is below 16 and 75% is below 30. The median is 23. Find (a) the IQR and (b) state which half of the box (lower or upper) is wider.',\n"
    "      steps: [\n"
    "        {\n"
    "          prompt: 'Identify Q1 and Q3, then calculate the IQR.', hint1: '25% below = Q1; 75% below = Q3.', hint2: 'Q1 = 16, Q3 = 30', hint3: 'IQR = 30 − 16 = 14',\n"
    "          answer: 14, tolerance: 0, unit: '',\n"
    "          explanation: 'Q1 = 16 (25th percentile), Q3 = 30 (75th percentile). IQR = 30 − 16 = 14.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'Which half of the box is wider — lower (Q1 to median) or upper (median to Q3)?', hint1: 'Lower half = median − Q1; upper half = Q3 − median.', hint2: 'Lower: 23 − 16 = 7; upper: 30 − 23 = 7.', hint3: 'Both halves are equal (7 each).',\n"
    "          answer: 0, tolerance: 0, unit: '', checkType: 'skip', displayAnswer: 'Both halves equal (7 each) — symmetric distribution',\n"
    "          explanation: 'Lower half: median − Q1 = 23 − 16 = 7. Upper half: Q3 − median = 30 − 23 = 7. Both halves equal — the distribution is symmetric.',\n"
    "        },\n"
    "      ],\n"
    "      workedExample: {\n"
    "        question: 'A box plot shows Q1 = 10, median = 18, Q3 = 28. Find the IQR and state the direction of skew.',\n"
    "        steps: [\n"
    "          'IQR — Q3 − Q1 = 28 − 10 = <strong>18</strong>',\n"
    "          'Lower half — median − Q1 = 18 − 10 = <strong>8</strong>',\n"
    "          'Upper half — Q3 − median = 28 − 18 = <strong>10</strong>',\n"
    "          'Skew — upper half wider (10 > 8) → <strong>positive skew</strong>',\n"
    "        ],\n"
    "      },\n"
    "      sampleAnswer: { grade4: 'IQR = 14. Both halves are equal.', grade6: 'Q1 = 16, Q3 = 30. IQR = 30 − 16 = 14. Lower half: 23 − 16 = 7. Upper half: 30 − 23 = 7. Both halves equal — symmetric.', grade8: 'IQR = Q3 − Q1 = 30 − 16 = 14. The box is symmetric: lower half (median − Q1 = 7) equals upper half (Q3 − median = 7), indicating a roughly symmetric distribution with no skew.' },\n"
    "      examinerTip: 'To judge skew from a box plot, compare (median − Q1) with (Q3 − median). If Q3 − median is larger, it is positively skewed.',\n"
    "      auditStatus: 'pending',\n"
    "    },\n"

    # ── stat-boxplots-B01 ──────────────────────────────────────────
    "    {\n"
    "      id: 'stat-boxplots-B01', subtopic: 'stat-boxplots', band: 'B', marks: 3,\n"
    "      question: 'Q1 = 20, Q3 = 44. A value of 65 is recorded. Using the outlier rule (upper fence = Q3 + 1.5 × IQR), determine whether 65 is an outlier.',\n"
    "      steps: [\n"
    "        {\n"
    "          prompt: 'Calculate the IQR.', hint1: 'IQR = Q3 − Q1', hint2: 'IQR = 44 − 20', hint3: 'IQR = 44 − 20 = 24',\n"
    "          answer: 24, tolerance: 0, unit: '',\n"
    "          explanation: 'IQR = Q3 − Q1 = 44 − 20 = 24.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'Calculate the upper fence (Q3 + 1.5 × IQR).', hint1: 'Upper fence = Q3 + 1.5 × IQR', hint2: '= 44 + 1.5 × 24', hint3: '= 44 + 36 = 80',\n"
    "          answer: 80, tolerance: 0, unit: '',\n"
    "          explanation: 'Upper fence = 44 + 1.5 × 24 = 44 + 36 = 80.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'Is 65 an outlier? Compare it to the upper fence.', hint1: 'A value is an outlier if it exceeds the fence.', hint2: 'Is 65 > 80?', hint3: '65 < 80, so 65 is NOT an outlier.',\n"
    "          answer: 0, tolerance: 0, unit: '', checkType: 'skip', displayAnswer: '65 < 80 → NOT an outlier',\n"
    "          explanation: '65 < upper fence of 80, so 65 is NOT classified as an outlier.',\n"
    "        },\n"
    "      ],\n"
    "      workedExample: {\n"
    "        question: 'Q1 = 10, Q3 = 28. Is a value of 58 an outlier?',\n"
    "        steps: [\n"
    "          'IQR — Q3 − Q1 = 28 − 10 = <strong>18</strong>',\n"
    "          'Upper fence — Q3 + 1.5 × IQR = 28 + 1.5 × 18 = 28 + 27 = <strong>55</strong>',\n"
    "          'Check — 58 > 55, so 58 <strong>IS an outlier</strong>',\n"
    "        ],\n"
    "      },\n"
    "      sampleAnswer: { grade4: 'IQR = 24. Upper fence = 80. 65 is not an outlier.', grade6: 'IQR = 44 − 20 = 24. Upper fence = 44 + 1.5 × 24 = 80. Since 65 < 80, it is not an outlier.', grade8: 'IQR = 24. Upper fence = Q3 + 1.5 × IQR = 44 + 36 = 80. The value 65 < 80, so it does not exceed the outlier threshold and is not classified as an outlier.' },\n"
    "      examinerTip: 'The outlier rule is: value > Q3 + 1.5 × IQR (upper) or value < Q1 − 1.5 × IQR (lower). Always show the fence calculation.',\n"
    "      auditStatus: 'pending',\n"
    "    },\n"

    # ── stat-boxplots-B02 ──────────────────────────────────────────
    "    {\n"
    "      id: 'stat-boxplots-B02', subtopic: 'stat-boxplots', band: 'B', marks: 3,\n"
    "      question: 'Class A exam scores: min = 40, Q1 = 55, median = 65, Q3 = 75, max = 90. Class B: min = 35, Q1 = 50, median = 68, Q3 = 80, max = 95. Compare the two distributions.',\n"
    "      steps: [\n"
    "        {\n"
    "          prompt: 'Find the IQR for both classes. Which class has greater spread?', hint1: 'IQR = Q3 − Q1 for each class.', hint2: 'IQR_A = 75 − 55 = 20; IQR_B = 80 − 50 = ?', hint3: 'IQR_B = 80 − 50 = 30. Class B has greater spread.',\n"
    "          answer: 30, tolerance: 0, unit: '',\n"
    "          explanation: 'IQR_A = 75 − 55 = 20. IQR_B = 80 − 50 = 30. Class B has the greater spread.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'Which class has the higher median?', hint1: 'Compare the median values: 65 and 68.', hint2: '68 > 65', hint3: 'Class B has the higher median.',\n"
    "          answer: 0, tolerance: 0, unit: '', checkType: 'skip', displayAnswer: 'Class B higher median (68 > 65)',\n"
    "          explanation: 'Class B median (68) > Class A median (65). Class B performed slightly better on average.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'Summarise the overall comparison: which class is more consistent?', hint1: 'Consistency relates to spread (IQR).', hint2: 'Smaller IQR = more consistent.', hint3: 'Class A (IQR 20) is more consistent than Class B (IQR 30).',\n"
    "          answer: 0, tolerance: 0, unit: '', checkType: 'skip', displayAnswer: 'B: higher median, greater spread — less consistent',\n"
    "          explanation: 'Class B has a higher median but greater spread (IQR 30 vs 20), making it less consistent. Class A performed more uniformly.',\n"
    "        },\n"
    "      ],\n"
    "      workedExample: {\n"
    "        question: 'Group X: median = 50, IQR = 15. Group Y: median = 58, IQR = 22. Compare the two groups.',\n"
    "        steps: [\n"
    "          'Median — Y has the higher median: 58 > 50, so <strong>Group Y scored higher on average</strong>',\n"
    "          'Spread — Y has greater spread: IQR 22 > 15, so <strong>Group Y is less consistent</strong>',\n"
    "          'Summary — <strong>Group Y: higher median but less consistent than Group X</strong>',\n"
    "        ],\n"
    "      },\n"
    "      sampleAnswer: { grade4: 'Class B has the higher median. Class B has greater spread.', grade6: 'Class B has a higher median (68 > 65) and greater spread (IQR 30 > 20). Class A is more consistent.', grade8: 'Median: Class B (68) > Class A (65) — B performed better on average. IQR: B (30) > A (20) — B had more variability. Range: A = 50, B = 60. Overall, Class B scored slightly higher but was less consistent than Class A.' },\n"
    "      examinerTip: 'A full comparison needs: median (average), IQR (spread), and a contextual comment. Missing any of these costs marks.',\n"
    "      auditStatus: 'pending',\n"
    "    },\n"

    # ── stat-boxplots-B03 ──────────────────────────────────────────
    "    {\n"
    "      id: 'stat-boxplots-B03', subtopic: 'stat-boxplots', band: 'B', marks: 4,\n"
    "      question: 'Find the five-number summary for this dataset: 12, 15, 18, 21, 24, 27, 30, 35, 40.',\n"
    "      steps: [\n"
    "        {\n"
    "          prompt: 'State the minimum and maximum values. Enter the maximum.', hint1: 'The data is already sorted.', hint2: 'Smallest = 12, largest = ?', hint3: 'Min = 12, max = 40',\n"
    "          answer: 40, tolerance: 0, unit: '',\n"
    "          explanation: 'Min = 12, max = 40 (the smallest and largest values in the dataset).',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'Find the median (middle value of 9 data points).', hint1: 'n = 9, so median is the 5th value.', hint2: 'Count to the 5th value: 12, 15, 18, 21, 24, ...', hint3: 'Median = 24 (the 5th value)',\n"
    "          answer: 24, tolerance: 0, unit: '',\n"
    "          explanation: 'n = 9. Median is the 5th value: 12, 15, 18, 21, <strong>24</strong>, 27, 30, 35, 40. Median = 24.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'Find Q1 (median of the lower half: {12, 15, 18, 21}).', hint1: 'Lower half has 4 values: 12, 15, 18, 21.', hint2: 'Median of 4 values = mean of 2nd and 3rd.', hint3: 'Q1 = (15 + 18) ÷ 2 = 16.5',\n"
    "          answer: 16.5, tolerance: 0, unit: '',\n"
    "          explanation: 'Lower half: {12, 15, 18, 21}. Q1 = (15 + 18) ÷ 2 = 33 ÷ 2 = 16.5.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'Find Q3 (median of the upper half: {27, 30, 35, 40}).', hint1: 'Upper half has 4 values: 27, 30, 35, 40.', hint2: 'Median of 4 values = mean of 2nd and 3rd.', hint3: 'Q3 = (30 + 35) ÷ 2 = 32.5',\n"
    "          answer: 32.5, tolerance: 0, unit: '',\n"
    "          explanation: 'Upper half: {27, 30, 35, 40}. Q3 = (30 + 35) ÷ 2 = 65 ÷ 2 = 32.5.',\n"
    "        },\n"
    "      ],\n"
    "      workedExample: {\n"
    "        question: 'Find the five-number summary for: 5, 8, 11, 14, 17, 20, 23.',\n"
    "        steps: [\n"
    "          'Min and max — Min = 5, max = <strong>23</strong>',\n"
    "          'Median — n = 7; 4th value = <strong>14</strong>',\n"
    "          'Q1 — Lower half {5, 8, 11}; median = <strong>8</strong>',\n"
    "          'Q3 — Upper half {17, 20, 23}; median = <strong>20</strong>',\n"
    "        ],\n"
    "      },\n"
    "      sampleAnswer: { grade4: 'Min = 12, Q1 = 16.5, median = 24, Q3 = 32.5, max = 40.', grade6: 'Sorted: 12, 15, 18, 21, 24, 27, 30, 35, 40. Min = 12, max = 40, median = 24 (5th value), Q1 = 16.5 (median of lower 4), Q3 = 32.5 (median of upper 4).', grade8: 'Five-number summary: min = 12, Q1 = (15+18)/2 = 16.5, median = 24 (5th of 9), Q3 = (30+35)/2 = 32.5, max = 40. IQR = 32.5 − 16.5 = 16.' },\n"
    "      examinerTip: 'When n is odd, the median value is excluded from the lower and upper halves when finding Q1 and Q3.',\n"
    "      auditStatus: 'pending',\n"
    "    },\n"

    # ── stat-boxplots-B04 ──────────────────────────────────────────
    "    {\n"
    "      id: 'stat-boxplots-B04', subtopic: 'stat-boxplots', band: 'B', marks: 3,\n"
    "      question: 'Q1 = 15, Q3 = 33, max = 58, min = 4. Using the outlier fence Q3 + 1.5 × IQR, determine whether the maximum value is an outlier.',\n"
    "      steps: [\n"
    "        {\n"
    "          prompt: 'Calculate the IQR.', hint1: 'IQR = Q3 − Q1', hint2: 'IQR = 33 − 15', hint3: 'IQR = 33 − 15 = 18',\n"
    "          answer: 18, tolerance: 0, unit: '',\n"
    "          explanation: 'IQR = Q3 − Q1 = 33 − 15 = 18.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'Calculate the upper fence (Q3 + 1.5 × IQR).', hint1: 'Upper fence = Q3 + 1.5 × IQR', hint2: '= 33 + 1.5 × 18 = 33 + 27', hint3: '= 33 + 27 = 60',\n"
    "          answer: 60, tolerance: 0, unit: '',\n"
    "          explanation: 'Upper fence = 33 + 1.5 × 18 = 33 + 27 = 60.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'Is max = 58 an outlier? Compare to the upper fence.', hint1: 'A value exceeding the fence is an outlier.', hint2: 'Is 58 > 60?', hint3: '58 < 60, so it is NOT an outlier.',\n"
    "          answer: 0, tolerance: 0, unit: '', checkType: 'skip', displayAnswer: '58 < 60 → NOT an outlier',\n"
    "          explanation: 'max = 58 < upper fence = 60. The maximum value is NOT an outlier.',\n"
    "        },\n"
    "      ],\n"
    "      workedExample: {\n"
    "        question: 'Q1 = 8, Q3 = 20. Is a maximum value of 41 an outlier?',\n"
    "        steps: [\n"
    "          'IQR — Q3 − Q1 = 20 − 8 = <strong>12</strong>',\n"
    "          'Upper fence — Q3 + 1.5 × IQR = 20 + 18 = <strong>38</strong>',\n"
    "          'Check — 41 > 38, so 41 <strong>IS an outlier</strong>',\n"
    "        ],\n"
    "      },\n"
    "      sampleAnswer: { grade4: 'IQR = 18. Upper fence = 60. 58 is not an outlier.', grade6: 'IQR = 33 − 15 = 18. Upper fence = 33 + 1.5 × 18 = 60. Since 58 < 60, the maximum is not an outlier.', grade8: 'IQR = 18. Upper fence = Q3 + 1.5 × IQR = 33 + 27 = 60. The maximum value of 58 is below this threshold, so it is not classified as an outlier.' },\n"
    "      examinerTip: 'Show all three steps: IQR → fence → comparison. A one-line answer without the fence calculation will not gain full marks.',\n"
    "      auditStatus: 'pending',\n"
    "    },\n"

    # ── stat-boxplots-B05 ──────────────────────────────────────────
    "    {\n"
    "      id: 'stat-boxplots-B05', subtopic: 'stat-boxplots', band: 'B', marks: 2,\n"
    "      question: 'A box plot shows median = 30, Q1 = 24, Q3 = 45. Determine the direction of skew and justify your answer.',\n"
    "      steps: [\n"
    "        {\n"
    "          prompt: 'Find Q3 − median and median − Q1. Enter Q3 − median.', hint1: 'Q3 − median = 45 − 30', hint2: 'Q3 − median = 15; median − Q1 = 30 − 24 = 6', hint3: 'Upper half (15) is wider than lower half (6).',\n"
    "          answer: 15, tolerance: 0, unit: '',\n"
    "          explanation: 'Q3 − median = 45 − 30 = 15. median − Q1 = 30 − 24 = 6. The upper half of the box is wider.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'What direction of skew does this indicate?', hint1: 'If Q3 − median > median − Q1, the data is skewed towards higher values.', hint2: 'Upper half wider → values extend more to the right.', hint3: 'Positive (right) skew.',\n"
    "          answer: 0, tolerance: 0, unit: '', checkType: 'skip', displayAnswer: 'Positive (right) skew — upper half wider',\n"
    "          explanation: 'Q3 − median (15) > median − Q1 (6), so the upper half of the box is wider. This indicates positive (right) skew — the data has a longer tail towards higher values.',\n"
    "        },\n"
    "      ],\n"
    "      workedExample: {\n"
    "        question: 'A box plot shows median = 40, Q1 = 32, Q3 = 46. Determine the direction of skew.',\n"
    "        steps: [\n"
    "          'Q3 − median — 46 − 40 = <strong>6</strong>',\n"
    "          'median − Q1 — 40 − 32 = <strong>8</strong>',\n"
    "          'Skew — lower half wider (8 > 6) → <strong>negative (left) skew</strong>',\n"
    "        ],\n"
    "      },\n"
    "      sampleAnswer: { grade4: 'Positive skew — upper half of the box is wider.', grade6: 'Q3 − median = 15; median − Q1 = 6. Upper half is wider, indicating positive (right) skew.', grade8: 'Q3 − median = 45 − 30 = 15 and median − Q1 = 30 − 24 = 6. Since the upper half is wider (15 > 6), the distribution is positively skewed, with a longer tail towards higher values.' },\n"
    "      examinerTip: 'Skew from a box plot: compare the two halves of the box. Larger upper half = positive skew. Larger lower half = negative skew.',\n"
    "      auditStatus: 'pending',\n"
    "    },\n"

    # ── stat-boxplots-B06 ──────────────────────────────────────────
    "    {\n"
    "      id: 'stat-boxplots-B06', subtopic: 'stat-boxplots', band: 'B', marks: 3,\n"
    "      question: 'A box plot for n = 20 values shows Q1 = 18 and Q3 = 34. Find (a) the IQR, (b) how many values lie above Q3, and (c) how many lie between Q1 and Q3.',\n"
    "      steps: [\n"
    "        {\n"
    "          prompt: 'Calculate the IQR.', hint1: 'IQR = Q3 − Q1', hint2: 'IQR = 34 − 18', hint3: 'IQR = 34 − 18 = 16',\n"
    "          answer: 16, tolerance: 0, unit: '',\n"
    "          explanation: 'IQR = Q3 − Q1 = 34 − 18 = 16.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'How many of the 20 values lie above Q3?', hint1: '25% of data lies above Q3.', hint2: '25% of 20 = ?', hint3: '0.25 × 20 = 5',\n"
    "          answer: 5, tolerance: 0, unit: '',\n"
    "          explanation: '25% of data lies above Q3 (the upper quartile). 25% of 20 = 5 values.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'How many values lie between Q1 and Q3?', hint1: '50% of data lies between Q1 and Q3.', hint2: '50% of 20 = ?', hint3: '0.5 × 20 = 10',\n"
    "          answer: 10, tolerance: 0, unit: '',\n"
    "          explanation: '50% of data lies between Q1 and Q3. 50% of 20 = 10 values.',\n"
    "        },\n"
    "      ],\n"
    "      workedExample: {\n"
    "        question: 'A box plot for n = 40 values shows Q1 = 12 and Q3 = 30. Find the IQR, number above Q3, and number between Q1 and Q3.',\n"
    "        steps: [\n"
    "          'IQR — Q3 − Q1 = 30 − 12 = <strong>18</strong>',\n"
    "          'Above Q3 — 25% of 40 = <strong>10</strong> values',\n"
    "          'Between Q1 and Q3 — 50% of 40 = <strong>20</strong> values',\n"
    "        ],\n"
    "      },\n"
    "      sampleAnswer: { grade4: 'IQR = 16. 5 values above Q3. 10 between Q1 and Q3.', grade6: 'IQR = 34 − 18 = 16. Above Q3: 25% of 20 = 5. Between Q1 and Q3: 50% of 20 = 10.', grade8: 'IQR = 16. Quartile properties: 25% of 20 = 5 values lie above Q3; 50% of 20 = 10 values lie between Q1 and Q3 (the interquartile range).' },\n"
    "      examinerTip: 'Know your quartile percentages: 25% below Q1, 25% between Q1 and median, 25% between median and Q3, 25% above Q3.',\n"
    "      auditStatus: 'pending',\n"
    "    },\n"

    # ── stat-boxplots-C01 ──────────────────────────────────────────
    "    {\n"
    "      id: 'stat-boxplots-C01', subtopic: 'stat-boxplots', band: 'C', marks: 3,\n"
    "      question: 'Five-number summary: min = 8, Q1 = 15, median = 22, Q3 = 35, max = 62. (a) Find the upper outlier fence. (b) Is max = 62 an outlier? (c) Comment on the skewness.',\n"
    "      steps: [\n"
    "        {\n"
    "          prompt: 'Calculate IQR then find the upper fence (Q3 + 1.5 × IQR).', hint1: 'IQR = Q3 − Q1 = 35 − 15 = 20', hint2: 'Upper fence = 35 + 1.5 × 20', hint3: '= 35 + 30 = 65',\n"
    "          answer: 65, tolerance: 0, unit: '',\n"
    "          explanation: 'IQR = 35 − 15 = 20. Upper fence = 35 + 1.5 × 20 = 35 + 30 = 65. Since 62 < 65, the maximum is NOT an outlier.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'Find Q3 − median to assess the upper half of the box.', hint1: 'Q3 − median = 35 − 22', hint2: '= 13; median − Q1 = 22 − 15 = 7', hint3: 'Upper half (13) wider than lower half (7).',\n"
    "          answer: 13, tolerance: 0, unit: '',\n"
    "          explanation: 'Q3 − median = 35 − 22 = 13. median − Q1 = 22 − 15 = 7. The upper half of the box is wider.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'What does the box shape and the long upper whisker tell us about skewness?', hint1: 'Upper half of box wider → data extends more towards high values.', hint2: 'Q3 − median (13) > median − Q1 (7)', hint3: 'Positive (right) skew.',\n"
    "          answer: 0, tolerance: 0, unit: '', checkType: 'skip', displayAnswer: 'Positive skew (Q3 − median > median − Q1)',\n"
    "          explanation: 'Since Q3 − median (13) > median − Q1 (7), the distribution is positively skewed. The data has a longer tail towards higher values.',\n"
    "        },\n"
    "      ],\n"
    "      workedExample: {\n"
    "        question: 'Five-number summary: Q1 = 20, median = 30, Q3 = 50, max = 75. Check for outlier (IQR = 30) and comment on skew.',\n"
    "        steps: [\n"
    "          'Upper fence — Q3 + 1.5 × 30 = 50 + 45 = <strong>95</strong>; 75 < 95 → not an outlier',\n"
    "          'Q3 − median — 50 − 30 = <strong>20</strong>',\n"
    "          'median − Q1 — 30 − 20 = <strong>10</strong>',\n"
    "          'Skew — upper half wider (20 > 10) → <strong>positive skew</strong>',\n"
    "        ],\n"
    "      },\n"
    "      sampleAnswer: { grade4: 'Upper fence = 65. 62 is not an outlier. The distribution is positively skewed.', grade6: 'IQR = 20. Upper fence = 35 + 30 = 65. max = 62 < 65, not an outlier. Q3 − median = 13 > median − Q1 = 7, so positively skewed.', grade8: 'IQR = 20. Upper fence = Q3 + 1.5 × IQR = 65. Since max (62) < 65, it is not an outlier. Box skew: Q3 − median = 13 vs median − Q1 = 7 — upper half wider confirms positive skew with a longer right tail.' },\n"
    "      examinerTip: 'For a 3-part question: IQR → fence → compare; then box halves → skew direction. Set out each step clearly.',\n"
    "      auditStatus: 'pending',\n"
    "    },\n"

    # ── stat-boxplots-C02 ──────────────────────────────────────────
    "    {\n"
    "      id: 'stat-boxplots-C02', subtopic: 'stat-boxplots', band: 'C', marks: 4,\n"
    "      question: \"Boys' weights (kg): min = 55, Q1 = 63, median = 70, Q3 = 79, max = 92. Girls' weights (kg): min = 48, Q1 = 57, median = 65, Q3 = 72, max = 85. Write a full 4-point comparison.\",\n"
    "      steps: [\n"
    "        {\n"
    "          prompt: \"Compare the medians. Which group is typically heavier?\", hint1: 'Compare boys median (70) and girls median (65).', hint2: '70 > 65', hint3: 'Boys have the higher median — typically heavier.',\n"
    "          answer: 0, tolerance: 0, unit: '', checkType: 'skip', displayAnswer: 'Boys higher median (70 > 65)',\n"
    "          explanation: 'Boys have a higher median weight (70 kg > 65 kg), so boys are typically heavier.',\n"
    "        },\n"
    "        {\n"
    "          prompt: \"Find IQR for boys (Q3 − Q1). Enter boys' IQR.\", hint1: 'IQR_boys = Q3 − Q1 = 79 − 63', hint2: '= 16', hint3: 'IQR_boys = 16; IQR_girls = 72 − 57 = 15. Similar spread.',\n"
    "          answer: 16, tolerance: 0, unit: '',\n"
    "          explanation: 'IQR_boys = 79 − 63 = 16. IQR_girls = 72 − 57 = 15. Spread is similar (IQR roughly equal).',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'Compare the ranges. Find the range for boys.', hint1: 'Range_boys = max − min = 92 − 55', hint2: '= 37', hint3: 'Range_boys = 37; Range_girls = 85 − 48 = 37. Identical overall range.',\n"
    "          answer: 37, tolerance: 0, unit: '',\n"
    "          explanation: 'Range_boys = 92 − 55 = 37. Range_girls = 85 − 48 = 37. Both have identical overall range.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'Write an overall summary comparing both groups.', hint1: 'Consider median, IQR and range together.', hint2: 'Boys heavier on average; similar variability.', hint3: 'Boys generally heavier; spread is similar for both groups.',\n"
    "          answer: 0, tolerance: 0, unit: '', checkType: 'skip', displayAnswer: 'Boys heavier overall; similar variability',\n"
    "          explanation: 'Boys are generally heavier (higher median) but both groups show similar variability (comparable IQR and range).',\n"
    "        },\n"
    "      ],\n"
    "      workedExample: {\n"
    "        question: 'Group A: Q1 = 40, Q3 = 60, median = 50, min = 30, max = 75. Group B: Q1 = 44, Q3 = 62, median = 55, min = 32, max = 78. Write a comparison.',\n"
    "        steps: [\n"
    "          'Medians — B (55) > A (50): <strong>Group B has higher typical value</strong>',\n"
    "          'IQR — A: 60−40=20; B: 62−44=18: <strong>similar spread, A slightly wider</strong>',\n"
    "          'Range — A: 75−30=45; B: 78−32=46: <strong>virtually identical overall spread</strong>',\n"
    "          'Summary — <strong>Group B scores slightly higher on average with similar consistency</strong>',\n"
    "        ],\n"
    "      },\n"
    "      sampleAnswer: { grade4: 'Boys have a higher median. Both groups have similar spread.', grade6: 'Boys have a higher median weight (70 > 65). IQRs are similar (boys 16, girls 15). Both have the same range (37). Boys are typically heavier with similar variability.', grade8: 'Median: boys (70) > girls (65) — boys are typically heavier. IQR: boys (16) ≈ girls (15) — similar central spread. Range: both = 37 — identical overall spread. Conclusion: boys are generally heavier but both groups are equally consistent.' },\n"
    "      examinerTip: 'A 4-mark comparison needs four distinct points: median, IQR, range, and a contextual summary. Use the context (weights, not just numbers).',\n"
    "      auditStatus: 'pending',\n"
    "    },\n"

    # ── stat-boxplots-C03 ──────────────────────────────────────────
    "    {\n"
    "      id: 'stat-boxplots-C03', subtopic: 'stat-boxplots', band: 'C', marks: 2,\n"
    "      question: 'A box plot has Q1 = 20 and IQR = 18. The dataset has n = 120 values. Find (a) Q3 and (b) the number of values between Q1 and Q3.',\n"
    "      steps: [\n"
    "        {\n"
    "          prompt: 'Find Q3 using Q1 and the IQR.', hint1: 'Q3 = Q1 + IQR', hint2: 'Q3 = 20 + 18', hint3: 'Q3 = 20 + 18 = 38',\n"
    "          answer: 38, tolerance: 0, unit: '',\n"
    "          explanation: 'Q3 = Q1 + IQR = 20 + 18 = 38.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'How many of the 120 values lie between Q1 and Q3?', hint1: '50% of values lie between Q1 and Q3.', hint2: '50% of 120 = ?', hint3: '0.5 × 120 = 60',\n"
    "          answer: 60, tolerance: 0, unit: '',\n"
    "          explanation: '50% of data lies between Q1 and Q3. 50% of 120 = 60 values.',\n"
    "        },\n"
    "      ],\n"
    "      workedExample: {\n"
    "        question: 'Q1 = 25, IQR = 16, n = 80. Find Q3 and the number of values between Q1 and Q3.',\n"
    "        steps: [\n"
    "          'Q3 — Q1 + IQR = 25 + 16 = <strong>41</strong>',\n"
    "          'Values between Q1 and Q3 — 50% of 80 = <strong>40</strong>',\n"
    "        ],\n"
    "      },\n"
    "      sampleAnswer: { grade4: 'Q3 = 38. 60 values between Q1 and Q3.', grade6: 'Q3 = Q1 + IQR = 20 + 18 = 38. Values between Q1 and Q3: 50% of 120 = 60.', grade8: 'Q3 = Q1 + IQR = 20 + 18 = 38. Since 50% of data lies between the quartiles, 0.5 × 120 = 60 values lie between Q1 = 20 and Q3 = 38.' },\n"
    "      examinerTip: 'If given Q1 and IQR, find Q3 by adding: Q3 = Q1 + IQR. Then use the 50% rule for values in the box.',\n"
    "      auditStatus: 'pending',\n"
    "    },\n"

    # ── stat-boxplots-C04 ──────────────────────────────────────────
    "    {\n"
    "      id: 'stat-boxplots-C04', subtopic: 'stat-boxplots', band: 'C', marks: 3,\n"
    "      question: 'A dataset of 40 values has mean = 32 and median = 28. The box plot shows Q1 = 20 and Q3 = 40. (a) Comment on skewness from the box plot. (b) Comment on skewness from mean vs median. (c) Are these two indicators consistent?',\n"
    "      steps: [\n"
    "        {\n"
    "          prompt: 'Assess skewness using the box plot (compare Q3 − median and median − Q1).', hint1: 'Q3 − median = 40 − 28 = 12; median − Q1 = 28 − 20 = 8', hint2: 'Upper half of box is wider (12 > 8)', hint3: 'Positive skew from box plot.',\n"
    "          answer: 0, tolerance: 0, unit: '', checkType: 'skip', displayAnswer: 'Positive skew: Q3 − median (12) > median − Q1 (8)',\n"
    "          explanation: 'Q3 − median = 40 − 28 = 12. median − Q1 = 28 − 20 = 8. Upper half wider → positive (right) skew from box plot.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'Assess skewness using mean vs median. What does mean > median indicate?', hint1: 'Compare mean (32) and median (28).', hint2: 'Mean > median → the mean is pulled towards higher values.', hint3: 'Mean > median → positive skew.',\n"
    "          answer: 0, tolerance: 0, unit: '', checkType: 'skip', displayAnswer: 'Mean > Median → positive skew',\n"
    "          explanation: 'Mean (32) > median (28). When the mean is greater than the median, the distribution is positively skewed — the mean is pulled right by higher values.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'Are the two skewness indicators consistent with each other?', hint1: 'Both methods give a direction of skew — do they agree?', hint2: 'Box plot → positive skew. Mean vs median → positive skew.', hint3: 'Yes, both consistently indicate positive skew.',\n"
    "          answer: 0, tolerance: 0, unit: '', checkType: 'skip', displayAnswer: 'Consistent — both indicate positive skew',\n"
    "          explanation: 'Both indicators point to positive skew: the box plot shows the upper half wider, and mean > median. They are consistent.',\n"
    "        },\n"
    "      ],\n"
    "      workedExample: {\n"
    "        question: 'A dataset has median = 50, Q1 = 40, Q3 = 58, mean = 47. Assess skewness from both indicators.',\n"
    "        steps: [\n"
    "          'Box plot — Q3 − med = 8; med − Q1 = 10: lower half wider → <strong>negative skew</strong>',\n"
    "          'Mean vs median — mean (47) < median (50) → <strong>negative skew</strong>',\n"
    "          'Consistent — <strong>both indicators agree: negative (left) skew</strong>',\n"
    "        ],\n"
    "      },\n"
    "      sampleAnswer: { grade4: 'Both indicators show positive skew. They are consistent.', grade6: 'Box plot: Q3 − median = 12 > median − Q1 = 8 → positive skew. Mean (32) > median (28) → positive skew. Both consistent.', grade8: 'Box plot skew: Q3 − median = 12 vs median − Q1 = 8 — upper half wider indicates positive skew. Mean–median skew: mean (32) > median (28) — mean pulled rightwards by high values, confirming positive skew. The two indicators are consistent.' },\n"
    "      examinerTip: 'Two methods to identify skew: (1) box plot — compare box halves; (2) mean vs median — mean > median means positive skew. Examiners reward both methods used together.',\n"
    "      auditStatus: 'pending',\n"
    "    },\n"
)

with open(FILE, 'r', encoding='utf-8') as f:
    content = f.read()

pos = content.find(MARKER)
if pos == -1:
    print("MARKER NOT FOUND")
    sys.exit(1)

print(f"Inserting at character position {pos}")

content = content[:pos] + NEW + content[pos:]

with open(FILE, 'w', encoding='utf-8') as f:
    f.write(content)

print("Done — inserted BOX PLOTS section header + 15 stat-boxplots questions (5A, 6B, 4C) into js/maths-questions.js")
