import sys

FILE = r'C:\Users\jason\OneDrive\Documents\GitHub\mabel-gcse\js\maths-questions.js'
MARKER = "\n\n    // ── pct-A04 ──────────────────────────────────────────────"

NEW = (
    "\n\n    // ══════════════════════════════════════════════════════════\n"
    "    // SAMPLING (stat-sampling)\n"
    "    // ══════════════════════════════════════════════════════════\n"

    # ── stat-sampling-A01 ──────────────────────────────────────────
    "    {\n"
    "      id: 'stat-sampling-A01', subtopic: 'stat-sampling', band: 'A', marks: 2,\n"
    "      question: 'A school has 300 students: 120 in Year 10 and 180 in Year 11. A stratified sample of 50 is required. How many students should be selected from each year group?',\n"
    "      steps: [\n"
    "        {\n"
    "          prompt: 'How many students should be selected from Year 10?', hint1: 'Year 10 fraction = 120 ÷ 300', hint2: '= 0.4; multiply by sample size 50', hint3: '0.4 × 50 = 20',\n"
    "          answer: 20, tolerance: 0, unit: '',\n"
    "          explanation: 'Year 10: (120 ÷ 300) × 50 = 0.4 × 50 = 20 students.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'How many students should be selected from Year 11?', hint1: 'Year 11 fraction = 180 ÷ 300', hint2: '= 0.6; multiply by 50', hint3: '0.6 × 50 = 30; check: 20 + 30 = 50 ✓',\n"
    "          answer: 30, tolerance: 0, unit: '',\n"
    "          explanation: 'Year 11: (180 ÷ 300) × 50 = 0.6 × 50 = 30 students. Check: 20 + 30 = 50 ✓',\n"
    "        },\n"
    "      ],\n"
    "      workedExample: {\n"
    "        question: 'A school has 400 students: 160 in Year 9 and 240 in Year 10. A stratified sample of 25 is required. How many from each year?',\n"
    "        steps: [\n"
    "          'Year 9 — (160 ÷ 400) × 25 = 0.4 × 25 = <strong>10</strong>',\n"
    "          'Year 10 — (240 ÷ 400) × 25 = 0.6 × 25 = <strong>15</strong>; check: 10 + 15 = 25 ✓',\n"
    "        ],\n"
    "      },\n"
    "      sampleAnswer: { grade4: 'Year 10: 20 students; Year 11: 30 students.', grade6: 'Year 10: (120/300) × 50 = 20. Year 11: (180/300) × 50 = 30. Total: 50 ✓', grade8: 'Stratified sample — proportional allocation. Year 10: (120/300) × 50 = 20. Year 11: (180/300) × 50 = 30. Total = 50 ✓. Each year group is represented in proportion to its size.' },\n"
    "      examinerTip: 'Stratified sampling: (group size ÷ total) × sample size. Always check your answers add up to the total sample size.',\n"
    "      auditStatus: 'pending',\n"
    "    },\n"

    # ── stat-sampling-A02 ──────────────────────────────────────────
    "    {\n"
    "      id: 'stat-sampling-A02', subtopic: 'stat-sampling', band: 'A', marks: 2,\n"
    "      question: 'A quality control team samples 5% of 2000 items produced each day. (a) How many items are sampled? (b) If 8 are defective, estimate the total number of defective items in the batch.',\n"
    "      steps: [\n"
    "        {\n"
    "          prompt: 'How many items are sampled (5% of 2000)?', hint1: '5% = 0.05', hint2: '0.05 × 2000', hint3: '0.05 × 2000 = 100',\n"
    "          answer: 100, tolerance: 0, unit: '',\n"
    "          explanation: '5% of 2000 = 0.05 × 2000 = 100 items sampled.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'Estimate the total defective items in the full batch of 2000.', hint1: 'Defect rate in sample = 8 ÷ 100 = 0.08', hint2: 'Apply rate to full batch: 0.08 × 2000', hint3: '0.08 × 2000 = 160',\n"
    "          answer: 160, tolerance: 0, unit: '',\n"
    "          explanation: 'Defect rate = 8 ÷ 100 = 0.08. Estimated total defective = 0.08 × 2000 = 160 items.',\n"
    "        },\n"
    "      ],\n"
    "      workedExample: {\n"
    "        question: 'A team samples 2% of 1500 items. 3 are found defective. Estimate the total defective items in the batch.',\n"
    "        steps: [\n"
    "          'Sample size — 2% of 1500 = 0.02 × 1500 = <strong>30</strong>',\n"
    "          'Defect rate — 3 ÷ 30 = <strong>0.1</strong>',\n"
    "          'Estimated defectives — 0.1 × 1500 = <strong>150</strong>',\n"
    "        ],\n"
    "      },\n"
    "      sampleAnswer: { grade4: '100 items sampled. Estimated 160 defective in the batch.', grade6: '5% of 2000 = 100 items. Defect rate = 8/100 = 0.08. Estimated defectives = 0.08 × 2000 = 160.', grade8: 'Sample size = 0.05 × 2000 = 100. Defect rate = 8/100 = 0.08 (8%). Applying to full batch: 0.08 × 2000 = 160 estimated defective items.' },\n"
    "      examinerTip: 'To estimate a total from a sample: find the proportion in the sample, then multiply by the population size.',\n"
    "      auditStatus: 'pending',\n"
    "    },\n"

    # ── stat-sampling-A03 ──────────────────────────────────────────
    "    {\n"
    "      id: 'stat-sampling-A03', subtopic: 'stat-sampling', band: 'A', marks: 2,\n"
    "      question: 'A sample of 50 products contains 12 defective items. Estimate the number of defective items in a batch of 500.',\n"
    "      steps: [\n"
    "        {\n"
    "          prompt: 'Calculate the proportion of defective items in the sample.', hint1: 'Proportion = defective ÷ sample size', hint2: '= 12 ÷ 50', hint3: '12 ÷ 50 = 0.24',\n"
    "          answer: 0.24, tolerance: 0.005, unit: '',\n"
    "          explanation: 'Proportion defective = 12 ÷ 50 = 0.24 (24%).',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'Estimate the total defective items in a batch of 500.', hint1: 'Estimated defectives = proportion × batch size', hint2: '= 0.24 × 500', hint3: '0.24 × 500 = 120',\n"
    "          answer: 120, tolerance: 0, unit: '',\n"
    "          explanation: 'Estimated defectives = 0.24 × 500 = 120 items.',\n"
    "        },\n"
    "      ],\n"
    "      workedExample: {\n"
    "        question: 'A sample of 40 products contains 8 defective items. Estimate the defectives in a batch of 600.',\n"
    "        steps: [\n"
    "          'Proportion — 8 ÷ 40 = <strong>0.2</strong>',\n"
    "          'Estimated defectives — 0.2 × 600 = <strong>120</strong>',\n"
    "        ],\n"
    "      },\n"
    "      sampleAnswer: { grade4: 'Proportion = 0.24. Estimated defectives = 120.', grade6: 'Defect rate = 12/50 = 0.24. Estimated defectives in 500 = 0.24 × 500 = 120.', grade8: 'Sample defect rate = 12/50 = 0.24. Assuming this rate applies to the full batch: estimated defectives = 0.24 × 500 = 120 items.' },\n"
    "      examinerTip: 'Always find the rate (proportion) first, then scale up to the full population. Show both steps.',\n"
    "      auditStatus: 'pending',\n"
    "    },\n"

    # ── stat-sampling-A04 ──────────────────────────────────────────
    "    {\n"
    "      id: 'stat-sampling-A04', subtopic: 'stat-sampling', band: 'A', marks: 2,\n"
    "      question: 'Systematic sampling is used from a list of 400 names. A sample of 20 is needed. (a) Find the sampling interval. (b) If the first person selected is number 7, what is the number of the next person selected?',\n"
    "      steps: [\n"
    "        {\n"
    "          prompt: 'Calculate the sampling interval.', hint1: 'Sampling interval = population size ÷ sample size', hint2: '= 400 ÷ 20', hint3: '= 20',\n"
    "          answer: 20, tolerance: 0, unit: '',\n"
    "          explanation: 'Sampling interval = 400 ÷ 20 = 20. Every 20th person is selected.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'If the first person is number 7, what is the next person selected?', hint1: 'Add the sampling interval to the first person.', hint2: '7 + 20', hint3: '7 + 20 = 27',\n"
    "          answer: 27, tolerance: 0, unit: '',\n"
    "          explanation: 'Next person = first + interval = 7 + 20 = 27.',\n"
    "        },\n"
    "      ],\n"
    "      workedExample: {\n"
    "        question: 'Systematic sample from 300 names, sample size 15. First selected is number 4. Find the interval and the next person.',\n"
    "        steps: [\n"
    "          'Interval — 300 ÷ 15 = <strong>20</strong>',\n"
    "          'Next person — 4 + 20 = <strong>24</strong>',\n"
    "        ],\n"
    "      },\n"
    "      sampleAnswer: { grade4: 'Sampling interval = 20. Next person = 27.', grade6: 'Sampling interval = 400 ÷ 20 = 20. Next person = 7 + 20 = 27.', grade8: 'Sampling interval = 400 ÷ 20 = 20. Starting at person 7, the sequence is 7, 27, 47, ... The next person after 7 is 7 + 20 = 27.' },\n"
    "      examinerTip: 'Systematic sampling interval = population ÷ sample size. The starting point is chosen randomly within the first interval.',\n"
    "      auditStatus: 'pending',\n"
    "    },\n"

    # ── stat-sampling-A05 ──────────────────────────────────────────
    "    {\n"
    "      id: 'stat-sampling-A05', subtopic: 'stat-sampling', band: 'A', marks: 2,\n"
    "      question: 'A researcher systematically samples every 10th person from a queue of 500. The first person selected is number 3. (a) How many people are in the sample? (b) What is the number of the last person selected?',\n"
    "      steps: [\n"
    "        {\n"
    "          prompt: 'How many people are in the sample?', hint1: 'Sample size = population ÷ interval', hint2: '= 500 ÷ 10', hint3: '= 50',\n"
    "          answer: 50, tolerance: 0, unit: '',\n"
    "          explanation: 'Sample size = 500 ÷ 10 = 50 people.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'What is the number of the last person selected?', hint1: 'Last = first + (n − 1) × interval', hint2: '= 3 + (50 − 1) × 10 = 3 + 490', hint3: '= 493',\n"
    "          answer: 493, tolerance: 0, unit: '',\n"
    "          explanation: 'Last person = 3 + (50 − 1) × 10 = 3 + 490 = 493.',\n"
    "        },\n"
    "      ],\n"
    "      workedExample: {\n"
    "        question: 'Every 8th person is sampled from a queue of 400. First selected is person 5. Find the sample size and last person selected.',\n"
    "        steps: [\n"
    "          'Sample size — 400 ÷ 8 = <strong>50</strong>',\n"
    "          'Last person — 5 + (50 − 1) × 8 = 5 + 392 = <strong>397</strong>',\n"
    "        ],\n"
    "      },\n"
    "      sampleAnswer: { grade4: 'Sample size = 50. Last person = 493.', grade6: 'Sample size = 500 ÷ 10 = 50. Last person = 3 + 49 × 10 = 493.', grade8: 'Sample size = 500 ÷ 10 = 50. Sequence: 3, 13, 23, …, last = first + (n−1) × interval = 3 + 49 × 10 = 493.' },\n"
    "      examinerTip: 'For the last value in systematic sampling: last = first + (n − 1) × interval. Check it does not exceed the population size.',\n"
    "      auditStatus: 'pending',\n"
    "    },\n"

    # ── stat-sampling-B01 ──────────────────────────────────────────
    "    {\n"
    "      id: 'stat-sampling-B01', subtopic: 'stat-sampling', band: 'B', marks: 4,\n"
    "      question: 'A company has 4 departments: Sales = 60, Marketing = 30, Finance = 40, HR = 20. Total = 150. A stratified sample of 30 is required. Find the number of employees to select from each department.',\n"
    "      steps: [\n"
    "        {\n"
    "          prompt: 'How many from Sales?', hint1: 'Sales fraction = 60 ÷ 150', hint2: '= 0.4; × 30', hint3: '0.4 × 30 = 12',\n"
    "          answer: 12, tolerance: 0, unit: '',\n"
    "          explanation: 'Sales: (60 ÷ 150) × 30 = 0.4 × 30 = 12.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'How many from Marketing?', hint1: 'Marketing fraction = 30 ÷ 150', hint2: '= 0.2; × 30', hint3: '0.2 × 30 = 6',\n"
    "          answer: 6, tolerance: 0, unit: '',\n"
    "          explanation: 'Marketing: (30 ÷ 150) × 30 = 0.2 × 30 = 6.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'How many from Finance?', hint1: 'Finance fraction = 40 ÷ 150', hint2: '≈ 0.267; × 30', hint3: '(40/150) × 30 = 8',\n"
    "          answer: 8, tolerance: 0, unit: '',\n"
    "          explanation: 'Finance: (40 ÷ 150) × 30 = 8.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'How many from HR? Verify the total.', hint1: 'HR fraction = 20 ÷ 150', hint2: '= (20/150) × 30', hint3: '= 4; check: 12 + 6 + 8 + 4 = 30 ✓',\n"
    "          answer: 4, tolerance: 0, unit: '',\n"
    "          explanation: 'HR: (20 ÷ 150) × 30 = 4. Total: 12 + 6 + 8 + 4 = 30 ✓',\n"
    "        },\n"
    "      ],\n"
    "      workedExample: {\n"
    "        question: 'Company departments: A = 80, B = 40, C = 30. Total = 150. Stratified sample of 15.',\n"
    "        steps: [\n"
    "          'A — (80 ÷ 150) × 15 = <strong>8</strong>',\n"
    "          'B — (40 ÷ 150) × 15 = <strong>4</strong>',\n"
    "          'C — (30 ÷ 150) × 15 = <strong>3</strong>; total: 8 + 4 + 3 = 15 ✓',\n"
    "        ],\n"
    "      },\n"
    "      sampleAnswer: { grade4: 'Sales: 12, Marketing: 6, Finance: 8, HR: 4.', grade6: 'Sales: (60/150)×30=12. Marketing: (30/150)×30=6. Finance: (40/150)×30=8. HR: (20/150)×30=4. Total: 30 ✓', grade8: 'Sampling fraction = 30/150 = 1/5. Sales: 60×(1/5)=12. Marketing: 30×(1/5)=6. Finance: 40×(1/5)=8. HR: 20×(1/5)=4. Total: 30 ✓ Each department is represented proportionally.' },\n"
    "      examinerTip: 'Alternatively: find the sampling fraction (30÷150 = 1/5) and multiply each stratum by it. Always verify totals.',\n"
    "      auditStatus: 'pending',\n"
    "    },\n"

    # ── stat-sampling-B02 ──────────────────────────────────────────
    "    {\n"
    "      id: 'stat-sampling-B02', subtopic: 'stat-sampling', band: 'B', marks: 3,\n"
    "      question: 'A researcher stands outside a supermarket and surveys the first 50 people to enter. (a) Identify the sampling method. (b) Give one reason this sample is biased. (c) Suggest a better method.',\n"
    "      steps: [\n"
    "        {\n"
    "          prompt: 'What sampling method is being used?', hint1: 'The researcher takes whoever is conveniently available.', hint2: 'This is not random — people are selected by proximity.', hint3: 'Convenience (opportunity) sampling.',\n"
    "          answer: 0, tolerance: 0, unit: '', checkType: 'skip', displayAnswer: 'Convenience/opportunity sampling',\n"
    "          explanation: 'The researcher uses convenience (opportunity) sampling — selecting whoever is easily available at that time and place.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'Give one reason this sample may be biased.', hint1: 'Think about who is excluded from this sample.', hint2: 'Only people who shop at this store at this time are represented.', hint3: 'Excludes people who do not shop at this store/time — not representative of the wider public.',\n"
    "          answer: 0, tolerance: 0, unit: '', checkType: 'skip', displayAnswer: 'Only captures shoppers at that location/time',\n"
    "          explanation: 'The sample only represents people who shop at this particular supermarket at this specific time — it excludes people who shop elsewhere or at different times.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'Suggest a better sampling method.', hint1: 'Think of a method that gives everyone an equal chance of being selected.', hint2: 'Random sampling avoids the bias of convenience sampling.', hint3: 'Stratified random sampling from the local population.',\n"
    "          answer: 0, tolerance: 0, unit: '', checkType: 'skip', displayAnswer: 'Stratified random sampling',\n"
    "          explanation: 'A stratified random sample from the full local population would give a more representative result.',\n"
    "        },\n"
    "      ],\n"
    "      workedExample: {\n"
    "        question: 'Students are surveyed only during the lunch break. Identify the method, give one bias, and suggest an improvement.',\n"
    "        steps: [\n"
    "          'Method — <strong>Convenience sampling</strong> (only students at lunch are surveyed)',\n"
    "          'Bias — excludes students absent or not in the canteen at lunch; <strong>over-represents students with free periods</strong>',\n"
    "          'Better method — <strong>random sample from the school register</strong>',\n"
    "        ],\n"
    "      },\n"
    "      sampleAnswer: { grade4: 'Convenience sampling. It is biased because not everyone has an equal chance. Use random sampling instead.', grade6: 'Convenience sampling. Biased because only people at that store at that time are included — excludes others. Better: stratified random sample from the local population.', grade8: 'Method: convenience (opportunity) sampling. Bias: the sample only represents shoppers at this location and time — those who shop elsewhere, online, or at different times are excluded, making results unrepresentative. Improvement: use stratified random sampling from the local population using a sampling frame.' },\n"
    "      examinerTip: 'When criticising a sampling method, always say who is excluded as well as who is included. Vague answers like \"not random\" alone will not score full marks.',\n"
    "      auditStatus: 'pending',\n"
    "    },\n"

    # ── stat-sampling-B03 ──────────────────────────────────────────
    "    {\n"
    "      id: 'stat-sampling-B03', subtopic: 'stat-sampling', band: 'B', marks: 3,\n"
    "      question: 'A quota sample requires 30 males and 30 females. The researcher finds 30 males but only 22 females willing to participate, so adds 8 more males to reach 60 total. (a) State the intended ratio. (b) State the actual ratio. (c) What problem does this introduce?',\n"
    "      steps: [\n"
    "        {\n"
    "          prompt: 'What was the intended male:female ratio?', hint1: 'Intended: 30 males and 30 females.', hint2: '30:30 simplifies to?', hint3: '1:1 (equal numbers of each gender)',\n"
    "          answer: 0, tolerance: 0, unit: '', checkType: 'skip', displayAnswer: '1:1 intended ratio',\n"
    "          explanation: 'Intended ratio: 30 males : 30 females = 1:1.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'What is the actual male:female ratio (38 males, 22 females)?', hint1: '38 males : 22 females', hint2: 'Divide both by 2: 19:11', hint3: 'Actual ratio is 19:11',\n"
    "          answer: 0, tolerance: 0, unit: '', checkType: 'skip', displayAnswer: '19:11 (38 males : 22 females)',\n"
    "          explanation: 'Actual ratio: 38 males : 22 females = 19:11. The sample is now skewed towards males.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'What problem does this introduce into the sample?', hint1: 'Compare the intended and actual ratios.', hint2: 'Males are now over-represented.', hint3: 'The sample is biased towards males and does not represent the intended gender balance.',\n"
    "          answer: 0, tolerance: 0, unit: '', checkType: 'skip', displayAnswer: 'Biased towards males — not representative',\n"
    "          explanation: 'By adding extra males to compensate, the gender balance is destroyed. The sample is now biased towards males and results will not represent the target population equally.',\n"
    "        },\n"
    "      ],\n"
    "      workedExample: {\n"
    "        question: 'A researcher wants 20 children and 20 adults. They get 20 children but only 14 adults, so add 6 more children. Find the intended ratio, actual ratio, and the problem introduced.',\n"
    "        steps: [\n"
    "          'Intended ratio — 20:20 = <strong>1:1</strong>',\n"
    "          'Actual ratio — 26 children : 14 adults = <strong>13:7</strong>',\n"
    "          'Problem — <strong>sample is biased towards children</strong>; adults are under-represented',\n"
    "        ],\n"
    "      },\n"
    "      sampleAnswer: { grade4: 'Intended ratio 1:1. Actual 19:11. The sample is biased towards males.', grade6: 'Intended: 30:30 = 1:1. Actual: 38:22 = 19:11. Adding extra males skews the sample — it no longer represents equal gender balance.', grade8: 'Intended ratio: 1:1 (equal gender representation). Actual ratio: 38:22 = 19:11. Replacing missing females with additional males introduces gender bias — the sample over-represents males and the results cannot be generalised to a population with equal gender distribution.' },\n"
    "      examinerTip: 'Quota sampling fills quotas by convenience — if one group is hard to reach, the researcher may distort the sample to meet the total. This is a key weakness.',\n"
    "      auditStatus: 'pending',\n"
    "    },\n"

    # ── stat-sampling-B04 ──────────────────────────────────────────
    "    {\n"
    "      id: 'stat-sampling-B04', subtopic: 'stat-sampling', band: 'B', marks: 3,\n"
    "      question: 'A school has 200 Year 10 students (100 boys, 100 girls) and 300 Year 11 students (150 boys, 150 girls). Total = 500. A stratified sample of 50 is taken proportionally by year group. (a) How many from Year 10? (b) How many from Year 11? (c) How many Year 10 boys?',\n"
    "      steps: [\n"
    "        {\n"
    "          prompt: 'How many students from Year 10?', hint1: 'Year 10 proportion = 200 ÷ 500 = 2/5', hint2: '(2/5) × 50', hint3: '= 20',\n"
    "          answer: 20, tolerance: 0, unit: '',\n"
    "          explanation: 'Year 10: (200 ÷ 500) × 50 = 0.4 × 50 = 20 students.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'How many students from Year 11?', hint1: 'Year 11 proportion = 300 ÷ 500 = 3/5', hint2: '(3/5) × 50', hint3: '= 30; check: 20 + 30 = 50 ✓',\n"
    "          answer: 30, tolerance: 0, unit: '',\n"
    "          explanation: 'Year 11: (300 ÷ 500) × 50 = 0.6 × 50 = 30. Check: 20 + 30 = 50 ✓',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'How many of the Year 10 sample should be boys?', hint1: 'Within Year 10: boys proportion = 100 ÷ 200 = 1/2', hint2: '(1/2) × 20', hint3: '= 10',\n"
    "          answer: 10, tolerance: 0, unit: '',\n"
    "          explanation: 'Year 10 boys: (100 ÷ 200) × 20 = 0.5 × 20 = 10.',\n"
    "        },\n"
    "      ],\n"
    "      workedExample: {\n"
    "        question: 'Y9: 150 students (80 boys, 70 girls). Y10: 350 (180 boys, 170 girls). Total = 500. Sample = 50. Find: Y9 total, Y10 total, Y9 boys.',\n"
    "        steps: [\n"
    "          'Y9 — (150 ÷ 500) × 50 = <strong>15</strong>',\n"
    "          'Y10 — (350 ÷ 500) × 50 = <strong>35</strong>',\n"
    "          'Y9 boys — (80 ÷ 150) × 15 ≈ <strong>8</strong>',\n"
    "        ],\n"
    "      },\n"
    "      sampleAnswer: { grade4: 'Year 10: 20; Year 11: 30; Year 10 boys: 10.', grade6: 'Year 10: (200/500)×50=20. Year 11: (300/500)×50=30. Year 10 boys: (100/200)×20=10.', grade8: 'Year 10: (200/500)×50=20; Year 11: (300/500)×50=30 (total 50 ✓). Within Year 10, boys = 100/200 = 50%, so 0.5×20=10 boys in the Year 10 sample.' },\n"
    "      examinerTip: 'Two-stage stratification: first stratify by year group, then within each year group stratify by gender. Apply the proportion at each stage.',\n"
    "      auditStatus: 'pending',\n"
    "    },\n"

    # ── stat-sampling-B05 ──────────────────────────────────────────
    "    {\n"
    "      id: 'stat-sampling-B05', subtopic: 'stat-sampling', band: 'B', marks: 2,\n"
    "      question: 'A factory has 1200 items on a production line. A systematic sample of 40 is required. (a) Find the sampling interval. (b) Explain whether systematic sampling is truly random.',\n"
    "      steps: [\n"
    "        {\n"
    "          prompt: 'Calculate the sampling interval.', hint1: 'Interval = population ÷ sample size', hint2: '= 1200 ÷ 40', hint3: '= 30',\n"
    "          answer: 30, tolerance: 0, unit: '',\n"
    "          explanation: 'Sampling interval = 1200 ÷ 40 = 30. Select every 30th item.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'Is systematic sampling truly random? Explain.', hint1: 'Think about which part of the process is random.', hint2: 'Only the starting point is chosen randomly.', hint3: 'Not fully random — only the first item is chosen randomly; subsequent selections are fixed.',\n"
    "          answer: 0, tolerance: 0, unit: '', checkType: 'skip', displayAnswer: 'Not fully random — only first item is random',\n"
    "          explanation: 'Systematic sampling is not fully random. Only the starting point is randomly chosen; every subsequent selection is determined by the fixed interval. Items do not each have an independent chance of selection.',\n"
    "        },\n"
    "      ],\n"
    "      workedExample: {\n"
    "        question: 'A factory has 600 items. A systematic sample of 20 is needed. Find the interval and comment on randomness.',\n"
    "        steps: [\n"
    "          'Interval — 600 ÷ 20 = <strong>30</strong>',\n"
    "          'Randomness — <strong>only the first item is randomly chosen</strong>; the rest are fixed by the interval',\n"
    "        ],\n"
    "      },\n"
    "      sampleAnswer: { grade4: 'Interval = 30. Not truly random — only the first item is random.', grade6: 'Sampling interval = 1200 ÷ 40 = 30. Systematic sampling is not fully random: the first item is chosen randomly, but all other items are determined by the interval.', grade8: 'Interval = 30. Systematic sampling has limited randomness: the starting point (within the first 30) is chosen at random, but all subsequent items are fixed. This means not every possible sample of size 40 has an equal chance of selection.' },\n"
    "      examinerTip: 'Systematic sampling is practical and spread across the population, but it is only partially random. It can miss patterns that repeat at the same interval (periodicity bias).',\n"
    "      auditStatus: 'pending',\n"
    "    },\n"

    # ── stat-sampling-B06 ──────────────────────────────────────────
    "    {\n"
    "      id: 'stat-sampling-B06', subtopic: 'stat-sampling', band: 'B', marks: 4,\n"
    "      question: 'A population is divided into 4 strata with sizes 80, 120, 60, 40. Total = 300. A stratified sample of 60 is required. Find the sampling fraction and the number to select from each stratum.',\n"
    "      steps: [\n"
    "        {\n"
    "          prompt: 'Calculate the sampling fraction (sample ÷ population).', hint1: 'Sampling fraction = 60 ÷ 300', hint2: '= 0.2', hint3: '0.2 (or 1/5)',\n"
    "          answer: 0.2, tolerance: 0.005, unit: '',\n"
    "          explanation: 'Sampling fraction = 60 ÷ 300 = 0.2 (one fifth of the population).',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'How many from stratum 1 (size 80) and stratum 2 (size 120)? Enter the stratum 1 count.', hint1: 'Stratum 1: 80 × 0.2', hint2: '= 16; Stratum 2: 120 × 0.2 = 24', hint3: 'Stratum 1: 16, Stratum 2: 24',\n"
    "          answer: 16, tolerance: 0, unit: '',\n"
    "          explanation: 'Stratum 1: 80 × 0.2 = 16. Stratum 2: 120 × 0.2 = 24.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'How many from stratum 3 (size 60)?', hint1: 'Stratum 3: 60 × 0.2', hint2: '= 12', hint3: '12',\n"
    "          answer: 12, tolerance: 0, unit: '',\n"
    "          explanation: 'Stratum 3: 60 × 0.2 = 12.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'How many from stratum 4 (size 40)? Verify the total.', hint1: 'Stratum 4: 40 × 0.2', hint2: '= 8', hint3: 'Check: 16 + 24 + 12 + 8 = 60 ✓',\n"
    "          answer: 8, tolerance: 0, unit: '',\n"
    "          explanation: 'Stratum 4: 40 × 0.2 = 8. Total: 16 + 24 + 12 + 8 = 60 ✓',\n"
    "        },\n"
    "      ],\n"
    "      workedExample: {\n"
    "        question: '4 strata: 50, 100, 30, 20. Total = 200. Sample = 40. Find the sampling fraction and numbers from each stratum.',\n"
    "        steps: [\n"
    "          'Sampling fraction — 40 ÷ 200 = <strong>0.2 (1/5)</strong>',\n"
    "          'Stratum 1 — 50 × 0.2 = <strong>10</strong>',\n"
    "          'Stratum 2 — 100 × 0.2 = <strong>20</strong>',\n"
    "          'Stratum 3 — 30 × 0.2 = <strong>6</strong>',\n"
    "          'Stratum 4 — 20 × 0.2 = <strong>4</strong>; total: 10+20+6+4 = 40 ✓',\n"
    "        ],\n"
    "      },\n"
    "      sampleAnswer: { grade4: 'Fraction = 0.2. Strata: 16, 24, 12, 8.', grade6: 'Sampling fraction = 60/300 = 0.2. Strata: 80×0.2=16; 120×0.2=24; 60×0.2=12; 40×0.2=8. Total: 60 ✓', grade8: 'Sampling fraction = 60/300 = 1/5. Multiply each stratum by 1/5: stratum 1 → 16, stratum 2 → 24, stratum 3 → 12, stratum 4 → 8. Total = 60 ✓. Each stratum is proportionally represented.' },\n"
    "      examinerTip: 'Finding the sampling fraction first makes all four calculations straightforward. Always verify by summing all stratum samples.',\n"
    "      auditStatus: 'pending',\n"
    "    },\n"

    # ── stat-sampling-C01 ──────────────────────────────────────────
    "    {\n"
    "      id: 'stat-sampling-C01', subtopic: 'stat-sampling', band: 'C', marks: 4,\n"
    "      question: \"A newspaper runs an online poll. 1200 people respond: 780 say 'yes'. The newspaper claims '65% of the public support the policy.' (a) Calculate the percentage. (b) Identify the sampling method. (c) Give two reasons results are unreliable. (d) Suggest a better method.\",\n"
    "      steps: [\n"
    "        {\n"
    "          prompt: \"Calculate the percentage who said 'yes'.\", hint1: 'Percentage = (780 ÷ 1200) × 100', hint2: '= 0.65 × 100', hint3: '= 65%',\n"
    "          answer: 65, tolerance: 0.1, unit: '%',\n"
    "          explanation: '(780 ÷ 1200) × 100 = 65%. The calculation is correct, but the conclusion is flawed.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'Identify the sampling method used.', hint1: 'People chose to respond — they were not randomly selected.', hint2: 'This is when people select themselves into a survey.', hint3: 'Self-selection (voluntary response) sampling.',\n"
    "          answer: 0, tolerance: 0, unit: '', checkType: 'skip', displayAnswer: 'Self-selection/voluntary response sampling',\n"
    "          explanation: 'An online poll where people choose to respond is self-selection (voluntary response) sampling.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'Give two reasons the results are unreliable.', hint1: 'Think about who is likely to respond to an online poll.', hint2: 'People with strong opinions are more likely to respond. Those without internet cannot participate.', hint3: 'Over-represents strong opinions; excludes non-internet users.',\n"
    "          answer: 0, tolerance: 0, unit: '', checkType: 'skip', displayAnswer: 'Over-represents strong opinions; excludes non-internet users',\n"
    "          explanation: 'Self-selection bias: people with strong opinions are more likely to respond. Non-internet users are excluded. Neither group represents the full public.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'Suggest a better sampling method.', hint1: 'The sample should give everyone an equal chance of being chosen.', hint2: 'Random methods are less biased.', hint3: 'Stratified random sample from the full population.',\n"
    "          answer: 0, tolerance: 0, unit: '', checkType: 'skip', displayAnswer: 'Stratified random sample from full population',\n"
    "          explanation: 'A stratified random sample from the full population would give more representative results.',\n"
    "        },\n"
    "      ],\n"
    "      workedExample: {\n"
    "        question: \"Online poll: 500 respond, 300 say 'yes'. Newspaper claims '60% of the public agree.' Assess this claim.\",\n"
    "        steps: [\n"
    "          'Percentage — (300 ÷ 500) × 100 = <strong>60%</strong>',\n"
    "          'Method — <strong>self-selection sampling</strong>',\n"
    "          'Reason 1 — <strong>people with stronger views more likely to respond</strong>',\n"
    "          'Reason 2 — <strong>excludes people without internet access</strong>',\n"
    "          'Better method — <strong>random telephone poll from the electoral register</strong>',\n"
    "        ],\n"
    "      },\n"
    "      sampleAnswer: { grade4: '65%. Self-selection sampling. Biased because only motivated people respond. Use random sampling.', grade6: '65%. Method: self-selection sampling. Unreliable because: (1) people with strong opinions over-respond; (2) excludes non-internet users. Better: stratified random sample.', grade8: '65% (780/1200). Method: voluntary response (self-selection) sampling. Limitations: (1) individuals with strong opinions are disproportionately represented; (2) internet access required, excluding part of the population. Improvement: stratified random sample from the full population using a valid sampling frame (e.g. electoral register).' },\n"
    "      examinerTip: 'For online polls, always critique: who responds (strong opinions), who is excluded (no internet), and what this means for representativeness.',\n"
    "      auditStatus: 'pending',\n"
    "    },\n"

    # ── stat-sampling-C02 ──────────────────────────────────────────
    "    {\n"
    "      id: 'stat-sampling-C02', subtopic: 'stat-sampling', band: 'C', marks: 3,\n"
    "      question: 'Three year groups: Year 10 = 240, Year 11 = 180, Year 12 = 80. Total = 500. Proportional sample of 75. (a) Find the sample size from each year group. (b) How many more are sampled from Year 10 than Year 12?',\n"
    "      steps: [\n"
    "        {\n"
    "          prompt: 'Find the sample size from Year 10.', hint1: 'Year 10: (240 ÷ 500) × 75', hint2: '= 0.48 × 75', hint3: '= 36',\n"
    "          answer: 36, tolerance: 0, unit: '',\n"
    "          explanation: 'Year 10: (240 ÷ 500) × 75 = 36. Year 11: (180/500)×75=27. Year 12: (80/500)×75=12. Check: 36+27+12=75 ✓',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'Find the sample size from Year 12.', hint1: 'Year 12: (80 ÷ 500) × 75', hint2: '= 0.16 × 75', hint3: '= 12',\n"
    "          answer: 12, tolerance: 0, unit: '',\n"
    "          explanation: 'Year 12: (80 ÷ 500) × 75 = 12.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'How many more are sampled from Year 10 than Year 12?', hint1: 'Difference = Year 10 − Year 12', hint2: '= 36 − 12', hint3: '= 24',\n"
    "          answer: 24, tolerance: 0, unit: '',\n"
    "          explanation: 'Difference = 36 − 12 = 24 more students from Year 10.',\n"
    "        },\n"
    "      ],\n"
    "      workedExample: {\n"
    "        question: 'Y7 = 300, Y8 = 200, Y9 = 100. Total = 600. Sample = 60. Find each year and the difference Y7 − Y9.',\n"
    "        steps: [\n"
    "          'Y7 — (300 ÷ 600) × 60 = <strong>30</strong>',\n"
    "          'Y8 — (200 ÷ 600) × 60 = <strong>20</strong>',\n"
    "          'Y9 — (100 ÷ 600) × 60 = <strong>10</strong>',\n"
    "          'Difference Y7 − Y9 — 30 − 10 = <strong>20</strong>',\n"
    "        ],\n"
    "      },\n"
    "      sampleAnswer: { grade4: 'Year 10: 36; Year 12: 12; difference = 24.', grade6: 'Year 10: (240/500)×75=36. Year 11: 27. Year 12: (80/500)×75=12. Total: 75 ✓. Difference: 36−12=24.', grade8: 'Sampling fraction = 75/500 = 0.15. Year 10: 240×0.15=36; Year 11: 180×0.15=27; Year 12: 80×0.15=12. Total=75 ✓. Year 10 provides 36−12=24 more than Year 12.' },\n"
    "      examinerTip: 'Work out all strata, check they sum to the required sample, then answer the specific comparison asked.',\n"
    "      auditStatus: 'pending',\n"
    "    },\n"

    # ── stat-sampling-C03 ──────────────────────────────────────────
    "    {\n"
    "      id: 'stat-sampling-C03', subtopic: 'stat-sampling', band: 'C', marks: 3,\n"
    "      question: 'A factory runs 3 shifts: morning (200 items), afternoon (300 items), night (100 items). Total = 600. Stratified sample of 60. (a) How many items from each shift? (b) 4 morning items are found defective. Estimate total defective items across all 600.',\n"
    "      steps: [\n"
    "        {\n"
    "          prompt: 'How many items are sampled from the morning shift?', hint1: 'Morning: (200 ÷ 600) × 60', hint2: '= (1/3) × 60', hint3: '= 20; afternoon: 30; night: 10 — check: 60 ✓',\n"
    "          answer: 20, tolerance: 0, unit: '',\n"
    "          explanation: 'Morning: (200/600)×60=20. Afternoon: (300/600)×60=30. Night: (100/600)×60=10. Total: 60 ✓',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'Find the defect rate from the morning sample (4 defective out of 20).', hint1: 'Rate = defective ÷ morning sample size', hint2: '= 4 ÷ 20', hint3: '= 0.2',\n"
    "          answer: 0.2, tolerance: 0.005, unit: '',\n"
    "          explanation: 'Defect rate = 4 ÷ 20 = 0.2 (20%).',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'Estimate the total defective items across all 600 items.', hint1: 'Apply rate to total production', hint2: '0.2 × 600', hint3: '= 120',\n"
    "          answer: 120, tolerance: 0, unit: '',\n"
    "          explanation: 'Estimated total defective = 0.2 × 600 = 120 items.',\n"
    "        },\n"
    "      ],\n"
    "      workedExample: {\n"
    "        question: '2 shifts: day (150 items), night (50 items). Total = 200. Sample = 40. 3 defective in day sample. Estimate total defective.',\n"
    "        steps: [\n"
    "          'Day sample — (150 ÷ 200) × 40 = <strong>30</strong>',\n"
    "          'Night sample — (50 ÷ 200) × 40 = <strong>10</strong>',\n"
    "          'Defect rate — 3 ÷ 30 = <strong>0.1</strong>',\n"
    "          'Total estimated defective — 0.1 × 200 = <strong>20</strong>',\n"
    "        ],\n"
    "      },\n"
    "      sampleAnswer: { grade4: 'Morning: 20; afternoon: 30; night: 10. Defect rate = 0.2. Estimated defective = 120.', grade6: 'Morning: (200/600)×60=20. Afternoon: 30. Night: 10. Total: 60 ✓. Defect rate = 4/20=0.2. Estimated total defective = 0.2×600=120.', grade8: 'Stratified sample: morning 20, afternoon 30, night 10 (total 60 ✓). Defect rate from morning = 4/20 = 0.2. Assuming this rate applies across all production: estimated defectives = 0.2 × 600 = 120 items.' },\n"
    "      examinerTip: 'When estimating a total from a stratified sample, use the overall defect rate (from the whole sample or one stratum if specified) and apply it to the full population.',\n"
    "      auditStatus: 'pending',\n"
    "    },\n"

    # ── stat-sampling-C04 ──────────────────────────────────────────
    "    {\n"
    "      id: 'stat-sampling-C04', subtopic: 'stat-sampling', band: 'C', marks: 4,\n"
    "      question: 'A student randomly samples 10 from a class of 30. The true class mean is 62. Their sample mean is 58. (a) Find the difference. (b) Is this evidence of bias? (c) What would happen with a larger sample of 25? (d) What would definitely reduce bias?',\n"
    "      steps: [\n"
    "        {\n"
    "          prompt: 'Find the difference between the population mean and the sample mean.', hint1: 'Difference = population mean − sample mean', hint2: '= 62 − 58', hint3: '= 4',\n"
    "          answer: 4, tolerance: 0, unit: '',\n"
    "          explanation: 'Difference = 62 − 58 = 4. The sample mean is 4 below the true mean.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'Is a difference of 4 evidence of bias in the sampling method?', hint1: 'Bias means the method systematically produces wrong results.', hint2: 'A single sample can differ from the true mean by chance.', hint3: 'Not necessarily bias — this could be natural sampling variability.',\n"
    "          answer: 0, tolerance: 0, unit: '', checkType: 'skip', displayAnswer: 'Sampling variability — not necessarily bias',\n"
    "          explanation: 'A single sample mean of 58 when the true mean is 62 is not evidence of bias. Random sampling produces variability — the sample mean will rarely equal the population mean exactly.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'If the sample size increased to 25, what effect would this have?', hint1: 'Larger samples produce more reliable estimates.', hint2: 'But a flawed method can still produce biased results.', hint3: 'Larger sample reduces sampling variability but does not eliminate methodological bias.',\n"
    "          answer: 0, tolerance: 0, unit: '', checkType: 'skip', displayAnswer: 'Larger sample reduces variability but not methodological bias',\n"
    "          explanation: 'A larger sample reduces the standard error (sampling variability), making the sample mean likely closer to the true mean. However, if the sampling method is flawed, bias remains.',\n"
    "        },\n"
    "        {\n"
    "          prompt: 'What would definitely reduce bias in the sampling method?', hint1: 'Bias comes from the selection method, not just sample size.', hint2: 'A truly random method gives everyone an equal chance.', hint3: 'Use simple random sampling (e.g. random number generator).',\n"
    "          answer: 0, tolerance: 0, unit: '', checkType: 'skip', displayAnswer: 'Truly random selection method reduces bias',\n"
    "          explanation: 'Using a truly random selection method (e.g. simple random sampling with a random number generator) ensures every member has an equal chance of selection, which reduces systematic bias.',\n"
    "        },\n"
    "      ],\n"
    "      workedExample: {\n"
    "        question: 'Sample of 5 from class of 25 (true mean = 70). Sample mean = 65. Is this bias? What helps?',\n"
    "        steps: [\n"
    "          'Difference — 70 − 65 = <strong>5</strong>',\n"
    "          'Bias? — <strong>not necessarily</strong>; could be chance variation with small sample',\n"
    "          'Larger sample — sample of 20 would give a <strong>more reliable estimate</strong> (less variability)',\n"
    "          'Reduces bias — <strong>truly random selection</strong> (random number generator)',\n"
    "        ],\n"
    "      },\n"
    "      sampleAnswer: { grade4: 'Difference = 4. This is not proof of bias. Larger sample helps. Random selection reduces bias.', grade6: 'Difference = 62 − 58 = 4. This is not necessarily bias — sampling variability means a random sample rarely gives exactly the population mean. Larger sample reduces variability. Truly random selection reduces bias.', grade8: 'Difference = 4. This is sampling variability, not evidence of bias — any single random sample can deviate from the population mean. Increasing sample size to 25 reduces standard error but does not remove methodological bias if the method is flawed. To reduce bias: use simple random sampling (e.g. assign each student a number, use a random number generator).' },\n"
    "      examinerTip: 'Distinguish between sampling variability (random fluctuation, reduced by larger n) and sampling bias (systematic error, reduced by better method). Examiners look for this distinction.',\n"
    "      auditStatus: 'pending',\n"
    "    },\n"
)

OLD_M6 = "M6: ['stat-averages','stat-charts','stat-scatter','stat-cumulative'],"
NEW_M6 = "M6: ['stat-averages','stat-charts','stat-scatter','stat-cumulative','stat-boxplots','stat-sampling'],"

with open(FILE, 'r', encoding='utf-8') as f:
    content = f.read()

pos = content.find(MARKER)
if pos == -1:
    print("MARKER NOT FOUND")
    sys.exit(1)

print(f"Inserting at character position {pos}")

content = content[:pos] + NEW + content[pos:]

if OLD_M6 in content:
    content = content.replace(OLD_M6, NEW_M6)
    print("M6 array updated — added stat-boxplots and stat-sampling")
else:
    print("WARNING: M6 array marker not found — M6 was NOT updated")

with open(FILE, 'w', encoding='utf-8') as f:
    f.write(content)

print("Done — inserted SAMPLING section header + 15 stat-sampling questions (5A, 6B, 4C) into js/maths-questions.js")
print("Done — M6 curriculum array updated to include stat-boxplots and stat-sampling")
